// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tables.proto

package tables

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	schema "pixur.org/pixur/be/schema"
	_ "pixur.org/pixur/be/schema/db/model"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PicRow struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IndexOrder           int64       `protobuf:"varint,2,opt,name=index_order,json=indexOrder,proto3" json:"index_order,omitempty"`
	ScoreOrder           int32       `protobuf:"varint,5,opt,name=score_order,json=scoreOrder,proto3" json:"score_order,omitempty"`
	SchedOrder           int32       `protobuf:"varint,6,opt,name=sched_order,json=schedOrder,proto3" json:"sched_order,omitempty"`
	Data                 *schema.Pic `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PicRow) Reset()         { *m = PicRow{} }
func (m *PicRow) String() string { return proto.CompactTextString(m) }
func (*PicRow) ProtoMessage()    {}
func (*PicRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{0}
}

func (m *PicRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicRow.Unmarshal(m, b)
}
func (m *PicRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicRow.Marshal(b, m, deterministic)
}
func (m *PicRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicRow.Merge(m, src)
}
func (m *PicRow) XXX_Size() int {
	return xxx_messageInfo_PicRow.Size(m)
}
func (m *PicRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PicRow.DiscardUnknown(m)
}

var xxx_messageInfo_PicRow proto.InternalMessageInfo

func (m *PicRow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PicRow) GetIndexOrder() int64 {
	if m != nil {
		return m.IndexOrder
	}
	return 0
}

func (m *PicRow) GetScoreOrder() int32 {
	if m != nil {
		return m.ScoreOrder
	}
	return 0
}

func (m *PicRow) GetSchedOrder() int32 {
	if m != nil {
		return m.SchedOrder
	}
	return 0
}

func (m *PicRow) GetData() *schema.Pic {
	if m != nil {
		return m.Data
	}
	return nil
}

type TagRow struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data                 *schema.Tag `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TagRow) Reset()         { *m = TagRow{} }
func (m *TagRow) String() string { return proto.CompactTextString(m) }
func (*TagRow) ProtoMessage()    {}
func (*TagRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{1}
}

func (m *TagRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagRow.Unmarshal(m, b)
}
func (m *TagRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagRow.Marshal(b, m, deterministic)
}
func (m *TagRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagRow.Merge(m, src)
}
func (m *TagRow) XXX_Size() int {
	return xxx_messageInfo_TagRow.Size(m)
}
func (m *TagRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TagRow.DiscardUnknown(m)
}

var xxx_messageInfo_TagRow proto.InternalMessageInfo

func (m *TagRow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TagRow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TagRow) GetData() *schema.Tag {
	if m != nil {
		return m.Data
	}
	return nil
}

type PicTagRow struct {
	PicId                int64          `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	TagId                int64          `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Data                 *schema.PicTag `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PicTagRow) Reset()         { *m = PicTagRow{} }
func (m *PicTagRow) String() string { return proto.CompactTextString(m) }
func (*PicTagRow) ProtoMessage()    {}
func (*PicTagRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{2}
}

func (m *PicTagRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicTagRow.Unmarshal(m, b)
}
func (m *PicTagRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicTagRow.Marshal(b, m, deterministic)
}
func (m *PicTagRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicTagRow.Merge(m, src)
}
func (m *PicTagRow) XXX_Size() int {
	return xxx_messageInfo_PicTagRow.Size(m)
}
func (m *PicTagRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PicTagRow.DiscardUnknown(m)
}

var xxx_messageInfo_PicTagRow proto.InternalMessageInfo

func (m *PicTagRow) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicTagRow) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *PicTagRow) GetData() *schema.PicTag {
	if m != nil {
		return m.Data
	}
	return nil
}

type PicIdentRow struct {
	PicId                int64                `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	Type                 schema.PicIdent_Type `protobuf:"varint,2,opt,name=type,proto3,enum=pixur.PicIdent_Type" json:"type,omitempty"`
	Value                []byte               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Data                 *schema.PicIdent     `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PicIdentRow) Reset()         { *m = PicIdentRow{} }
func (m *PicIdentRow) String() string { return proto.CompactTextString(m) }
func (*PicIdentRow) ProtoMessage()    {}
func (*PicIdentRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{3}
}

func (m *PicIdentRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicIdentRow.Unmarshal(m, b)
}
func (m *PicIdentRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicIdentRow.Marshal(b, m, deterministic)
}
func (m *PicIdentRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicIdentRow.Merge(m, src)
}
func (m *PicIdentRow) XXX_Size() int {
	return xxx_messageInfo_PicIdentRow.Size(m)
}
func (m *PicIdentRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PicIdentRow.DiscardUnknown(m)
}

var xxx_messageInfo_PicIdentRow proto.InternalMessageInfo

func (m *PicIdentRow) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicIdentRow) GetType() schema.PicIdent_Type {
	if m != nil {
		return m.Type
	}
	return schema.PicIdent_UNKNOWN
}

func (m *PicIdentRow) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PicIdentRow) GetData() *schema.PicIdent {
	if m != nil {
		return m.Data
	}
	return nil
}

type PicCommentRow struct {
	PicId                int64              `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	CommentId            int64              `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Data                 *schema.PicComment `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PicCommentRow) Reset()         { *m = PicCommentRow{} }
func (m *PicCommentRow) String() string { return proto.CompactTextString(m) }
func (*PicCommentRow) ProtoMessage()    {}
func (*PicCommentRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{4}
}

func (m *PicCommentRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicCommentRow.Unmarshal(m, b)
}
func (m *PicCommentRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicCommentRow.Marshal(b, m, deterministic)
}
func (m *PicCommentRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicCommentRow.Merge(m, src)
}
func (m *PicCommentRow) XXX_Size() int {
	return xxx_messageInfo_PicCommentRow.Size(m)
}
func (m *PicCommentRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PicCommentRow.DiscardUnknown(m)
}

var xxx_messageInfo_PicCommentRow proto.InternalMessageInfo

func (m *PicCommentRow) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicCommentRow) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PicCommentRow) GetData() *schema.PicComment {
	if m != nil {
		return m.Data
	}
	return nil
}

type PicVoteRow struct {
	PicId                int64           `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	UserId               int64           `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 *schema.PicVote `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PicVoteRow) Reset()         { *m = PicVoteRow{} }
func (m *PicVoteRow) String() string { return proto.CompactTextString(m) }
func (*PicVoteRow) ProtoMessage()    {}
func (*PicVoteRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{5}
}

func (m *PicVoteRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicVoteRow.Unmarshal(m, b)
}
func (m *PicVoteRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicVoteRow.Marshal(b, m, deterministic)
}
func (m *PicVoteRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicVoteRow.Merge(m, src)
}
func (m *PicVoteRow) XXX_Size() int {
	return xxx_messageInfo_PicVoteRow.Size(m)
}
func (m *PicVoteRow) XXX_DiscardUnknown() {
	xxx_messageInfo_PicVoteRow.DiscardUnknown(m)
}

var xxx_messageInfo_PicVoteRow proto.InternalMessageInfo

func (m *PicVoteRow) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicVoteRow) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicVoteRow) GetData() *schema.PicVote {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserRow struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ident                string       `protobuf:"bytes,2,opt,name=ident,proto3" json:"ident,omitempty"`
	Data                 *schema.User `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserRow) Reset()         { *m = UserRow{} }
func (m *UserRow) String() string { return proto.CompactTextString(m) }
func (*UserRow) ProtoMessage()    {}
func (*UserRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e429e24f449e1ed, []int{6}
}

func (m *UserRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRow.Unmarshal(m, b)
}
func (m *UserRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRow.Marshal(b, m, deterministic)
}
func (m *UserRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRow.Merge(m, src)
}
func (m *UserRow) XXX_Size() int {
	return xxx_messageInfo_UserRow.Size(m)
}
func (m *UserRow) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRow.DiscardUnknown(m)
}

var xxx_messageInfo_UserRow proto.InternalMessageInfo

func (m *UserRow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRow) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *UserRow) GetData() *schema.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PicRow)(nil), "pixur.tables.PicRow")
	proto.RegisterType((*TagRow)(nil), "pixur.tables.TagRow")
	proto.RegisterType((*PicTagRow)(nil), "pixur.tables.PicTagRow")
	proto.RegisterType((*PicIdentRow)(nil), "pixur.tables.PicIdentRow")
	proto.RegisterType((*PicCommentRow)(nil), "pixur.tables.PicCommentRow")
	proto.RegisterType((*PicVoteRow)(nil), "pixur.tables.PicVoteRow")
	proto.RegisterType((*UserRow)(nil), "pixur.tables.UserRow")
}

func init() { proto.RegisterFile("tables.proto", fileDescriptor_9e429e24f449e1ed) }

var fileDescriptor_9e429e24f449e1ed = []byte{
	// 721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0x26, 0xb6, 0x93, 0x4c, 0xbe, 0xdc, 0x2d, 0x94, 0x92, 0x8a, 0x76, 0x6b, 0x1a, 0x29,
	0xa7, 0x44, 0x14, 0x04, 0x12, 0xe2, 0x50, 0xa5, 0x5c, 0x8a, 0x10, 0x44, 0x69, 0xda, 0x03, 0x97,
	0xca, 0xb1, 0x57, 0xc9, 0x4a, 0x49, 0x6c, 0x6c, 0x87, 0xb6, 0x37, 0x9f, 0x2d, 0x8e, 0xdc, 0xf9,
	0x31, 0xfc, 0x07, 0xfe, 0x08, 0x37, 0x4e, 0x68, 0x3f, 0x6c, 0xc7, 0x95, 0x50, 0xd5, 0x4b, 0xb5,
	0x3b, 0xf3, 0x66, 0xde, 0x7b, 0x33, 0xde, 0x06, 0x1a, 0x91, 0x3d, 0x5d, 0xd0, 0xb0, 0xef, 0x07,
	0x5e, 0xe4, 0xe1, 0x86, 0xcf, 0x6e, 0xd6, 0x41, 0x5f, 0xc6, 0x3a, 0x5d, 0x79, 0xf3, 0x82, 0xd9,
	0x40, 0x9c, 0x06, 0x53, 0x3a, 0x08, 0x9d, 0x39, 0x5d, 0xda, 0xf2, 0x2e, 0x8b, 0x3a, 0xfd, 0xff,
	0xc3, 0xdc, 0xe9, 0x60, 0xe9, 0xb9, 0x74, 0x21, 0xff, 0x4a, 0xbc, 0xf5, 0xa7, 0x04, 0xc6, 0x88,
	0x39, 0x63, 0xef, 0x1a, 0xef, 0x41, 0x89, 0xb9, 0xbb, 0x88, 0xa0, 0x5e, 0x79, 0x58, 0x4f, 0x62,
	0x52, 0x01, 0xfd, 0xcc, 0x3d, 0xf5, 0x16, 0xe3, 0x12, 0x73, 0xf1, 0x2b, 0xa8, 0xb3, 0x95, 0x4b,
	0x6f, 0xae, 0xbc, 0xc0, 0xa5, 0xc1, 0x6e, 0x49, 0xa0, 0xb6, 0x93, 0x98, 0xb4, 0xa1, 0x79, 0xc6,
	0x13, 0x9f, 0x79, 0x9c, 0xa3, 0x81, 0x65, 0x57, 0xfc, 0x1a, 0xea, 0xa1, 0xe3, 0x05, 0x54, 0x55,
	0xe9, 0x04, 0xf5, 0xf4, 0xe1, 0xe3, 0x24, 0x26, 0x5b, 0xd0, 0xfe, 0xe8, 0x5d, 0xd3, 0xe0, 0x9c,
	0x67, 0x87, 0xde, 0x7a, 0xe5, 0x8e, 0x41, 0x20, 0x37, 0xea, 0xe6, 0xd4, 0x55, 0x75, 0xc6, 0x66,
	0xdd, 0x85, 0xef, 0xdf, 0xad, 0x9b, 0x53, 0x57, 0xd6, 0xed, 0x83, 0xe6, 0xda, 0x91, 0xbd, 0xab,
	0x11, 0xd4, 0xab, 0x1f, 0x83, 0x1a, 0x06, 0xf7, 0x27, 0xe2, 0x6f, 0xd7, 0x49, 0x4c, 0xbe, 0x82,
	0x36, 0x62, 0x4e, 0x88, 0x0d, 0x6e, 0xd7, 0x44, 0xf8, 0xa0, 0xe0, 0x4c, 0x04, 0x4b, 0x1d, 0xc8,
	0x3d, 0x71, 0xc0, 0x86, 0x89, 0x14, 0x70, 0x9e, 0xab, 0x3d, 0x28, 0xa8, 0xcd, 0x01, 0xa9, 0xac,
	0x0f, 0x5a, 0xb5, 0x6c, 0x6a, 0xe3, 0x1a, 0x0b, 0xaf, 0xe6, 0xcc, 0x75, 0xe9, 0xca, 0xfa, 0x8e,
	0xc0, 0x98, 0xd8, 0xb3, 0x7b, 0xa7, 0x7e, 0x08, 0xda, 0xca, 0x5e, 0x52, 0x31, 0xee, 0xda, 0xb0,
	0x99, 0xc4, 0xa4, 0x06, 0x95, 0x4f, 0xf6, 0x92, 0x72, 0x80, 0x48, 0x65, 0x96, 0xcb, 0x05, 0xcb,
	0xbc, 0xb9, 0xb4, 0x6c, 0x25, 0x31, 0xd9, 0x07, 0x6d, 0x62, 0xcf, 0x72, 0xcb, 0x2d, 0xd9, 0xd6,
	0x2c, 0x77, 0x34, 0xde, 0xcc, 0xfa, 0x89, 0xa0, 0x36, 0x62, 0x8e, 0x52, 0xd4, 0x05, 0xc3, 0x67,
	0xce, 0x55, 0xa6, 0xaa, 0x95, 0xc4, 0x04, 0xa0, 0x3a, 0x62, 0x8e, 0x14, 0xa6, 0xfb, 0xfc, 0xc4,
	0x61, 0x91, 0x3d, 0xe3, 0xb0, 0xd2, 0x26, 0x6c, 0x62, 0xcf, 0x14, 0x2c, 0xe2, 0x27, 0x6e, 0x61,
	0x43, 0x5f, 0x33, 0x5f, 0x49, 0x2e, 0xf1, 0x30, 0x89, 0xc9, 0x33, 0xa8, 0xc8, 0x58, 0x88, 0x71,
	0xca, 0x9f, 0x12, 0x98, 0xc8, 0xfa, 0x8b, 0xa0, 0x2e, 0x04, 0xd0, 0x55, 0xf4, 0x00, 0x8d, 0x6f,
	0x40, 0x8b, 0x6e, 0x7d, 0x39, 0xbf, 0xd6, 0xf1, 0xa3, 0x9c, 0x5c, 0x34, 0xea, 0x4f, 0x6e, 0x7d,
	0x9a, 0x4e, 0x95, 0x9f, 0xc5, 0x54, 0x79, 0x01, 0x3e, 0x02, 0xfd, 0x9b, 0xbd, 0x58, 0x53, 0x21,
	0xbb, 0x91, 0xb6, 0xbf, 0xe4, 0x21, 0xd1, 0x5e, 0x24, 0xf1, 0xf3, 0xc2, 0xe7, 0xd6, 0xbe, 0xd3,
	0x5e, 0xb9, 0x3b, 0x49, 0x62, 0xf2, 0x4e, 0xcc, 0x57, 0x44, 0x43, 0xfc, 0x24, 0xf3, 0x27, 0xb8,
	0x14, 0x93, 0x89, 0xf0, 0x4e, 0x31, 0x50, 0xea, 0xe8, 0xa2, 0xc2, 0xfa, 0x8d, 0xa0, 0x39, 0x62,
	0xce, 0xa9, 0xb7, 0x5c, 0x3e, 0xcc, 0xfe, 0x0b, 0x00, 0x47, 0x16, 0xe5, 0x6b, 0xc2, 0x49, 0x4c,
	0x5a, 0xd0, 0x50, 0xcd, 0x24, 0xbc, 0xe6, 0xa4, 0x37, 0xdc, 0x2d, 0xac, 0x6b, 0x2b, 0xb7, 0x94,
	0xb2, 0x4b, 0x53, 0xef, 0x93, 0x98, 0x9c, 0x88, 0x95, 0xa8, 0x78, 0x88, 0x77, 0x32, 0x5b, 0x1b,
	0xa4, 0x26, 0xc2, 0x4f, 0x0b, 0xf7, 0x72, 0xa7, 0x96, 0x51, 0x5b, 0xbf, 0x10, 0xc0, 0x88, 0x39,
	0x97, 0x5e, 0x44, 0x1f, 0xe0, 0xaa, 0x07, 0x95, 0x75, 0x48, 0x83, 0xdc, 0x52, 0x3b, 0x89, 0x49,
	0x1d, 0x6a, 0x17, 0x21, 0x0d, 0x24, 0xd0, 0x58, 0x8b, 0x23, 0xb6, 0x0a, 0x66, 0x5a, 0xb9, 0x19,
	0xc1, 0xb8, 0xb9, 0x9e, 0xaa, 0x0a, 0x86, 0x78, 0x3b, 0xb3, 0x91, 0xb2, 0x98, 0x08, 0xef, 0x65,
	0x97, 0x34, 0x6b, 0x96, 0x3b, 0x86, 0x24, 0xb4, 0x7e, 0x20, 0xa8, 0xf0, 0xe3, 0xbd, 0xaf, 0xf9,
	0x08, 0x74, 0xc6, 0x17, 0xaa, 0x9e, 0xb3, 0xb2, 0x27, 0x76, 0x2c, 0xec, 0x89, 0x24, 0x3e, 0x28,
	0x88, 0xae, 0x2b, 0xd1, 0x82, 0x40, 0x2a, 0xee, 0x26, 0x31, 0x39, 0x04, 0x9d, 0x47, 0xf2, 0x27,
	0x6d, 0xaa, 0xde, 0x66, 0x59, 0x7d, 0x35, 0xc3, 0xea, 0x17, 0x43, 0xfe, 0x74, 0x4c, 0x0d, 0xf1,
	0xaf, 0xfe, 0xe5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xf0, 0x19, 0xf3, 0x5f, 0x06, 0x00,
	0x00,
}
