// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyType int32

const (
	KeyType_NONE    KeyType = 0
	KeyType_PRIMARY KeyType = 1
	KeyType_INDEX   KeyType = 2
	KeyType_UNIQUE  KeyType = 3
)

var KeyType_name = map[int32]string{
	0: "NONE",
	1: "PRIMARY",
	2: "INDEX",
	3: "UNIQUE",
}

var KeyType_value = map[string]int32{
	"NONE":    0,
	"PRIMARY": 1,
	"INDEX":   2,
	"UNIQUE":  3,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

type TableOptions struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  []*TableOptions_Key `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TableOptions) Reset()         { *m = TableOptions{} }
func (m *TableOptions) String() string { return proto.CompactTextString(m) }
func (*TableOptions) ProtoMessage()    {}
func (*TableOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *TableOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableOptions.Unmarshal(m, b)
}
func (m *TableOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableOptions.Marshal(b, m, deterministic)
}
func (m *TableOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableOptions.Merge(m, src)
}
func (m *TableOptions) XXX_Size() int {
	return xxx_messageInfo_TableOptions.Size(m)
}
func (m *TableOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TableOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TableOptions proto.InternalMessageInfo

func (m *TableOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TableOptions) GetKey() []*TableOptions_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type TableOptions_Key struct {
	Col                  []string `protobuf:"bytes,1,rep,name=col,proto3" json:"col,omitempty"`
	KeyType              KeyType  `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=pixur.be.schema.db.model.KeyType" json:"key_type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableOptions_Key) Reset()         { *m = TableOptions_Key{} }
func (m *TableOptions_Key) String() string { return proto.CompactTextString(m) }
func (*TableOptions_Key) ProtoMessage()    {}
func (*TableOptions_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0, 0}
}

func (m *TableOptions_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableOptions_Key.Unmarshal(m, b)
}
func (m *TableOptions_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableOptions_Key.Marshal(b, m, deterministic)
}
func (m *TableOptions_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableOptions_Key.Merge(m, src)
}
func (m *TableOptions_Key) XXX_Size() int {
	return xxx_messageInfo_TableOptions_Key.Size(m)
}
func (m *TableOptions_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_TableOptions_Key.DiscardUnknown(m)
}

var xxx_messageInfo_TableOptions_Key proto.InternalMessageInfo

func (m *TableOptions_Key) GetCol() []string {
	if m != nil {
		return m.Col
	}
	return nil
}

func (m *TableOptions_Key) GetKeyType() KeyType {
	if m != nil {
		return m.KeyType
	}
	return KeyType_NONE
}

func (m *TableOptions_Key) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FieldOptions struct {
	ColFn                string   `protobuf:"bytes,1,opt,name=col_fn,json=colFn,proto3" json:"col_fn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetColFn() string {
	if m != nil {
		return m.ColFn
	}
	return ""
}

var E_TabOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*TableOptions)(nil),
	Field:         65537,
	Name:          "pixur.be.schema.db.model.tab_opts",
	Tag:           "bytes,65537,opt,name=tab_opts",
	Filename:      "model.proto",
}

var E_FieldOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         65537,
	Name:          "pixur.be.schema.db.model.field_opts",
	Tag:           "bytes,65537,opt,name=field_opts",
	Filename:      "model.proto",
}

func init() {
	proto.RegisterEnum("pixur.be.schema.db.model.KeyType", KeyType_name, KeyType_value)
	proto.RegisterType((*TableOptions)(nil), "pixur.be.schema.db.model.TableOptions")
	proto.RegisterType((*TableOptions_Key)(nil), "pixur.be.schema.db.model.TableOptions.Key")
	proto.RegisterType((*FieldOptions)(nil), "pixur.be.schema.db.model.FieldOptions")
	proto.RegisterExtension(E_TabOpts)
	proto.RegisterExtension(E_FieldOpts)
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0xab, 0xd3, 0x40,
	0x14, 0x85, 0x4d, 0xd3, 0xd7, 0x34, 0x37, 0x0f, 0x09, 0x03, 0x42, 0x78, 0x20, 0xc6, 0xa2, 0x12,
	0xde, 0x62, 0x02, 0x75, 0x21, 0x3c, 0xde, 0x46, 0xb1, 0x85, 0x52, 0x9a, 0xea, 0xd0, 0x82, 0xba,
	0x29, 0x99, 0xe4, 0x26, 0x86, 0xa6, 0x99, 0x21, 0x33, 0x05, 0xb3, 0xd3, 0xdf, 0xe7, 0x9f, 0x92,
	0x26, 0xad, 0x16, 0xa4, 0xd0, 0xdd, 0x19, 0xe6, 0x9e, 0xfb, 0xdd, 0x73, 0xc0, 0xd9, 0x89, 0x14,
	0x4b, 0x2a, 0x6b, 0xa1, 0x05, 0xf1, 0x64, 0xf1, 0x63, 0x5f, 0x53, 0x8e, 0x54, 0x25, 0xdf, 0x71,
	0x17, 0xd3, 0x94, 0xd3, 0xf6, 0xff, 0xce, 0xcf, 0x85, 0xc8, 0x4b, 0x0c, 0xdb, 0x39, 0xbe, 0xcf,
	0xc2, 0x14, 0x55, 0x52, 0x17, 0x52, 0x8b, 0xba, 0xf3, 0x8e, 0x7e, 0x1b, 0x70, 0xbb, 0x8a, 0x79,
	0x89, 0x4b, 0xa9, 0x0b, 0x51, 0x29, 0x42, 0xa0, 0x5f, 0xc5, 0x3b, 0xf4, 0x0c, 0xdf, 0x08, 0x6c,
	0xd6, 0x6a, 0xf2, 0x08, 0xe6, 0x16, 0x1b, 0xaf, 0xe7, 0x9b, 0x81, 0x33, 0xbe, 0xa7, 0x97, 0x70,
	0xf4, 0x7c, 0x11, 0x9d, 0x63, 0xc3, 0x0e, 0xb6, 0xbb, 0x02, 0xcc, 0x39, 0x36, 0xc4, 0x05, 0x33,
	0x11, 0xa5, 0x67, 0xf8, 0x66, 0x60, 0xb3, 0x83, 0x24, 0x8f, 0x30, 0xdc, 0x62, 0xb3, 0xd1, 0x8d,
	0x44, 0xaf, 0xe7, 0x1b, 0xc1, 0xd3, 0xf1, 0xcb, 0xcb, 0xbb, 0xe7, 0xd8, 0xac, 0x1a, 0x89, 0xcc,
	0xda, 0x76, 0xe2, 0xef, 0xa1, 0xe6, 0xbf, 0x43, 0x47, 0xaf, 0xe1, 0x76, 0x5a, 0x60, 0x99, 0x9e,
	0xc2, 0x3c, 0x83, 0x41, 0x22, 0xca, 0x4d, 0x56, 0x1d, 0xe3, 0xdc, 0x24, 0xa2, 0x9c, 0x56, 0xf7,
	0xef, 0xc0, 0x3a, 0xae, 0x23, 0x43, 0xe8, 0x47, 0xcb, 0x68, 0xe2, 0x3e, 0x21, 0x0e, 0x58, 0x9f,
	0xd8, 0x6c, 0xf1, 0x9e, 0x7d, 0x75, 0x0d, 0x62, 0xc3, 0xcd, 0x2c, 0xfa, 0x38, 0xf9, 0xe2, 0xf6,
	0x08, 0xc0, 0x60, 0x1d, 0xcd, 0x3e, 0xaf, 0x27, 0xae, 0xf9, 0x90, 0xc2, 0x50, 0xc7, 0x7c, 0x23,
	0xa4, 0x56, 0xe4, 0x05, 0xed, 0xca, 0xa5, 0xa7, 0x72, 0xe9, 0x02, 0x95, 0x8a, 0xf3, 0x53, 0x01,
	0xde, 0xaf, 0x9f, 0x7d, 0xdf, 0x08, 0x9c, 0xf1, 0x9b, 0xeb, 0x0a, 0x63, 0x96, 0x8e, 0xf9, 0x52,
	0x6a, 0xf5, 0x90, 0x01, 0x64, 0x87, 0x14, 0x1d, 0xe7, 0xf9, 0x7f, 0x9c, 0xf3, 0x88, 0xd7, 0x50,
	0xce, 0xe7, 0x99, 0x9d, 0x1d, 0x5f, 0xea, 0xc3, 0xab, 0x6f, 0xa3, 0xce, 0x23, 0xea, 0x3c, 0x6c,
	0x55, 0xc8, 0x31, 0xec, 0xdc, 0x61, 0xca, 0xc3, 0xd6, 0xcd, 0x07, 0x2d, 0xf7, 0xed, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0x86, 0x0e, 0xef, 0x73, 0x02, 0x00, 0x00,
}
