// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package handlers is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ApiPic
	ApiPicTag
	ApiPicComment
	ApiUser
	ApiCapability
	LookupUserRequest
	LookupUserResponse
	UpdateUserRequest
	UpdateUserResponse
	ApiPicCommentTree
	LookupPicDetailsRequest
	LookupPicDetailsResponse
	FindIndexPicsRequest
	FindIndexPicsResponse
	AddPicTagsRequest
	AddPicTagsResponse
	CreatePicRequest
	CreatePicResponse
	FindSimilarPicsRequest
	FindSimilarPicsResponse
	IncrementViewCountRequest
	IncrementViewCountResponse
	PurgePicRequest
	PurgePicResponse
	SoftDeletePicRequest
	SoftDeletePicResponse
	UpsertPicRequest
	UpsertPicResponse
	GetXsrfTokenRequest
	GetXsrfTokenResponse
	CreateUserRequest
	CreateUserResponse
	GetRefreshTokenRequest
	GetRefreshTokenResponse
	PwtHeader
	PwtPayload
	AddPicCommentRequest
	AddPicCommentResponse
	DeleteTokenRequest
	DeleteTokenResponse
	UpsertPicVoteRequest
	UpsertPicVoteResponse
*/
package handlers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Copy of schema.proto
type DeletionReason int32

const (
	// The reason is not know, due to limitations of proto
	DeletionReason_UNKNOWN DeletionReason = 0
	// No specific reason.  This is a catch-all reason.
	DeletionReason_NONE DeletionReason = 1
	// The pic is in violation of the rules.
	DeletionReason_RULE_VIOLATION DeletionReason = 2
)

var DeletionReason_name = map[int32]string{
	0: "UNKNOWN",
	1: "NONE",
	2: "RULE_VIOLATION",
}
var DeletionReason_value = map[string]int32{
	"UNKNOWN":        0,
	"NONE":           1,
	"RULE_VIOLATION": 2,
}

func (x DeletionReason) String() string {
	return proto.EnumName(DeletionReason_name, int32(x))
}
func (DeletionReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ApiCapability_Cap int32

const (
	ApiCapability_UNKNOWN ApiCapability_Cap = 0
	// Can this user create and upload pictures
	ApiCapability_PIC_CREATE ApiCapability_Cap = 1
	// Can this user view the actual image data (grants pic token)
	ApiCapability_PIC_READ ApiCapability_Cap = 2
	// Can this user perform general pic index queries?
	ApiCapability_PIC_INDEX ApiCapability_Cap = 3
	// Can this user soft delete a pic?
	ApiCapability_PIC_SOFT_DELETE ApiCapability_Cap = 5
	// Can this user hard delete a pic?
	ApiCapability_PIC_HARD_DELETE ApiCapability_Cap = 6
	// Can this user purge a pic?
	ApiCapability_PIC_PURGE ApiCapability_Cap = 7
	// Can this user increment the pic view counter?
	ApiCapability_PIC_UPDATE_VIEW_COUNTER ApiCapability_Cap = 8
	// Can this user add tags and pic tags?
	ApiCapability_PIC_TAG_CREATE ApiCapability_Cap = 9
	// Can this user create comments?
	ApiCapability_PIC_COMMENT_CREATE ApiCapability_Cap = 10
	// Can this user vote?
	ApiCapability_PIC_VOTE_CREATE ApiCapability_Cap = 11
	// Can this user create other users?
	ApiCapability_USER_CREATE ApiCapability_Cap = 4
	// Can this user modify capabilities?
	ApiCapability_USER_UPDATE_CAPABILITY ApiCapability_Cap = 12
)

var ApiCapability_Cap_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "PIC_CREATE",
	2:  "PIC_READ",
	3:  "PIC_INDEX",
	5:  "PIC_SOFT_DELETE",
	6:  "PIC_HARD_DELETE",
	7:  "PIC_PURGE",
	8:  "PIC_UPDATE_VIEW_COUNTER",
	9:  "PIC_TAG_CREATE",
	10: "PIC_COMMENT_CREATE",
	11: "PIC_VOTE_CREATE",
	4:  "USER_CREATE",
	12: "USER_UPDATE_CAPABILITY",
}
var ApiCapability_Cap_value = map[string]int32{
	"UNKNOWN":                 0,
	"PIC_CREATE":              1,
	"PIC_READ":                2,
	"PIC_INDEX":               3,
	"PIC_SOFT_DELETE":         5,
	"PIC_HARD_DELETE":         6,
	"PIC_PURGE":               7,
	"PIC_UPDATE_VIEW_COUNTER": 8,
	"PIC_TAG_CREATE":          9,
	"PIC_COMMENT_CREATE":      10,
	"PIC_VOTE_CREATE":         11,
	"USER_CREATE":             4,
	"USER_UPDATE_CAPABILITY":  12,
}

func (x ApiCapability_Cap) String() string {
	return proto.EnumName(ApiCapability_Cap_name, int32(x))
}
func (ApiCapability_Cap) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type PwtHeader_Algorithm int32

const (
	PwtHeader_UNKNOWN PwtHeader_Algorithm = 0
	PwtHeader_HS256   PwtHeader_Algorithm = 1
	PwtHeader_RS256   PwtHeader_Algorithm = 2
)

var PwtHeader_Algorithm_name = map[int32]string{
	0: "UNKNOWN",
	1: "HS256",
	2: "RS256",
}
var PwtHeader_Algorithm_value = map[string]int32{
	"UNKNOWN": 0,
	"HS256":   1,
	"RS256":   2,
}

func (x PwtHeader_Algorithm) String() string {
	return proto.EnumName(PwtHeader_Algorithm_name, int32(x))
}
func (PwtHeader_Algorithm) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{34, 0} }

type PwtPayload_Type int32

const (
	PwtPayload_UNKNOWN PwtPayload_Type = 0
	PwtPayload_REFRESH PwtPayload_Type = 1
	PwtPayload_AUTH    PwtPayload_Type = 2
	PwtPayload_PIX     PwtPayload_Type = 3
)

var PwtPayload_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "REFRESH",
	2: "AUTH",
	3: "PIX",
}
var PwtPayload_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"REFRESH": 1,
	"AUTH":    2,
	"PIX":     3,
}

func (x PwtPayload_Type) String() string {
	return proto.EnumName(PwtPayload_Type_name, int32(x))
}
func (PwtPayload_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{35, 0} }

type UpsertPicVoteRequest_Vote int32

const (
	UpsertPicVoteRequest_UNKNOWN UpsertPicVoteRequest_Vote = 0
	UpsertPicVoteRequest_UP      UpsertPicVoteRequest_Vote = 1
	UpsertPicVoteRequest_DOWN    UpsertPicVoteRequest_Vote = 2
	UpsertPicVoteRequest_NEUTRAL UpsertPicVoteRequest_Vote = 3
)

var UpsertPicVoteRequest_Vote_name = map[int32]string{
	0: "UNKNOWN",
	1: "UP",
	2: "DOWN",
	3: "NEUTRAL",
}
var UpsertPicVoteRequest_Vote_value = map[string]int32{
	"UNKNOWN": 0,
	"UP":      1,
	"DOWN":    2,
	"NEUTRAL": 3,
}

func (x UpsertPicVoteRequest_Vote) String() string {
	return proto.EnumName(UpsertPicVoteRequest_Vote_name, int32(x))
}
func (UpsertPicVoteRequest_Vote) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{40, 0}
}

type ApiPic struct {
	// id is the unique identifier for the pic, in varint form
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// width is the width of pic
	Width int32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	// height is the height of the pic
	Height int32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	// version is the version of the pic.  It is used when updating the pic.
	Version int64 `protobuf:"fixed64,4,opt,name=version" json:"version,omitempty"`
	// type is the mime type of the pic. (JPEG, GIF, PNG, or WEBM)
	Type string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	// relative_url is the location of the pic file relative to the root dir.
	RelativeUrl string `protobuf:"bytes,6,opt,name=relative_url,json=relativeUrl" json:"relative_url,omitempty"`
	// thumbnail_relative_url is the location of the the pic thumbnail
	// relative to the root dir.
	ThumbnailRelativeUrl string `protobuf:"bytes,7,opt,name=thumbnail_relative_url,json=thumbnailRelativeUrl" json:"thumbnail_relative_url,omitempty"`
	// pending_deletion indicates if the pic may be deleted soon.
	PendingDeletion bool `protobuf:"varint,9,opt,name=pending_deletion,json=pendingDeletion" json:"pending_deletion,omitempty"`
	// view_count is the number of views this picture has received.
	ViewCount int64 `protobuf:"varint,10,opt,name=view_count,json=viewCount" json:"view_count,omitempty"`
	// duration is present if the image is animated (GIF or WEBM).  Note that
	// GIFs duration is not well defined and is subject to reinterpretation.
	Duration *google_protobuf.Duration `protobuf:"bytes,11,opt,name=duration" json:"duration,omitempty"`
	// The estimated lower bound of the pic score
	ScoreLo float64 `protobuf:"fixed64,12,opt,name=score_lo,json=scoreLo" json:"score_lo,omitempty"`
	// The estimated upper bound of the pic score
	ScoreHi float64 `protobuf:"fixed64,13,opt,name=score_hi,json=scoreHi" json:"score_hi,omitempty"`
}

func (m *ApiPic) Reset()                    { *m = ApiPic{} }
func (m *ApiPic) String() string            { return proto.CompactTextString(m) }
func (*ApiPic) ProtoMessage()               {}
func (*ApiPic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiPic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApiPic) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ApiPic) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ApiPic) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ApiPic) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ApiPic) GetRelativeUrl() string {
	if m != nil {
		return m.RelativeUrl
	}
	return ""
}

func (m *ApiPic) GetThumbnailRelativeUrl() string {
	if m != nil {
		return m.ThumbnailRelativeUrl
	}
	return ""
}

func (m *ApiPic) GetPendingDeletion() bool {
	if m != nil {
		return m.PendingDeletion
	}
	return false
}

func (m *ApiPic) GetViewCount() int64 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *ApiPic) GetDuration() *google_protobuf.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *ApiPic) GetScoreLo() float64 {
	if m != nil {
		return m.ScoreLo
	}
	return 0
}

func (m *ApiPic) GetScoreHi() float64 {
	if m != nil {
		return m.ScoreHi
	}
	return 0
}

type ApiPicTag struct {
	// pic_id is the unique identifier for the pic, in varint form
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	// tag_id is the unique identifier for the tag, in varint form
	TagId string `protobuf:"bytes,2,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
	// name is the tag name in utf8 form
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// created_time is when the tag was created.
	CreatedTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// modified_time is when the tag was last modified.
	ModifiedTime *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=modified_time,json=modifiedTime" json:"modified_time,omitempty"`
	// version is the version of the tag.  It is used when updating the tag.
	Version int64 `protobuf:"fixed64,6,opt,name=version" json:"version,omitempty"`
}

func (m *ApiPicTag) Reset()                    { *m = ApiPicTag{} }
func (m *ApiPicTag) String() string            { return proto.CompactTextString(m) }
func (*ApiPicTag) ProtoMessage()               {}
func (*ApiPicTag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiPicTag) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

func (m *ApiPicTag) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

func (m *ApiPicTag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApiPicTag) GetCreatedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *ApiPicTag) GetModifiedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ModifiedTime
	}
	return nil
}

func (m *ApiPicTag) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ApiPicComment struct {
	// pic_id is the unique identifier for the pic, in varint form
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	// comment_id is the unique identifier for the comment, in varint form
	CommentId string `protobuf:"bytes,2,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
	// comment_parent_id is the unique identifier for the parent comment, in varint form
	CommentParentId string `protobuf:"bytes,3,opt,name=comment_parent_id,json=commentParentId" json:"comment_parent_id,omitempty"`
	Text            string `protobuf:"bytes,7,opt,name=text" json:"text,omitempty"`
	// created_time is when the tag was created.
	CreatedTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// modified_time is when the tag was last modified.
	ModifiedTime *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=modified_time,json=modifiedTime" json:"modified_time,omitempty"`
	// version is the version of the tag.  It is used when updating the tag.
	Version int64 `protobuf:"fixed64,6,opt,name=version" json:"version,omitempty"`
}

func (m *ApiPicComment) Reset()                    { *m = ApiPicComment{} }
func (m *ApiPicComment) String() string            { return proto.CompactTextString(m) }
func (*ApiPicComment) ProtoMessage()               {}
func (*ApiPicComment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiPicComment) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

func (m *ApiPicComment) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *ApiPicComment) GetCommentParentId() string {
	if m != nil {
		return m.CommentParentId
	}
	return ""
}

func (m *ApiPicComment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ApiPicComment) GetCreatedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *ApiPicComment) GetModifiedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ModifiedTime
	}
	return nil
}

func (m *ApiPicComment) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ApiUser struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Ident  string `protobuf:"bytes,2,opt,name=ident" json:"ident,omitempty"`
	// created_time is when the user was created.
	CreatedTime *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// modified_time is when the user was last modified.
	ModifiedTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=modified_time,json=modifiedTime" json:"modified_time,omitempty"`
	// modified_time is when the user was last modified.
	LastSeenTime *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=last_seen_time,json=lastSeenTime" json:"last_seen_time,omitempty"`
	// version is the version of the user.  It is used when updating the user.
	Version    int64               `protobuf:"fixed64,6,opt,name=version" json:"version,omitempty"`
	Capability []ApiCapability_Cap `protobuf:"varint,7,rep,packed,name=capability,enum=pixur.api.ApiCapability_Cap" json:"capability,omitempty"`
}

func (m *ApiUser) Reset()                    { *m = ApiUser{} }
func (m *ApiUser) String() string            { return proto.CompactTextString(m) }
func (*ApiUser) ProtoMessage()               {}
func (*ApiUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApiUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ApiUser) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *ApiUser) GetCreatedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *ApiUser) GetModifiedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ModifiedTime
	}
	return nil
}

func (m *ApiUser) GetLastSeenTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastSeenTime
	}
	return nil
}

func (m *ApiUser) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ApiUser) GetCapability() []ApiCapability_Cap {
	if m != nil {
		return m.Capability
	}
	return nil
}

type ApiCapability struct {
}

func (m *ApiCapability) Reset()                    { *m = ApiCapability{} }
func (m *ApiCapability) String() string            { return proto.CompactTextString(m) }
func (*ApiCapability) ProtoMessage()               {}
func (*ApiCapability) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type LookupUserRequest struct {
	// if absent, assumed to come from auth token
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LookupUserRequest) Reset()                    { *m = LookupUserRequest{} }
func (m *LookupUserRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupUserRequest) ProtoMessage()               {}
func (*LookupUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LookupUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LookupUserResponse struct {
	User *ApiUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *LookupUserResponse) Reset()                    { *m = LookupUserResponse{} }
func (m *LookupUserResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupUserResponse) ProtoMessage()               {}
func (*LookupUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LookupUserResponse) GetUser() *ApiUser {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	UserId     string                              `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Version    int64                               `protobuf:"fixed64,2,opt,name=version" json:"version,omitempty"`
	Ident      *UpdateUserRequest_ChangeIdent      `protobuf:"bytes,3,opt,name=ident" json:"ident,omitempty"`
	Secret     *UpdateUserRequest_ChangeSecret     `protobuf:"bytes,4,opt,name=secret" json:"secret,omitempty"`
	Capability *UpdateUserRequest_ChangeCapability `protobuf:"bytes,5,opt,name=capability" json:"capability,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserRequest) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UpdateUserRequest) GetIdent() *UpdateUserRequest_ChangeIdent {
	if m != nil {
		return m.Ident
	}
	return nil
}

func (m *UpdateUserRequest) GetSecret() *UpdateUserRequest_ChangeSecret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *UpdateUserRequest) GetCapability() *UpdateUserRequest_ChangeCapability {
	if m != nil {
		return m.Capability
	}
	return nil
}

type UpdateUserRequest_ChangeIdent struct {
	Ident string `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
}

func (m *UpdateUserRequest_ChangeIdent) Reset()         { *m = UpdateUserRequest_ChangeIdent{} }
func (m *UpdateUserRequest_ChangeIdent) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest_ChangeIdent) ProtoMessage()    {}
func (*UpdateUserRequest_ChangeIdent) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

func (m *UpdateUserRequest_ChangeIdent) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

type UpdateUserRequest_ChangeSecret struct {
	Secret string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
}

func (m *UpdateUserRequest_ChangeSecret) Reset()         { *m = UpdateUserRequest_ChangeSecret{} }
func (m *UpdateUserRequest_ChangeSecret) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest_ChangeSecret) ProtoMessage()    {}
func (*UpdateUserRequest_ChangeSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 1}
}

func (m *UpdateUserRequest_ChangeSecret) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type UpdateUserRequest_ChangeCapability struct {
	SetCapability   []ApiCapability_Cap `protobuf:"varint,1,rep,packed,name=set_capability,json=setCapability,enum=pixur.api.ApiCapability_Cap" json:"set_capability,omitempty"`
	ClearCapability []ApiCapability_Cap `protobuf:"varint,2,rep,packed,name=clear_capability,json=clearCapability,enum=pixur.api.ApiCapability_Cap" json:"clear_capability,omitempty"`
}

func (m *UpdateUserRequest_ChangeCapability) Reset()         { *m = UpdateUserRequest_ChangeCapability{} }
func (m *UpdateUserRequest_ChangeCapability) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest_ChangeCapability) ProtoMessage()    {}
func (*UpdateUserRequest_ChangeCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 2}
}

func (m *UpdateUserRequest_ChangeCapability) GetSetCapability() []ApiCapability_Cap {
	if m != nil {
		return m.SetCapability
	}
	return nil
}

func (m *UpdateUserRequest_ChangeCapability) GetClearCapability() []ApiCapability_Cap {
	if m != nil {
		return m.ClearCapability
	}
	return nil
}

type UpdateUserResponse struct {
	User *ApiUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateUserResponse) GetUser() *ApiUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ApiPicCommentTree struct {
	// All comments, ordered by a post order traversal.  Protobuf does not handle deeply nested
	// messages well.
	Comment []*ApiPicComment `protobuf:"bytes,1,rep,name=comment" json:"comment,omitempty"`
}

func (m *ApiPicCommentTree) Reset()                    { *m = ApiPicCommentTree{} }
func (m *ApiPicCommentTree) String() string            { return proto.CompactTextString(m) }
func (*ApiPicCommentTree) ProtoMessage()               {}
func (*ApiPicCommentTree) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApiPicCommentTree) GetComment() []*ApiPicComment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type LookupPicDetailsRequest struct {
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
}

func (m *LookupPicDetailsRequest) Reset()                    { *m = LookupPicDetailsRequest{} }
func (m *LookupPicDetailsRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupPicDetailsRequest) ProtoMessage()               {}
func (*LookupPicDetailsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LookupPicDetailsRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

type LookupPicDetailsResponse struct {
	Pic            *ApiPic            `protobuf:"bytes,1,opt,name=pic" json:"pic,omitempty"`
	PicTag         []*ApiPicTag       `protobuf:"bytes,2,rep,name=pic_tag,json=picTag" json:"pic_tag,omitempty"`
	PicCommentTree *ApiPicCommentTree `protobuf:"bytes,3,opt,name=pic_comment_tree,json=picCommentTree" json:"pic_comment_tree,omitempty"`
}

func (m *LookupPicDetailsResponse) Reset()                    { *m = LookupPicDetailsResponse{} }
func (m *LookupPicDetailsResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupPicDetailsResponse) ProtoMessage()               {}
func (*LookupPicDetailsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LookupPicDetailsResponse) GetPic() *ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

func (m *LookupPicDetailsResponse) GetPicTag() []*ApiPicTag {
	if m != nil {
		return m.PicTag
	}
	return nil
}

func (m *LookupPicDetailsResponse) GetPicCommentTree() *ApiPicCommentTree {
	if m != nil {
		return m.PicCommentTree
	}
	return nil
}

type FindIndexPicsRequest struct {
	StartPicId string `protobuf:"bytes,1,opt,name=start_pic_id,json=startPicId" json:"start_pic_id,omitempty"`
	Ascending  bool   `protobuf:"varint,2,opt,name=ascending" json:"ascending,omitempty"`
}

func (m *FindIndexPicsRequest) Reset()                    { *m = FindIndexPicsRequest{} }
func (m *FindIndexPicsRequest) String() string            { return proto.CompactTextString(m) }
func (*FindIndexPicsRequest) ProtoMessage()               {}
func (*FindIndexPicsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *FindIndexPicsRequest) GetStartPicId() string {
	if m != nil {
		return m.StartPicId
	}
	return ""
}

func (m *FindIndexPicsRequest) GetAscending() bool {
	if m != nil {
		return m.Ascending
	}
	return false
}

type FindIndexPicsResponse struct {
	Pic []*ApiPic `protobuf:"bytes,1,rep,name=pic" json:"pic,omitempty"`
}

func (m *FindIndexPicsResponse) Reset()                    { *m = FindIndexPicsResponse{} }
func (m *FindIndexPicsResponse) String() string            { return proto.CompactTextString(m) }
func (*FindIndexPicsResponse) ProtoMessage()               {}
func (*FindIndexPicsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *FindIndexPicsResponse) GetPic() []*ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

type AddPicTagsRequest struct {
	PicId string   `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	Tag   []string `protobuf:"bytes,2,rep,name=tag" json:"tag,omitempty"`
}

func (m *AddPicTagsRequest) Reset()                    { *m = AddPicTagsRequest{} }
func (m *AddPicTagsRequest) String() string            { return proto.CompactTextString(m) }
func (*AddPicTagsRequest) ProtoMessage()               {}
func (*AddPicTagsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AddPicTagsRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

func (m *AddPicTagsRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type AddPicTagsResponse struct {
}

func (m *AddPicTagsResponse) Reset()                    { *m = AddPicTagsResponse{} }
func (m *AddPicTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*AddPicTagsResponse) ProtoMessage()               {}
func (*AddPicTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type CreatePicRequest struct {
	// file_data is the contents of the pic.  Either file_data or file_url must be present.
	// If sent as part of a stream, this field will be the only one read after the first message.
	FileData []byte `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	// optional, only used if file_data is present.
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	// URL to get the pic from.  Either file_data or file_url must be present.
	FileUrl string   `protobuf:"bytes,3,opt,name=file_url,json=fileUrl" json:"file_url,omitempty"`
	Tag     []string `protobuf:"bytes,4,rep,name=tag" json:"tag,omitempty"`
}

func (m *CreatePicRequest) Reset()                    { *m = CreatePicRequest{} }
func (m *CreatePicRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePicRequest) ProtoMessage()               {}
func (*CreatePicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CreatePicRequest) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *CreatePicRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CreatePicRequest) GetFileUrl() string {
	if m != nil {
		return m.FileUrl
	}
	return ""
}

func (m *CreatePicRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type CreatePicResponse struct {
	Pic *ApiPic `protobuf:"bytes,1,opt,name=pic" json:"pic,omitempty"`
}

func (m *CreatePicResponse) Reset()                    { *m = CreatePicResponse{} }
func (m *CreatePicResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePicResponse) ProtoMessage()               {}
func (*CreatePicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreatePicResponse) GetPic() *ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

type FindSimilarPicsRequest struct {
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
}

func (m *FindSimilarPicsRequest) Reset()                    { *m = FindSimilarPicsRequest{} }
func (m *FindSimilarPicsRequest) String() string            { return proto.CompactTextString(m) }
func (*FindSimilarPicsRequest) ProtoMessage()               {}
func (*FindSimilarPicsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *FindSimilarPicsRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

type FindSimilarPicsResponse struct {
	PicId []string `protobuf:"bytes,1,rep,name=pic_id,json=picId" json:"pic_id,omitempty"`
}

func (m *FindSimilarPicsResponse) Reset()                    { *m = FindSimilarPicsResponse{} }
func (m *FindSimilarPicsResponse) String() string            { return proto.CompactTextString(m) }
func (*FindSimilarPicsResponse) ProtoMessage()               {}
func (*FindSimilarPicsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *FindSimilarPicsResponse) GetPicId() []string {
	if m != nil {
		return m.PicId
	}
	return nil
}

type IncrementViewCountRequest struct {
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
}

func (m *IncrementViewCountRequest) Reset()                    { *m = IncrementViewCountRequest{} }
func (m *IncrementViewCountRequest) String() string            { return proto.CompactTextString(m) }
func (*IncrementViewCountRequest) ProtoMessage()               {}
func (*IncrementViewCountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *IncrementViewCountRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

type IncrementViewCountResponse struct {
}

func (m *IncrementViewCountResponse) Reset()                    { *m = IncrementViewCountResponse{} }
func (m *IncrementViewCountResponse) String() string            { return proto.CompactTextString(m) }
func (*IncrementViewCountResponse) ProtoMessage()               {}
func (*IncrementViewCountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type PurgePicRequest struct {
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
}

func (m *PurgePicRequest) Reset()                    { *m = PurgePicRequest{} }
func (m *PurgePicRequest) String() string            { return proto.CompactTextString(m) }
func (*PurgePicRequest) ProtoMessage()               {}
func (*PurgePicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PurgePicRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

type PurgePicResponse struct {
}

func (m *PurgePicResponse) Reset()                    { *m = PurgePicResponse{} }
func (m *PurgePicResponse) String() string            { return proto.CompactTextString(m) }
func (*PurgePicResponse) ProtoMessage()               {}
func (*PurgePicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type SoftDeletePicRequest struct {
	PicId        string                      `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	Details      string                      `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
	Reason       DeletionReason              `protobuf:"varint,3,opt,name=reason,enum=pixur.api.DeletionReason" json:"reason,omitempty"`
	DeletionTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=deletion_time,json=deletionTime" json:"deletion_time,omitempty"`
}

func (m *SoftDeletePicRequest) Reset()                    { *m = SoftDeletePicRequest{} }
func (m *SoftDeletePicRequest) String() string            { return proto.CompactTextString(m) }
func (*SoftDeletePicRequest) ProtoMessage()               {}
func (*SoftDeletePicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *SoftDeletePicRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

func (m *SoftDeletePicRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *SoftDeletePicRequest) GetReason() DeletionReason {
	if m != nil {
		return m.Reason
	}
	return DeletionReason_UNKNOWN
}

func (m *SoftDeletePicRequest) GetDeletionTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.DeletionTime
	}
	return nil
}

type SoftDeletePicResponse struct {
}

func (m *SoftDeletePicResponse) Reset()                    { *m = SoftDeletePicResponse{} }
func (m *SoftDeletePicResponse) String() string            { return proto.CompactTextString(m) }
func (*SoftDeletePicResponse) ProtoMessage()               {}
func (*SoftDeletePicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type UpsertPicRequest struct {
	Url     string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data    []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Md5Hash []byte   `protobuf:"bytes,4,opt,name=md5_hash,json=md5Hash,proto3" json:"md5_hash,omitempty"`
	Tag     []string `protobuf:"bytes,5,rep,name=tag" json:"tag,omitempty"`
}

func (m *UpsertPicRequest) Reset()                    { *m = UpsertPicRequest{} }
func (m *UpsertPicRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertPicRequest) ProtoMessage()               {}
func (*UpsertPicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *UpsertPicRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UpsertPicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpsertPicRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpsertPicRequest) GetMd5Hash() []byte {
	if m != nil {
		return m.Md5Hash
	}
	return nil
}

func (m *UpsertPicRequest) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type UpsertPicResponse struct {
	Pic *ApiPic `protobuf:"bytes,1,opt,name=pic" json:"pic,omitempty"`
}

func (m *UpsertPicResponse) Reset()                    { *m = UpsertPicResponse{} }
func (m *UpsertPicResponse) String() string            { return proto.CompactTextString(m) }
func (*UpsertPicResponse) ProtoMessage()               {}
func (*UpsertPicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UpsertPicResponse) GetPic() *ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

type GetXsrfTokenRequest struct {
}

func (m *GetXsrfTokenRequest) Reset()                    { *m = GetXsrfTokenRequest{} }
func (m *GetXsrfTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*GetXsrfTokenRequest) ProtoMessage()               {}
func (*GetXsrfTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type GetXsrfTokenResponse struct {
	XsrfToken string `protobuf:"bytes,1,opt,name=xsrf_token,json=xsrfToken" json:"xsrf_token,omitempty"`
}

func (m *GetXsrfTokenResponse) Reset()                    { *m = GetXsrfTokenResponse{} }
func (m *GetXsrfTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*GetXsrfTokenResponse) ProtoMessage()               {}
func (*GetXsrfTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GetXsrfTokenResponse) GetXsrfToken() string {
	if m != nil {
		return m.XsrfToken
	}
	return ""
}

type CreateUserRequest struct {
	// ident is the unique identity of the user being created, usually an email address
	Ident string `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
	// secret is the secret string used to authenticate the user, usually a password
	Secret string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *CreateUserRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *CreateUserRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type CreateUserResponse struct {
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type GetRefreshTokenRequest struct {
	// ident is the unique identity of the user being created, usually an email address
	Ident string `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
	// secret is the secret string used to authenticate the user, usually a password
	Secret       string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *GetRefreshTokenRequest) Reset()                    { *m = GetRefreshTokenRequest{} }
func (m *GetRefreshTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRefreshTokenRequest) ProtoMessage()               {}
func (*GetRefreshTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *GetRefreshTokenRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *GetRefreshTokenRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GetRefreshTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type GetRefreshTokenResponse struct {
	RefreshToken   string      `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	AuthToken      string      `protobuf:"bytes,2,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
	PixToken       string      `protobuf:"bytes,5,opt,name=pix_token,json=pixToken" json:"pix_token,omitempty"`
	RefreshPayload *PwtPayload `protobuf:"bytes,3,opt,name=refresh_payload,json=refreshPayload" json:"refresh_payload,omitempty"`
	AuthPayload    *PwtPayload `protobuf:"bytes,4,opt,name=auth_payload,json=authPayload" json:"auth_payload,omitempty"`
	PixPayload     *PwtPayload `protobuf:"bytes,6,opt,name=pix_payload,json=pixPayload" json:"pix_payload,omitempty"`
}

func (m *GetRefreshTokenResponse) Reset()                    { *m = GetRefreshTokenResponse{} }
func (m *GetRefreshTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRefreshTokenResponse) ProtoMessage()               {}
func (*GetRefreshTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *GetRefreshTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetRefreshTokenResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *GetRefreshTokenResponse) GetPixToken() string {
	if m != nil {
		return m.PixToken
	}
	return ""
}

func (m *GetRefreshTokenResponse) GetRefreshPayload() *PwtPayload {
	if m != nil {
		return m.RefreshPayload
	}
	return nil
}

func (m *GetRefreshTokenResponse) GetAuthPayload() *PwtPayload {
	if m != nil {
		return m.AuthPayload
	}
	return nil
}

func (m *GetRefreshTokenResponse) GetPixPayload() *PwtPayload {
	if m != nil {
		return m.PixPayload
	}
	return nil
}

type PwtHeader struct {
	Algorithm PwtHeader_Algorithm `protobuf:"varint,1,opt,name=algorithm,enum=pixur.api.PwtHeader_Algorithm" json:"algorithm,omitempty"`
	Version   int64               `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *PwtHeader) Reset()                    { *m = PwtHeader{} }
func (m *PwtHeader) String() string            { return proto.CompactTextString(m) }
func (*PwtHeader) ProtoMessage()               {}
func (*PwtHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PwtHeader) GetAlgorithm() PwtHeader_Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return PwtHeader_UNKNOWN
}

func (m *PwtHeader) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type PwtPayload struct {
	Subject   string                      `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	NotBefore *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=not_before,json=notBefore" json:"not_before,omitempty"`
	NotAfter  *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=not_after,json=notAfter" json:"not_after,omitempty"`
	// represents when this token should be reverified.  Optional.
	SoftNotAfter  *google_protobuf1.Timestamp `protobuf:"bytes,6,opt,name=soft_not_after,json=softNotAfter" json:"soft_not_after,omitempty"`
	Issuer        string                      `protobuf:"bytes,4,opt,name=issuer" json:"issuer,omitempty"`
	TokenId       int64                       `protobuf:"varint,5,opt,name=token_id,json=tokenId" json:"token_id,omitempty"`
	TokenParentId int64                       `protobuf:"varint,8,opt,name=token_parent_id,json=tokenParentId" json:"token_parent_id,omitempty"`
	Type          PwtPayload_Type             `protobuf:"varint,7,opt,name=type,enum=pixur.api.PwtPayload_Type" json:"type,omitempty"`
}

func (m *PwtPayload) Reset()                    { *m = PwtPayload{} }
func (m *PwtPayload) String() string            { return proto.CompactTextString(m) }
func (*PwtPayload) ProtoMessage()               {}
func (*PwtPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PwtPayload) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *PwtPayload) GetNotBefore() *google_protobuf1.Timestamp {
	if m != nil {
		return m.NotBefore
	}
	return nil
}

func (m *PwtPayload) GetNotAfter() *google_protobuf1.Timestamp {
	if m != nil {
		return m.NotAfter
	}
	return nil
}

func (m *PwtPayload) GetSoftNotAfter() *google_protobuf1.Timestamp {
	if m != nil {
		return m.SoftNotAfter
	}
	return nil
}

func (m *PwtPayload) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *PwtPayload) GetTokenId() int64 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

func (m *PwtPayload) GetTokenParentId() int64 {
	if m != nil {
		return m.TokenParentId
	}
	return 0
}

func (m *PwtPayload) GetType() PwtPayload_Type {
	if m != nil {
		return m.Type
	}
	return PwtPayload_UNKNOWN
}

type AddPicCommentRequest struct {
	PicId           string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	CommentParentId string `protobuf:"bytes,2,opt,name=comment_parent_id,json=commentParentId" json:"comment_parent_id,omitempty"`
	Text            string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
}

func (m *AddPicCommentRequest) Reset()                    { *m = AddPicCommentRequest{} }
func (m *AddPicCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*AddPicCommentRequest) ProtoMessage()               {}
func (*AddPicCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *AddPicCommentRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

func (m *AddPicCommentRequest) GetCommentParentId() string {
	if m != nil {
		return m.CommentParentId
	}
	return ""
}

func (m *AddPicCommentRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type AddPicCommentResponse struct {
	Comment *ApiPicComment `protobuf:"bytes,1,opt,name=comment" json:"comment,omitempty"`
}

func (m *AddPicCommentResponse) Reset()                    { *m = AddPicCommentResponse{} }
func (m *AddPicCommentResponse) String() string            { return proto.CompactTextString(m) }
func (*AddPicCommentResponse) ProtoMessage()               {}
func (*AddPicCommentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *AddPicCommentResponse) GetComment() *ApiPicComment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type DeleteTokenRequest struct {
}

func (m *DeleteTokenRequest) Reset()                    { *m = DeleteTokenRequest{} }
func (m *DeleteTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTokenRequest) ProtoMessage()               {}
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type DeleteTokenResponse struct {
}

func (m *DeleteTokenResponse) Reset()                    { *m = DeleteTokenResponse{} }
func (m *DeleteTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteTokenResponse) ProtoMessage()               {}
func (*DeleteTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

type UpsertPicVoteRequest struct {
	PicId string                    `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	Vote  UpsertPicVoteRequest_Vote `protobuf:"varint,2,opt,name=vote,enum=pixur.api.UpsertPicVoteRequest_Vote" json:"vote,omitempty"`
}

func (m *UpsertPicVoteRequest) Reset()                    { *m = UpsertPicVoteRequest{} }
func (m *UpsertPicVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertPicVoteRequest) ProtoMessage()               {}
func (*UpsertPicVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *UpsertPicVoteRequest) GetPicId() string {
	if m != nil {
		return m.PicId
	}
	return ""
}

func (m *UpsertPicVoteRequest) GetVote() UpsertPicVoteRequest_Vote {
	if m != nil {
		return m.Vote
	}
	return UpsertPicVoteRequest_UNKNOWN
}

type UpsertPicVoteResponse struct {
}

func (m *UpsertPicVoteResponse) Reset()                    { *m = UpsertPicVoteResponse{} }
func (m *UpsertPicVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*UpsertPicVoteResponse) ProtoMessage()               {}
func (*UpsertPicVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func init() {
	proto.RegisterType((*ApiPic)(nil), "pixur.api.ApiPic")
	proto.RegisterType((*ApiPicTag)(nil), "pixur.api.ApiPicTag")
	proto.RegisterType((*ApiPicComment)(nil), "pixur.api.ApiPicComment")
	proto.RegisterType((*ApiUser)(nil), "pixur.api.ApiUser")
	proto.RegisterType((*ApiCapability)(nil), "pixur.api.ApiCapability")
	proto.RegisterType((*LookupUserRequest)(nil), "pixur.api.LookupUserRequest")
	proto.RegisterType((*LookupUserResponse)(nil), "pixur.api.LookupUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "pixur.api.UpdateUserRequest")
	proto.RegisterType((*UpdateUserRequest_ChangeIdent)(nil), "pixur.api.UpdateUserRequest.ChangeIdent")
	proto.RegisterType((*UpdateUserRequest_ChangeSecret)(nil), "pixur.api.UpdateUserRequest.ChangeSecret")
	proto.RegisterType((*UpdateUserRequest_ChangeCapability)(nil), "pixur.api.UpdateUserRequest.ChangeCapability")
	proto.RegisterType((*UpdateUserResponse)(nil), "pixur.api.UpdateUserResponse")
	proto.RegisterType((*ApiPicCommentTree)(nil), "pixur.api.ApiPicCommentTree")
	proto.RegisterType((*LookupPicDetailsRequest)(nil), "pixur.api.LookupPicDetailsRequest")
	proto.RegisterType((*LookupPicDetailsResponse)(nil), "pixur.api.LookupPicDetailsResponse")
	proto.RegisterType((*FindIndexPicsRequest)(nil), "pixur.api.FindIndexPicsRequest")
	proto.RegisterType((*FindIndexPicsResponse)(nil), "pixur.api.FindIndexPicsResponse")
	proto.RegisterType((*AddPicTagsRequest)(nil), "pixur.api.AddPicTagsRequest")
	proto.RegisterType((*AddPicTagsResponse)(nil), "pixur.api.AddPicTagsResponse")
	proto.RegisterType((*CreatePicRequest)(nil), "pixur.api.CreatePicRequest")
	proto.RegisterType((*CreatePicResponse)(nil), "pixur.api.CreatePicResponse")
	proto.RegisterType((*FindSimilarPicsRequest)(nil), "pixur.api.FindSimilarPicsRequest")
	proto.RegisterType((*FindSimilarPicsResponse)(nil), "pixur.api.FindSimilarPicsResponse")
	proto.RegisterType((*IncrementViewCountRequest)(nil), "pixur.api.IncrementViewCountRequest")
	proto.RegisterType((*IncrementViewCountResponse)(nil), "pixur.api.IncrementViewCountResponse")
	proto.RegisterType((*PurgePicRequest)(nil), "pixur.api.PurgePicRequest")
	proto.RegisterType((*PurgePicResponse)(nil), "pixur.api.PurgePicResponse")
	proto.RegisterType((*SoftDeletePicRequest)(nil), "pixur.api.SoftDeletePicRequest")
	proto.RegisterType((*SoftDeletePicResponse)(nil), "pixur.api.SoftDeletePicResponse")
	proto.RegisterType((*UpsertPicRequest)(nil), "pixur.api.UpsertPicRequest")
	proto.RegisterType((*UpsertPicResponse)(nil), "pixur.api.UpsertPicResponse")
	proto.RegisterType((*GetXsrfTokenRequest)(nil), "pixur.api.GetXsrfTokenRequest")
	proto.RegisterType((*GetXsrfTokenResponse)(nil), "pixur.api.GetXsrfTokenResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "pixur.api.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "pixur.api.CreateUserResponse")
	proto.RegisterType((*GetRefreshTokenRequest)(nil), "pixur.api.GetRefreshTokenRequest")
	proto.RegisterType((*GetRefreshTokenResponse)(nil), "pixur.api.GetRefreshTokenResponse")
	proto.RegisterType((*PwtHeader)(nil), "pixur.api.PwtHeader")
	proto.RegisterType((*PwtPayload)(nil), "pixur.api.PwtPayload")
	proto.RegisterType((*AddPicCommentRequest)(nil), "pixur.api.AddPicCommentRequest")
	proto.RegisterType((*AddPicCommentResponse)(nil), "pixur.api.AddPicCommentResponse")
	proto.RegisterType((*DeleteTokenRequest)(nil), "pixur.api.DeleteTokenRequest")
	proto.RegisterType((*DeleteTokenResponse)(nil), "pixur.api.DeleteTokenResponse")
	proto.RegisterType((*UpsertPicVoteRequest)(nil), "pixur.api.UpsertPicVoteRequest")
	proto.RegisterType((*UpsertPicVoteResponse)(nil), "pixur.api.UpsertPicVoteResponse")
	proto.RegisterEnum("pixur.api.DeletionReason", DeletionReason_name, DeletionReason_value)
	proto.RegisterEnum("pixur.api.ApiCapability_Cap", ApiCapability_Cap_name, ApiCapability_Cap_value)
	proto.RegisterEnum("pixur.api.PwtHeader_Algorithm", PwtHeader_Algorithm_name, PwtHeader_Algorithm_value)
	proto.RegisterEnum("pixur.api.PwtPayload_Type", PwtPayload_Type_name, PwtPayload_Type_value)
	proto.RegisterEnum("pixur.api.UpsertPicVoteRequest_Vote", UpsertPicVoteRequest_Vote_name, UpsertPicVoteRequest_Vote_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x93, 0xdb, 0x48,
	0x15, 0x47, 0xb6, 0xc7, 0xb6, 0x9e, 0x3d, 0x1e, 0x4d, 0x67, 0xfe, 0x38, 0xce, 0x24, 0xeb, 0x55,
	0x20, 0xe5, 0xdd, 0x62, 0x9d, 0xc5, 0x4b, 0x96, 0x50, 0x0c, 0x0b, 0x8e, 0xc7, 0x99, 0x31, 0x3b,
	0xf1, 0xb8, 0x34, 0x76, 0x36, 0xc0, 0xc1, 0xa5, 0xb1, 0x7a, 0x6c, 0x11, 0x5b, 0x12, 0x52, 0x3b,
	0x99, 0x9c, 0xb9, 0x50, 0x5c, 0x29, 0x4e, 0x50, 0x05, 0x1f, 0x80, 0x33, 0x17, 0xbe, 0x05, 0x27,
	0xbe, 0x01, 0xdf, 0x80, 0x33, 0xd5, 0xad, 0x6e, 0x4b, 0x6d, 0xcb, 0xf3, 0xa7, 0xb8, 0xec, 0x4d,
	0xfd, 0xfe, 0xf5, 0xeb, 0xf7, 0x7e, 0xfd, 0xfa, 0x3d, 0x81, 0x6a, 0x7a, 0x76, 0xdd, 0xf3, 0x5d,
	0xe2, 0x22, 0xd5, 0xb3, 0xaf, 0xe6, 0x7e, 0xdd, 0xf4, 0xec, 0xca, 0xa3, 0xb1, 0xeb, 0x8e, 0xa7,
	0xf8, 0x29, 0x63, 0x5c, 0xcc, 0x2f, 0x9f, 0x5a, 0x73, 0xdf, 0x24, 0xb6, 0xeb, 0x84, 0xa2, 0x95,
	0x8f, 0x96, 0xf9, 0xc4, 0x9e, 0xe1, 0x80, 0x98, 0x33, 0x2f, 0x14, 0xd0, 0xff, 0x90, 0x86, 0x6c,
	0xd3, 0xb3, 0x7b, 0xf6, 0x08, 0x95, 0x20, 0x65, 0x5b, 0x65, 0xa5, 0xaa, 0xd4, 0x54, 0x23, 0x65,
	0x5b, 0x68, 0x07, 0x36, 0xde, 0xdb, 0x16, 0x99, 0x94, 0x53, 0x55, 0xa5, 0xb6, 0x61, 0x84, 0x0b,
	0xb4, 0x07, 0xd9, 0x09, 0xb6, 0xc7, 0x13, 0x52, 0x4e, 0x33, 0x32, 0x5f, 0xa1, 0x32, 0xe4, 0xde,
	0x61, 0x3f, 0xb0, 0x5d, 0xa7, 0x9c, 0xa9, 0x2a, 0x35, 0xcd, 0x10, 0x4b, 0x84, 0x20, 0x43, 0x3e,
	0x78, 0xb8, 0xbc, 0xc1, 0x2c, 0xb3, 0x6f, 0xf4, 0x31, 0x14, 0x7d, 0x3c, 0x35, 0x89, 0xfd, 0x0e,
	0x0f, 0xe7, 0xfe, 0xb4, 0x9c, 0x65, 0xbc, 0x82, 0xa0, 0x0d, 0xfc, 0x29, 0xfa, 0x21, 0xec, 0x91,
	0xc9, 0x7c, 0x76, 0xe1, 0x98, 0xf6, 0x74, 0x28, 0x09, 0xe7, 0x98, 0xf0, 0xce, 0x82, 0x6b, 0xc4,
	0xb4, 0x3e, 0x01, 0xcd, 0xc3, 0x8e, 0x65, 0x3b, 0xe3, 0xa1, 0x85, 0xa7, 0x98, 0x86, 0xa2, 0xac,
	0x56, 0x95, 0x5a, 0xde, 0xd8, 0xe2, 0xf4, 0x23, 0x4e, 0x46, 0x0f, 0x01, 0xde, 0xd9, 0xf8, 0xfd,
	0x70, 0xe4, 0xce, 0x1d, 0x52, 0x86, 0xaa, 0x52, 0x4b, 0x1b, 0x2a, 0xa5, 0xb4, 0x28, 0x01, 0x3d,
	0x83, 0xbc, 0x08, 0x66, 0xb9, 0x50, 0x55, 0x6a, 0x85, 0xc6, 0xfd, 0x7a, 0x18, 0xcd, 0xba, 0x88,
	0x66, 0xfd, 0x88, 0x0b, 0x18, 0x0b, 0x51, 0x74, 0x1f, 0xf2, 0xc1, 0xc8, 0xf5, 0xf1, 0x70, 0xea,
	0x96, 0x8b, 0x55, 0xa5, 0xa6, 0x18, 0x39, 0xb6, 0x3e, 0x75, 0x23, 0xd6, 0xc4, 0x2e, 0x6f, 0xc6,
	0x58, 0x27, 0xf6, 0x2f, 0x32, 0xf9, 0xbc, 0xa6, 0xea, 0xff, 0x51, 0x40, 0x0d, 0x93, 0xd1, 0x37,
	0xc7, 0x68, 0x17, 0xb2, 0x9e, 0x3d, 0x1a, 0x2e, 0x72, 0xb2, 0xe1, 0xd9, 0xa3, 0x8e, 0x45, 0xc9,
	0xc4, 0x1c, 0x53, 0x72, 0x2a, 0x24, 0x13, 0x73, 0xdc, 0xb1, 0x68, 0x94, 0x1d, 0x73, 0x86, 0x59,
	0x56, 0x54, 0x83, 0x7d, 0xa3, 0x9f, 0x42, 0x71, 0xe4, 0x63, 0x93, 0x60, 0x6b, 0x48, 0xf3, 0xce,
	0x12, 0x53, 0x68, 0x54, 0x56, 0x8e, 0xd1, 0x17, 0xa0, 0x30, 0x0a, 0x5c, 0x9e, 0x52, 0xd0, 0xcf,
	0x60, 0x73, 0xe6, 0x5a, 0xf6, 0xa5, 0x2d, 0xf4, 0x37, 0x6e, 0xd4, 0x2f, 0x0a, 0x05, 0x66, 0x20,
	0x86, 0x89, 0xac, 0x84, 0x09, 0xfd, 0xaf, 0x29, 0xd8, 0x0c, 0x4f, 0xda, 0x72, 0x67, 0x33, 0xec,
	0x90, 0x75, 0xa7, 0x7d, 0x08, 0x30, 0x0a, 0x25, 0xa2, 0x13, 0xab, 0x9c, 0xd2, 0xb1, 0xd0, 0xa7,
	0xb0, 0x2d, 0xd8, 0x9e, 0xe9, 0x73, 0xa9, 0x30, 0x04, 0x5b, 0x9c, 0xd1, 0x63, 0xf4, 0x30, 0x42,
	0x04, 0x5f, 0x11, 0x0e, 0x1f, 0xf6, 0xfd, 0x2d, 0x8e, 0xd0, 0xbf, 0x52, 0x90, 0x6b, 0x7a, 0xf6,
	0x20, 0xc0, 0x3e, 0xda, 0x87, 0xdc, 0x3c, 0xc0, 0x7e, 0x14, 0x9c, 0x2c, 0x5d, 0x76, 0xd8, 0x15,
	0xb5, 0x2d, 0xec, 0x10, 0x01, 0x05, 0xb6, 0x58, 0x39, 0x54, 0xfa, 0xff, 0x3c, 0x54, 0xe6, 0x8e,
	0x87, 0xfa, 0x39, 0x94, 0xa6, 0x66, 0x40, 0x86, 0x01, 0xc6, 0xce, 0xad, 0xc3, 0x42, 0x35, 0xce,
	0x31, 0x76, 0xae, 0x0f, 0x0b, 0x3a, 0x04, 0x18, 0x99, 0x9e, 0x79, 0x61, 0x4f, 0x6d, 0xf2, 0xa1,
	0x9c, 0xab, 0xa6, 0x6b, 0xa5, 0xc6, 0x41, 0x7d, 0x51, 0x10, 0xeb, 0x4d, 0xcf, 0x6e, 0x2d, 0xf8,
	0xf5, 0x96, 0xe9, 0x19, 0x31, 0x79, 0xfd, 0x4f, 0x21, 0xec, 0x22, 0x09, 0xfd, 0x77, 0x29, 0x48,
	0xb7, 0x4c, 0x0f, 0x15, 0x20, 0x37, 0xe8, 0x7e, 0xdd, 0x3d, 0xfb, 0xa6, 0xab, 0x7d, 0x07, 0x95,
	0x00, 0x7a, 0x9d, 0xd6, 0xb0, 0x65, 0xb4, 0x9b, 0xfd, 0xb6, 0xa6, 0xa0, 0x22, 0xe4, 0xe9, 0xda,
	0x68, 0x37, 0x8f, 0xb4, 0x14, 0xda, 0x04, 0x95, 0xae, 0x3a, 0xdd, 0xa3, 0xf6, 0x1b, 0x2d, 0x8d,
	0xee, 0xc1, 0x16, 0x5d, 0x9e, 0x9f, 0xbd, 0xec, 0x0f, 0x8f, 0xda, 0xa7, 0xed, 0x7e, 0x5b, 0xdb,
	0x10, 0xc4, 0x93, 0xa6, 0x71, 0x24, 0x88, 0x59, 0xa1, 0xd8, 0x1b, 0x18, 0xc7, 0x6d, 0x2d, 0x87,
	0x1e, 0xc0, 0x3e, 0x5d, 0x0e, 0x7a, 0x47, 0xcd, 0x7e, 0x7b, 0xf8, 0xba, 0xd3, 0xfe, 0x66, 0xd8,
	0x3a, 0x1b, 0x74, 0xfb, 0x6d, 0x43, 0xcb, 0x23, 0x04, 0x25, 0xca, 0xec, 0x37, 0x8f, 0x85, 0x1b,
	0x2a, 0xda, 0x03, 0xc4, 0xdc, 0x3a, 0x7b, 0xf5, 0xaa, 0xdd, 0xed, 0x0b, 0x3a, 0x88, 0xcd, 0x5e,
	0x9f, 0xf5, 0xdb, 0x82, 0x58, 0x40, 0x5b, 0x50, 0x18, 0x9c, 0xb7, 0x0d, 0x41, 0xc8, 0xa0, 0x0a,
	0xec, 0x31, 0x02, 0xdf, 0xaf, 0xd5, 0xec, 0x35, 0x5f, 0x74, 0x4e, 0x3b, 0xfd, 0x5f, 0x6a, 0x45,
	0xfd, 0xfb, 0xb0, 0x7d, 0xea, 0xba, 0x6f, 0xe7, 0x1e, 0x85, 0x9b, 0x81, 0x7f, 0x3b, 0xc7, 0x01,
	0x59, 0x8b, 0x3a, 0xfd, 0x10, 0x50, 0x5c, 0x3a, 0xf0, 0x5c, 0x27, 0xc0, 0xe8, 0x09, 0x64, 0x28,
	0x9f, 0xc9, 0x16, 0x1a, 0x48, 0xce, 0x09, 0x93, 0x64, 0x7c, 0xfd, 0xf7, 0x19, 0xd8, 0x1e, 0x78,
	0x96, 0x49, 0xf0, 0x6d, 0x36, 0x8b, 0x43, 0x21, 0x25, 0x43, 0xe1, 0x2b, 0x01, 0xfe, 0x10, 0xdf,
	0xb5, 0xd8, 0x8e, 0x2b, 0xf6, 0xeb, 0xad, 0x89, 0xe9, 0x8c, 0x71, 0x87, 0xca, 0x8b, 0x6b, 0xd2,
	0x84, 0x6c, 0x80, 0x47, 0x3e, 0x26, 0x1c, 0xe0, 0x9f, 0xdc, 0xc2, 0xc0, 0x39, 0x53, 0x30, 0xb8,
	0x22, 0x7a, 0x25, 0xa1, 0x31, 0x44, 0xf9, 0x67, 0xb7, 0x30, 0x13, 0x01, 0x30, 0x0e, 0xcf, 0xca,
	0x63, 0x28, 0xc4, 0xfc, 0x8c, 0x6e, 0xb7, 0x12, 0xbb, 0xdd, 0x95, 0x27, 0x50, 0x8c, 0xfb, 0x42,
	0x1f, 0x64, 0x7e, 0x0c, 0x1e, 0xb8, 0x70, 0x55, 0xf9, 0x9b, 0x02, 0xda, 0xf2, 0x6e, 0xa8, 0x05,
	0xa5, 0x00, 0x93, 0x61, 0xcc, 0x69, 0xe5, 0x16, 0x57, 0x68, 0x33, 0xc0, 0x24, 0x66, 0xe4, 0x18,
	0xb4, 0xd1, 0x14, 0x9b, 0x7e, 0xdc, 0x4c, 0xea, 0x16, 0x66, 0xb6, 0x98, 0x56, 0xec, 0xf2, 0x1d,
	0x02, 0x8a, 0x47, 0xe8, 0x8e, 0x40, 0x3a, 0x86, 0x6d, 0xe9, 0x09, 0xe9, 0xfb, 0x18, 0xa3, 0x06,
	0xe4, 0x78, 0xdd, 0x67, 0x27, 0x2b, 0x34, 0xca, 0xb2, 0x7e, 0x24, 0x6e, 0x08, 0x41, 0xfd, 0x73,
	0xd8, 0x0f, 0xf1, 0xdc, 0xb3, 0x47, 0x47, 0x98, 0x98, 0xf6, 0x34, 0x10, 0xb0, 0x4c, 0x7e, 0x95,
	0xf4, 0x7f, 0x28, 0x50, 0x5e, 0x55, 0xe1, 0xfe, 0x3f, 0x86, 0xb4, 0x67, 0x8f, 0xb8, 0xfb, 0xdb,
	0x2b, 0xdb, 0x1b, 0x94, 0x8b, 0x3e, 0x83, 0x1c, 0x35, 0x4c, 0xcc, 0x31, 0x0b, 0x5d, 0xa1, 0xb1,
	0xb3, 0x22, 0xd8, 0x37, 0xc7, 0x06, 0xdd, 0x9d, 0xf6, 0x02, 0x2f, 0x41, 0xa3, 0xe2, 0xe2, 0xad,
	0x23, 0x3e, 0x16, 0x65, 0xfd, 0x60, 0xdd, 0xf9, 0x68, 0x38, 0x8c, 0x92, 0x27, 0xad, 0xf5, 0xd7,
	0xb0, 0xf3, 0xd2, 0x76, 0xac, 0x8e, 0x63, 0xe1, 0xab, 0x9e, 0x3d, 0x5a, 0x9c, 0xb3, 0x0a, 0xc5,
	0x80, 0x98, 0x3e, 0x19, 0x4a, 0xa7, 0x05, 0x46, 0xeb, 0xb1, 0x87, 0xf8, 0x00, 0x54, 0x33, 0x18,
	0x85, 0x2d, 0x14, 0xbb, 0x89, 0x79, 0x23, 0x22, 0xe8, 0x87, 0xb0, 0xbb, 0x64, 0x77, 0x39, 0x18,
	0xe9, 0xf5, 0xc1, 0xd0, 0x0f, 0x61, 0xbb, 0x69, 0x59, 0xe1, 0x91, 0x6f, 0x08, 0x3d, 0xd2, 0x20,
	0x2d, 0x82, 0xa6, 0x1a, 0xf4, 0x53, 0xdf, 0x01, 0x14, 0xd7, 0x0e, 0x37, 0xd6, 0x3f, 0x80, 0xd6,
	0x62, 0x8f, 0x1a, 0xdd, 0x85, 0x9b, 0x7c, 0x00, 0xea, 0xa5, 0x3d, 0xc5, 0x43, 0xcb, 0x24, 0x26,
	0xb3, 0x5a, 0x34, 0xf2, 0x94, 0x70, 0x64, 0x12, 0x73, 0xc1, 0x64, 0x5d, 0x54, 0xf8, 0x9e, 0x32,
	0x66, 0x97, 0x76, 0x52, 0xf7, 0x81, 0x7d, 0xb3, 0xf6, 0x33, 0x6c, 0x2f, 0x72, 0x74, 0x4d, 0x3b,
	0x4e, 0xee, 0x50, 0x26, 0x72, 0xe8, 0x39, 0x6c, 0xc7, 0xb6, 0xbe, 0x03, 0x2a, 0xf4, 0xa7, 0xb0,
	0x47, 0xc3, 0x78, 0x6e, 0xcf, 0xec, 0xa9, 0xe9, 0xc7, 0x13, 0xb4, 0x06, 0x88, 0x9f, 0xc3, 0xfe,
	0x8a, 0x02, 0xdf, 0x30, 0xae, 0x91, 0x8e, 0x34, 0x1a, 0x70, 0xbf, 0xe3, 0x8c, 0x7c, 0x4c, 0x21,
	0xf1, 0x5a, 0x34, 0xbb, 0x37, 0xec, 0x72, 0x00, 0x95, 0x24, 0x1d, 0x1e, 0xe9, 0x1a, 0x6c, 0xf5,
	0xe6, 0xfe, 0x38, 0x1e, 0xe8, 0x35, 0x76, 0x10, 0x68, 0x91, 0x24, 0xd7, 0xfe, 0xa7, 0x02, 0x3b,
	0xe7, 0xee, 0x25, 0x61, 0x6d, 0xf9, 0xcd, 0x36, 0xe8, 0x7b, 0x60, 0x85, 0x17, 0x8e, 0x27, 0x49,
	0x2c, 0xd1, 0x0f, 0x20, 0xeb, 0x63, 0x33, 0x70, 0x1d, 0x96, 0xa1, 0x52, 0xe3, 0x7e, 0x2c, 0xc8,
	0xa2, 0xe9, 0x37, 0x98, 0x80, 0xc1, 0x05, 0x69, 0xab, 0x23, 0xa6, 0x84, 0x5b, 0xb7, 0x3a, 0x42,
	0x81, 0x92, 0xf4, 0x7d, 0xd8, 0x5d, 0x72, 0x3e, 0x82, 0xdf, 0xc0, 0x0b, 0x30, 0xbb, 0x3d, 0xe2,
	0x44, 0x1a, 0xa4, 0x29, 0x7e, 0xc2, 0xe3, 0xd0, 0xcf, 0x45, 0xd3, 0x9e, 0x8a, 0x35, 0xed, 0x08,
	0x32, 0x0c, 0x9f, 0x69, 0x86, 0x4f, 0xf6, 0x4d, 0xe1, 0x37, 0xb3, 0x9e, 0x0d, 0x27, 0x66, 0x30,
	0x61, 0x2e, 0x16, 0x8d, 0xdc, 0xcc, 0x7a, 0x76, 0x62, 0x06, 0x13, 0x01, 0xbf, 0x0d, 0x09, 0x7e,
	0xb1, 0xad, 0xef, 0x02, 0xbf, 0x5d, 0xb8, 0x77, 0x8c, 0xc9, 0x9b, 0xc0, 0xbf, 0xec, 0xbb, 0x6f,
	0xb1, 0xc3, 0xfd, 0xd6, 0x9f, 0xc1, 0x8e, 0x4c, 0xe6, 0x36, 0x1f, 0x02, 0x5c, 0x05, 0xfe, 0xe5,
	0x90, 0x50, 0x2a, 0x3f, 0x96, 0x7a, 0x25, 0xc4, 0xf4, 0xa6, 0xb8, 0x06, 0xf1, 0x77, 0x3e, 0xf1,
	0x4d, 0x8b, 0xbd, 0x61, 0xa9, 0xf8, 0x1b, 0x46, 0xaf, 0x76, 0xdc, 0x04, 0x8f, 0xed, 0x5b, 0xd8,
	0x3b, 0xc6, 0xc4, 0xc0, 0x97, 0x3e, 0x0e, 0x26, 0x71, 0x4f, 0xef, 0x66, 0x1d, 0x3d, 0x86, 0x4d,
	0x3f, 0x34, 0xc2, 0x8f, 0x10, 0xde, 0xec, 0xa2, 0x1f, 0xb3, 0xac, 0xff, 0x3d, 0x05, 0xfb, 0x2b,
	0xbb, 0x2d, 0x82, 0xba, 0x64, 0x40, 0x59, 0x35, 0x40, 0xa3, 0x64, 0xce, 0x89, 0x90, 0xe0, 0x13,
	0x0c, 0xa5, 0x84, 0xec, 0x07, 0x40, 0xc7, 0x79, 0xce, 0x0d, 0x47, 0xe4, 0xbc, 0x67, 0x5f, 0x85,
	0xcc, 0xaf, 0x60, 0x4b, 0x6c, 0xe0, 0x99, 0x1f, 0xa6, 0xae, 0x69, 0xf1, 0xaa, 0xbf, 0x1b, 0xcb,
	0x60, 0xef, 0x3d, 0xe9, 0x85, 0x4c, 0xa3, 0xc4, 0xa5, 0xf9, 0x1a, 0x3d, 0x87, 0x22, 0xdb, 0x5b,
	0x28, 0x67, 0xae, 0x53, 0x2e, 0x50, 0x51, 0xa1, 0xf9, 0x25, 0x14, 0xa8, 0x5b, 0x42, 0x31, 0x7b,
	0x9d, 0x22, 0x78, 0xf6, 0x15, 0xff, 0xd6, 0xff, 0xa8, 0x80, 0xda, 0x7b, 0x4f, 0x4e, 0xb0, 0x69,
	0x61, 0x1f, 0x1d, 0x82, 0x6a, 0x4e, 0xc7, 0xae, 0x6f, 0x93, 0xc9, 0x8c, 0x05, 0xa7, 0xd4, 0x78,
	0x24, 0xdb, 0x08, 0x05, 0xeb, 0x4d, 0x21, 0x65, 0x44, 0x0a, 0xcb, 0xad, 0x5f, 0x3a, 0x1a, 0x8e,
	0xea, 0xa0, 0x2e, 0x34, 0xe4, 0xd6, 0x5d, 0x85, 0x8d, 0x93, 0xf3, 0xc6, 0xb3, 0x2f, 0x35, 0x85,
	0x7e, 0x1a, 0xec, 0x33, 0xa5, 0xff, 0x25, 0x0d, 0x10, 0x39, 0x4c, 0x0d, 0x07, 0xf3, 0x8b, 0xdf,
	0xe0, 0x91, 0x00, 0x8a, 0x58, 0xa2, 0x1f, 0x03, 0x38, 0x2e, 0x19, 0x5e, 0xe0, 0x4b, 0xd7, 0x0f,
	0xaf, 0xe5, 0xf5, 0xd5, 0x40, 0x75, 0x5c, 0xf2, 0x82, 0x09, 0xa3, 0x1f, 0x01, 0x5d, 0x0c, 0xcd,
	0x4b, 0x82, 0xfd, 0x5b, 0x8c, 0x5c, 0x79, 0xc7, 0x25, 0x4d, 0x2a, 0x4b, 0xc7, 0xa5, 0xc0, 0xbd,
	0x24, 0xc3, 0x48, 0x3b, 0x7b, 0x73, 0x15, 0xa2, 0x1a, 0x5d, 0x61, 0x61, 0x0f, 0xb2, 0x76, 0x10,
	0xcc, 0xb1, 0xcf, 0x12, 0xac, 0x1a, 0x7c, 0x45, 0xcb, 0x06, 0xc3, 0x15, 0x2d, 0xa2, 0x1b, 0x61,
	0x04, 0xd9, 0xba, 0x63, 0xa1, 0x27, 0xb0, 0x15, 0xb2, 0xa2, 0xb1, 0x39, 0xcf, 0x24, 0x36, 0x19,
	0x79, 0x31, 0x34, 0xd7, 0xf9, 0xcf, 0x9b, 0x1c, 0x4b, 0x5e, 0x25, 0x11, 0x00, 0xf5, 0xfe, 0x07,
	0x0f, 0x87, 0x3f, 0x76, 0xf4, 0x2f, 0x20, 0x43, 0x57, 0x72, 0x52, 0x0a, 0x90, 0x33, 0xda, 0x2f,
	0x8d, 0xf6, 0xf9, 0x89, 0xa6, 0xa0, 0x3c, 0x64, 0x9a, 0x83, 0xfe, 0x89, 0x96, 0x42, 0x39, 0x48,
	0xf7, 0x3a, 0x6f, 0xb4, 0xb4, 0x3e, 0x83, 0x9d, 0xf0, 0x05, 0x17, 0xad, 0xd9, 0xf5, 0x4f, 0x40,
	0xe2, 0xd0, 0x9f, 0xba, 0x7e, 0xe8, 0x4f, 0x47, 0x43, 0xbf, 0xfe, 0x35, 0xec, 0x2e, 0x6d, 0xc7,
	0xef, 0xb3, 0xd4, 0x3c, 0x2a, 0xb7, 0x6b, 0x1e, 0x77, 0x00, 0x85, 0xd5, 0x5f, 0x2a, 0x99, 0xbb,
	0x70, 0x4f, 0xa2, 0xf2, 0xca, 0xf5, 0x67, 0x05, 0x76, 0x16, 0xb5, 0xf9, 0xb5, 0x4b, 0xf0, 0x0d,
	0x27, 0x7d, 0x0e, 0x99, 0x77, 0x2e, 0x09, 0x81, 0x58, 0x6a, 0x7c, 0x57, 0x9a, 0x2c, 0x56, 0xad,
	0xd4, 0xd9, 0x37, 0xd3, 0xd0, 0x1b, 0x90, 0xa1, 0x2b, 0x39, 0x0f, 0x59, 0x48, 0x0d, 0x7a, 0x61,
	0x0a, 0x8e, 0x28, 0x25, 0x45, 0xd9, 0xdd, 0xf6, 0xa0, 0x6f, 0x34, 0x4f, 0xb5, 0x34, 0x7d, 0xcc,
	0x96, 0xcc, 0x86, 0x6e, 0x7f, 0xfa, 0x13, 0x28, 0xc9, 0x0f, 0xa8, 0x6c, 0x36, 0x0f, 0x99, 0xee,
	0x59, 0x97, 0x0e, 0xca, 0x08, 0x4a, 0xc6, 0xe0, 0x94, 0x0e, 0xb3, 0x67, 0xa7, 0xcd, 0x7e, 0xe7,
	0xac, 0xab, 0xa5, 0x1a, 0xff, 0x05, 0x28, 0xf6, 0xa8, 0xdf, 0xe7, 0xd8, 0x7f, 0x67, 0x8f, 0x30,
	0xea, 0x00, 0x44, 0x45, 0x1d, 0xc5, 0xfb, 0xd7, 0x95, 0xe7, 0xa2, 0xf2, 0x70, 0x0d, 0x97, 0x27,
	0xac, 0x03, 0x10, 0x0d, 0x10, 0x92, 0xa9, 0x95, 0xc9, 0x4b, 0x32, 0x95, 0x30, 0x75, 0x9c, 0x41,
	0x31, 0xfe, 0xc8, 0xa1, 0x78, 0x9d, 0x4a, 0x78, 0x14, 0x2b, 0x1f, 0xad, 0xe5, 0x73, 0x83, 0x27,
	0xa0, 0x2e, 0xa2, 0x89, 0x1e, 0x24, 0xa5, 0x4e, 0x98, 0x3a, 0x48, 0x66, 0x86, 0x76, 0x6a, 0x0a,
	0x32, 0x60, 0x53, 0x6a, 0x32, 0x50, 0x7c, 0xef, 0xa4, 0xde, 0xa9, 0x52, 0x5d, 0x2f, 0xc0, 0xbd,
	0x6b, 0x41, 0x5e, 0xb4, 0x62, 0x48, 0xba, 0xd5, 0x72, 0x27, 0x57, 0x79, 0x90, 0xc8, 0xe3, 0x46,
	0x4c, 0x40, 0xab, 0x7d, 0x21, 0x8a, 0xc3, 0x74, 0x6d, 0xab, 0x59, 0xf9, 0xde, 0x0d, 0x52, 0x7c,
	0x8b, 0x37, 0xb0, 0xb5, 0xd4, 0xe0, 0xa2, 0x8f, 0x63, 0x9a, 0xc9, 0xdd, 0x72, 0x45, 0xbf, 0x4e,
	0x24, 0xca, 0xcf, 0xa2, 0x4b, 0x97, 0xf2, 0xb3, 0x3c, 0x36, 0x54, 0x0e, 0x92, 0x99, 0x8b, 0xfc,
	0x74, 0x00, 0xa2, 0x01, 0x44, 0x42, 0xe1, 0xca, 0x54, 0x23, 0xa1, 0x70, 0x75, 0x6a, 0xa1, 0xa9,
	0x96, 0xe6, 0x28, 0x29, 0xd5, 0x49, 0x93, 0x9b, 0x94, 0xea, 0xe4, 0x11, 0xec, 0xd7, 0xa0, 0x2d,
	0xcf, 0xaa, 0x28, 0x1e, 0xa0, 0x35, 0xb3, 0x6f, 0xe5, 0xf1, 0xb5, 0x32, 0x51, 0x7e, 0x96, 0xba,
	0x23, 0x29, 0x3f, 0xc9, 0x7d, 0x9a, 0x94, 0x9f, 0x75, 0xcd, 0x95, 0x01, 0x9b, 0x52, 0x95, 0x96,
	0x42, 0x91, 0xf4, 0x5c, 0x48, 0xa1, 0x48, 0x2e, 0xf0, 0xa7, 0x50, 0x88, 0x95, 0x65, 0xf4, 0x70,
	0x79, 0x42, 0x90, 0x8a, 0x78, 0xe5, 0xd1, 0x3a, 0x76, 0xe4, 0xa1, 0x54, 0x2f, 0x25, 0x0f, 0x93,
	0x0a, 0xb4, 0xe4, 0x61, 0x62, 0xa9, 0xa5, 0x58, 0x8a, 0xfe, 0xad, 0x49, 0x58, 0x5a, 0xf9, 0x41,
	0x27, 0x61, 0x69, 0xf5, 0x87, 0xdc, 0x8b, 0x2a, 0x6c, 0xba, 0xfe, 0x38, 0x92, 0x39, 0x49, 0xf5,
	0x94, 0x5f, 0xe5, 0x27, 0xa6, 0x63, 0x4d, 0xb1, 0x1f, 0xfc, 0x5b, 0x51, 0x2e, 0xb2, 0xac, 0xb3,
	0xf8, 0xe2, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x72, 0x58, 0x09, 0x5c, 0x1a, 0x00, 0x00,
}
