// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package handlers is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ApiPic
	ApiPicTag
	LookupPicDetailsResponse
	IndexResponse
	AddPicTagsResponse
	CreatePicResponse
	FindSimilarPicsResponse
	IncrementViewCountResponse
	PurgePicResponse
	SoftDeletePicResponse
	UpsertPicResponse
	GetSessionResponse
	JwtPayload
	GetXsrfTokenResponse
*/
package handlers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ApiPic struct {
	// id is the unique identifier for the pic, in varint form
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// width is the width of pic
	Width int32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	// height is the height of the pic
	Height int32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	// version is the version of the pic.  It is used when updating the pic.
	Version int64 `protobuf:"fixed64,4,opt,name=version" json:"version,omitempty"`
	// type is the mime type of the pic. (JPEG, GIF, PNG, or WEBM)
	Type string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	// relative_url is the location of the pic file relative to the root dir.
	RelativeUrl string `protobuf:"bytes,6,opt,name=relative_url,json=relativeUrl" json:"relative_url,omitempty"`
	// thumbnail_relative_url is the location of the the pic thumbnail
	// relative to the root dir.
	ThumbnailRelativeUrl string `protobuf:"bytes,7,opt,name=thumbnail_relative_url,json=thumbnailRelativeUrl" json:"thumbnail_relative_url,omitempty"`
	// pending_deletion indicates if the pic may be deleted soon.
	PendingDeletion bool `protobuf:"varint,9,opt,name=pending_deletion,json=pendingDeletion" json:"pending_deletion,omitempty"`
	// view_count is the number of views this picture has received.
	ViewCount int64 `protobuf:"varint,10,opt,name=view_count,json=viewCount" json:"view_count,omitempty"`
	// duration is present if the image is animated (GIF or WEBM).  Note that
	// GIFs duration is not well defined and is subject to reinterpretation.
	Duration *google_protobuf.Duration `protobuf:"bytes,11,opt,name=duration" json:"duration,omitempty"`
}

func (m *ApiPic) Reset()                    { *m = ApiPic{} }
func (m *ApiPic) String() string            { return proto.CompactTextString(m) }
func (*ApiPic) ProtoMessage()               {}
func (*ApiPic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApiPic) GetDuration() *google_protobuf.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type ApiPicTag struct {
	// pic_id is the unique identifier for the pic, in varint form
	PicId string `protobuf:"bytes,1,opt,name=pic_id,json=picId" json:"pic_id,omitempty"`
	// tag_id is the unique identifier for the tag, in varint form
	TagId string `protobuf:"bytes,2,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
	// name is the tag name in utf8 form
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// created_time is when the tag was created.
	CreatedTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// modified_time is when the tag was last modified.
	ModifiedTime *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=modified_time,json=modifiedTime" json:"modified_time,omitempty"`
	// version is the version of the tag.  It is used when updating the tag.
	Version int64 `protobuf:"fixed64,6,opt,name=version" json:"version,omitempty"`
}

func (m *ApiPicTag) Reset()                    { *m = ApiPicTag{} }
func (m *ApiPicTag) String() string            { return proto.CompactTextString(m) }
func (*ApiPicTag) ProtoMessage()               {}
func (*ApiPicTag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApiPicTag) GetCreatedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *ApiPicTag) GetModifiedTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ModifiedTime
	}
	return nil
}

type LookupPicDetailsResponse struct {
	Pic    *ApiPic      `protobuf:"bytes,1,opt,name=pic" json:"pic,omitempty"`
	PicTag []*ApiPicTag `protobuf:"bytes,2,rep,name=pic_tag,json=picTag" json:"pic_tag,omitempty"`
}

func (m *LookupPicDetailsResponse) Reset()                    { *m = LookupPicDetailsResponse{} }
func (m *LookupPicDetailsResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupPicDetailsResponse) ProtoMessage()               {}
func (*LookupPicDetailsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LookupPicDetailsResponse) GetPic() *ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

func (m *LookupPicDetailsResponse) GetPicTag() []*ApiPicTag {
	if m != nil {
		return m.PicTag
	}
	return nil
}

type IndexResponse struct {
	Pic []*ApiPic `protobuf:"bytes,1,rep,name=pic" json:"pic,omitempty"`
}

func (m *IndexResponse) Reset()                    { *m = IndexResponse{} }
func (m *IndexResponse) String() string            { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()               {}
func (*IndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IndexResponse) GetPic() []*ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

type AddPicTagsResponse struct {
}

func (m *AddPicTagsResponse) Reset()                    { *m = AddPicTagsResponse{} }
func (m *AddPicTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*AddPicTagsResponse) ProtoMessage()               {}
func (*AddPicTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CreatePicResponse struct {
	Pic *ApiPic `protobuf:"bytes,1,opt,name=pic" json:"pic,omitempty"`
}

func (m *CreatePicResponse) Reset()                    { *m = CreatePicResponse{} }
func (m *CreatePicResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePicResponse) ProtoMessage()               {}
func (*CreatePicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreatePicResponse) GetPic() *ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

type FindSimilarPicsResponse struct {
	Id []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
}

func (m *FindSimilarPicsResponse) Reset()                    { *m = FindSimilarPicsResponse{} }
func (m *FindSimilarPicsResponse) String() string            { return proto.CompactTextString(m) }
func (*FindSimilarPicsResponse) ProtoMessage()               {}
func (*FindSimilarPicsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type IncrementViewCountResponse struct {
}

func (m *IncrementViewCountResponse) Reset()                    { *m = IncrementViewCountResponse{} }
func (m *IncrementViewCountResponse) String() string            { return proto.CompactTextString(m) }
func (*IncrementViewCountResponse) ProtoMessage()               {}
func (*IncrementViewCountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type PurgePicResponse struct {
}

func (m *PurgePicResponse) Reset()                    { *m = PurgePicResponse{} }
func (m *PurgePicResponse) String() string            { return proto.CompactTextString(m) }
func (*PurgePicResponse) ProtoMessage()               {}
func (*PurgePicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SoftDeletePicResponse struct {
}

func (m *SoftDeletePicResponse) Reset()                    { *m = SoftDeletePicResponse{} }
func (m *SoftDeletePicResponse) String() string            { return proto.CompactTextString(m) }
func (*SoftDeletePicResponse) ProtoMessage()               {}
func (*SoftDeletePicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type UpsertPicResponse struct {
	Pic *ApiPic `protobuf:"bytes,1,opt,name=pic" json:"pic,omitempty"`
}

func (m *UpsertPicResponse) Reset()                    { *m = UpsertPicResponse{} }
func (m *UpsertPicResponse) String() string            { return proto.CompactTextString(m) }
func (*UpsertPicResponse) ProtoMessage()               {}
func (*UpsertPicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpsertPicResponse) GetPic() *ApiPic {
	if m != nil {
		return m.Pic
	}
	return nil
}

type GetSessionResponse struct {
	JwtPayload *JwtPayload `protobuf:"bytes,1,opt,name=jwt_payload,json=jwtPayload" json:"jwt_payload,omitempty"`
}

func (m *GetSessionResponse) Reset()                    { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()               {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetSessionResponse) GetJwtPayload() *JwtPayload {
	if m != nil {
		return m.JwtPayload
	}
	return nil
}

type JwtPayload struct {
	// subject is the Subject claim of the payload.  It is the user id in varint
	// form.
	Subject string `protobuf:"bytes,1,opt,name=subject,json=sub" json:"subject,omitempty"`
	// exp is the Expiration claim in unix epoch seconds.  Encodes as string in
	// jsonpb, int in the JWT.
	Expiration int64 `protobuf:"varint,2,opt,name=expiration,json=exp" json:"expiration,omitempty"`
	// not_before is the Not Before claim time in unix epoch seconds.  Encodes as
	// string in jsonpb, int in the JWT.
	NotBefore int64 `protobuf:"varint,3,opt,name=not_before,json=nbf" json:"not_before,omitempty"`
}

func (m *JwtPayload) Reset()                    { *m = JwtPayload{} }
func (m *JwtPayload) String() string            { return proto.CompactTextString(m) }
func (*JwtPayload) ProtoMessage()               {}
func (*JwtPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetXsrfTokenResponse struct {
}

func (m *GetXsrfTokenResponse) Reset()                    { *m = GetXsrfTokenResponse{} }
func (m *GetXsrfTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*GetXsrfTokenResponse) ProtoMessage()               {}
func (*GetXsrfTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*ApiPic)(nil), "pixur.api.ApiPic")
	proto.RegisterType((*ApiPicTag)(nil), "pixur.api.ApiPicTag")
	proto.RegisterType((*LookupPicDetailsResponse)(nil), "pixur.api.LookupPicDetailsResponse")
	proto.RegisterType((*IndexResponse)(nil), "pixur.api.IndexResponse")
	proto.RegisterType((*AddPicTagsResponse)(nil), "pixur.api.AddPicTagsResponse")
	proto.RegisterType((*CreatePicResponse)(nil), "pixur.api.CreatePicResponse")
	proto.RegisterType((*FindSimilarPicsResponse)(nil), "pixur.api.FindSimilarPicsResponse")
	proto.RegisterType((*IncrementViewCountResponse)(nil), "pixur.api.IncrementViewCountResponse")
	proto.RegisterType((*PurgePicResponse)(nil), "pixur.api.PurgePicResponse")
	proto.RegisterType((*SoftDeletePicResponse)(nil), "pixur.api.SoftDeletePicResponse")
	proto.RegisterType((*UpsertPicResponse)(nil), "pixur.api.UpsertPicResponse")
	proto.RegisterType((*GetSessionResponse)(nil), "pixur.api.GetSessionResponse")
	proto.RegisterType((*JwtPayload)(nil), "pixur.api.JwtPayload")
	proto.RegisterType((*GetXsrfTokenResponse)(nil), "pixur.api.GetXsrfTokenResponse")
}

var fileDescriptor0 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x4f, 0xe3, 0x46,
	0x14, 0x95, 0x6d, 0xf2, 0xe1, 0x6b, 0x68, 0xc3, 0x28, 0x80, 0x1b, 0xf5, 0xc3, 0x75, 0x5f, 0xc2,
	0x43, 0x83, 0x94, 0xd2, 0x8a, 0x97, 0xaa, 0xa2, 0xa0, 0xd2, 0x20, 0x1e, 0x22, 0x13, 0xaa, 0x6a,
	0x5f, 0xac, 0x89, 0x67, 0xe2, 0x0c, 0x38, 0x33, 0xa3, 0xf1, 0x98, 0x84, 0xff, 0xb9, 0x0f, 0xfb,
	0x0f, 0xf6, 0x6f, 0xac, 0xfc, 0x49, 0x58, 0xb4, 0x5a, 0xf1, 0x36, 0x73, 0xce, 0xb9, 0xd7, 0xc7,
	0xe7, 0xde, 0x01, 0x1b, 0x4b, 0x36, 0x92, 0x4a, 0x68, 0x81, 0x6c, 0xc9, 0x36, 0x99, 0x1a, 0x61,
	0xc9, 0x06, 0x3f, 0xc6, 0x42, 0xc4, 0x09, 0x3d, 0x29, 0x88, 0x79, 0xb6, 0x38, 0x21, 0x99, 0xc2,
	0x9a, 0x09, 0x5e, 0x4a, 0x07, 0x3f, 0x7d, 0xce, 0x6b, 0xb6, 0xa2, 0xa9, 0xc6, 0x2b, 0x59, 0x0a,
	0xfc, 0xf7, 0x26, 0xb4, 0xcf, 0x25, 0x9b, 0xb2, 0x08, 0x7d, 0x03, 0x26, 0x23, 0xae, 0xe1, 0x19,
	0x43, 0x3b, 0x30, 0x19, 0x41, 0x7d, 0x68, 0xad, 0x19, 0xd1, 0x4b, 0xd7, 0xf4, 0x8c, 0x61, 0x2b,
	0x28, 0x2f, 0xe8, 0x10, 0xda, 0x4b, 0xca, 0xe2, 0xa5, 0x76, 0xad, 0x02, 0xae, 0x6e, 0xc8, 0x85,
	0xce, 0x23, 0x55, 0x29, 0x13, 0xdc, 0xdd, 0xf1, 0x8c, 0x61, 0x2f, 0xa8, 0xaf, 0x08, 0xc1, 0x8e,
	0x7e, 0x92, 0xd4, 0x6d, 0x15, 0x9d, 0x8b, 0x33, 0xfa, 0x19, 0x76, 0x15, 0x4d, 0xb0, 0x66, 0x8f,
	0x34, 0xcc, 0x54, 0xe2, 0xb6, 0x0b, 0xce, 0xa9, 0xb1, 0x3b, 0x95, 0xa0, 0x53, 0x38, 0xd4, 0xcb,
	0x6c, 0x35, 0xe7, 0x98, 0x25, 0xe1, 0x0b, 0x71, 0xa7, 0x10, 0xf7, 0x1b, 0x36, 0xd8, 0xaa, 0x3a,
	0x86, 0x9e, 0xa4, 0x9c, 0x30, 0x1e, 0x87, 0x84, 0x26, 0x34, 0x8f, 0xc2, 0xb5, 0x3d, 0x63, 0xd8,
	0x0d, 0xbe, 0xad, 0xf0, 0xcb, 0x0a, 0x46, 0x3f, 0x00, 0x3c, 0x32, 0xba, 0x0e, 0x23, 0x91, 0x71,
	0xed, 0x82, 0x67, 0x0c, 0xad, 0xc0, 0xce, 0x91, 0x8b, 0x1c, 0x40, 0xbf, 0x43, 0xb7, 0x0e, 0xd3,
	0x75, 0x3c, 0x63, 0xe8, 0x8c, 0xbf, 0x1b, 0x95, 0x69, 0x8e, 0xea, 0x34, 0x47, 0x97, 0x95, 0x20,
	0x68, 0xa4, 0xd7, 0x3b, 0xdd, 0x6e, 0xcf, 0xf6, 0x3f, 0x1a, 0x60, 0x97, 0xb1, 0xce, 0x70, 0x8c,
	0x0e, 0xa0, 0x2d, 0x59, 0x14, 0x36, 0xe9, 0xb6, 0x24, 0x8b, 0x26, 0x24, 0x87, 0x35, 0x8e, 0x73,
	0xd8, 0x2c, 0x61, 0x8d, 0xe3, 0x09, 0xc9, 0xf3, 0xe2, 0x78, 0x45, 0x8b, 0x7c, 0xed, 0xa0, 0x38,
	0xa3, 0x3f, 0x61, 0x37, 0x52, 0x14, 0x6b, 0x4a, 0xc2, 0x7c, 0x82, 0x45, 0xc4, 0xce, 0x78, 0xf0,
	0xca, 0xd0, 0xac, 0x1e, 0x6f, 0xe0, 0x54, 0xfa, 0x1c, 0x41, 0x7f, 0xc1, 0xde, 0x4a, 0x10, 0xb6,
	0x60, 0x75, 0x7d, 0xeb, 0xab, 0xf5, 0xbb, 0x75, 0x41, 0xd1, 0x60, 0x6b, 0xba, 0xed, 0x17, 0xd3,
	0xf5, 0x39, 0xb8, 0x37, 0x42, 0x3c, 0x64, 0x72, 0xca, 0xa2, 0x4b, 0xaa, 0x31, 0x4b, 0xd2, 0x80,
	0xa6, 0x52, 0xf0, 0x94, 0xa2, 0x5f, 0xc0, 0x92, 0x2c, 0x2a, 0x7e, 0xda, 0x19, 0xef, 0x8f, 0x9a,
	0xb5, 0x1d, 0x95, 0xd1, 0x04, 0x39, 0x8b, 0x7e, 0x85, 0x4e, 0x1e, 0x8e, 0xc6, 0xb1, 0x6b, 0x7a,
	0xd6, 0xd0, 0x19, 0xf7, 0x5f, 0x09, 0x67, 0x38, 0x0e, 0xf2, 0x04, 0x67, 0x38, 0xf6, 0x4f, 0x61,
	0x6f, 0xc2, 0x09, 0xdd, 0xbc, 0xfe, 0x88, 0xf5, 0xe5, 0x8f, 0xf8, 0x7d, 0x40, 0xe7, 0x84, 0x94,
	0xad, 0x1a, 0x7f, 0xfe, 0x19, 0xec, 0x5f, 0x14, 0x29, 0xe5, 0xba, 0xb7, 0x98, 0xf6, 0x8f, 0xe1,
	0xe8, 0x1f, 0xc6, 0xc9, 0x2d, 0x5b, 0xb1, 0x04, 0xab, 0x29, 0x8b, 0x9e, 0x7f, 0xba, 0x7e, 0x46,
	0x56, 0xf9, 0x8c, 0xfc, 0xef, 0x61, 0x30, 0xe1, 0x91, 0xa2, 0x2b, 0xca, 0xf5, 0x7f, 0xf5, 0x76,
	0x35, 0x16, 0x10, 0xf4, 0xa6, 0x99, 0x8a, 0xb7, 0x1d, 0xf8, 0x47, 0x70, 0x70, 0x2b, 0x16, 0xba,
	0x58, 0xd4, 0x17, 0xc4, 0x19, 0xec, 0xdf, 0xc9, 0x94, 0x2a, 0xfd, 0x66, 0xbf, 0x37, 0x80, 0xae,
	0xa8, 0xbe, 0xa5, 0x69, 0x3e, 0xb3, 0xa6, 0xf4, 0x0f, 0x70, 0xee, 0xd7, 0x3a, 0x94, 0xf8, 0x29,
	0x11, 0x98, 0x54, 0x2d, 0x0e, 0xb6, 0x5a, 0x5c, 0xaf, 0xf5, 0xb4, 0x24, 0x03, 0xb8, 0x6f, 0xce,
	0xfe, 0x0c, 0xe0, 0x99, 0x41, 0x7d, 0xe8, 0xa4, 0xd9, 0xfc, 0x9e, 0x46, 0xba, 0x5a, 0x6f, 0x2b,
	0xcd, 0xe6, 0xe8, 0x08, 0x80, 0x6e, 0x24, 0xab, 0x1e, 0x90, 0x59, 0xbc, 0x2e, 0x8b, 0x6e, 0x64,
	0x4e, 0x70, 0xa1, 0xc3, 0x39, 0x5d, 0x08, 0x55, 0x2e, 0xb9, 0x15, 0x58, 0x7c, 0xbe, 0xf0, 0x0f,
	0xa1, 0x7f, 0x45, 0xf5, 0xff, 0xa9, 0x5a, 0xcc, 0xc4, 0x03, 0x6d, 0x5c, 0xfe, 0xed, 0xc1, 0x9e,
	0x50, 0xf1, 0xb3, 0xab, 0x7f, 0xcd, 0xa9, 0xf1, 0xae, 0xbb, 0xc4, 0x9c, 0x24, 0x54, 0xa5, 0x1f,
	0x0c, 0x63, 0xde, 0x2e, 0xf6, 0xf7, 0xb7, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xec, 0x0d,
	0x36, 0x24, 0x05, 0x00, 0x00,
}
