// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pixur.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pic_Mime int32

const (
	Pic_UNKNOWN Pic_Mime = 0
	Pic_JPEG    Pic_Mime = 1
	Pic_GIF     Pic_Mime = 2
	Pic_PNG     Pic_Mime = 3
	Pic_WEBM    Pic_Mime = 4
)

var Pic_Mime_name = map[int32]string{
	0: "UNKNOWN",
	1: "JPEG",
	2: "GIF",
	3: "PNG",
	4: "WEBM",
}
var Pic_Mime_value = map[string]int32{
	"UNKNOWN": 0,
	"JPEG":    1,
	"GIF":     2,
	"PNG":     3,
	"WEBM":    4,
}

func (x Pic_Mime) String() string {
	return proto.EnumName(Pic_Mime_name, int32(x))
}
func (Pic_Mime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{0, 0}
}

type Pic_DeletionStatus_Reason int32

const (
	// The reason is not know, due to limitations of proto
	Pic_DeletionStatus_UNKNOWN Pic_DeletionStatus_Reason = 0
	// No specific reason.  This is a catch-all reason.
	Pic_DeletionStatus_NONE Pic_DeletionStatus_Reason = 1
	// The pic is in violation of the rules.
	Pic_DeletionStatus_RULE_VIOLATION Pic_DeletionStatus_Reason = 2
)

var Pic_DeletionStatus_Reason_name = map[int32]string{
	0: "UNKNOWN",
	1: "NONE",
	2: "RULE_VIOLATION",
}
var Pic_DeletionStatus_Reason_value = map[string]int32{
	"UNKNOWN":        0,
	"NONE":           1,
	"RULE_VIOLATION": 2,
}

func (x Pic_DeletionStatus_Reason) String() string {
	return proto.EnumName(Pic_DeletionStatus_Reason_name, int32(x))
}
func (Pic_DeletionStatus_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{0, 0, 0}
}

type PicIdent_Type int32

const (
	PicIdent_UNKNOWN PicIdent_Type = 0
	PicIdent_SHA256  PicIdent_Type = 1
	PicIdent_SHA1    PicIdent_Type = 2
	PicIdent_MD5     PicIdent_Type = 3
	PicIdent_DCT_0   PicIdent_Type = 4
)

var PicIdent_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "SHA256",
	2: "SHA1",
	3: "MD5",
	4: "DCT_0",
}
var PicIdent_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"SHA256":  1,
	"SHA1":    2,
	"MD5":     3,
	"DCT_0":   4,
}

func (x PicIdent_Type) String() string {
	return proto.EnumName(PicIdent_Type_name, int32(x))
}
func (PicIdent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{1, 0}
}

type PicVote_Vote int32

const (
	PicVote_UNKNOWN PicVote_Vote = 0
	PicVote_UP      PicVote_Vote = 1
	PicVote_DOWN    PicVote_Vote = 2
	PicVote_NEUTRAL PicVote_Vote = 3
)

var PicVote_Vote_name = map[int32]string{
	0: "UNKNOWN",
	1: "UP",
	2: "DOWN",
	3: "NEUTRAL",
}
var PicVote_Vote_value = map[string]int32{
	"UNKNOWN": 0,
	"UP":      1,
	"DOWN":    2,
	"NEUTRAL": 3,
}

func (x PicVote_Vote) String() string {
	return proto.EnumName(PicVote_Vote_name, int32(x))
}
func (PicVote_Vote) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{6, 0}
}

type User_Capability int32

const (
	User_UNKNOWN User_Capability = 0
	// Can this user create and upload pictures
	User_PIC_CREATE User_Capability = 1
	// Can this user view the actual image data (grants pic token)
	User_PIC_READ User_Capability = 2
	// Can this user perform general pic index queries?
	User_PIC_INDEX User_Capability = 3
	// Can this user soft delete a pic?
	User_PIC_SOFT_DELETE User_Capability = 5
	// Can this user hard delete a pic?
	User_PIC_HARD_DELETE User_Capability = 6
	// Can this user purge a pic?
	User_PIC_PURGE User_Capability = 7
	// Can this user increment the pic view counter?
	User_PIC_UPDATE_VIEW_COUNTER User_Capability = 8
	// Can this user add tags and pic tags?
	User_PIC_TAG_CREATE User_Capability = 9
	// Can this user create comments?
	User_PIC_COMMENT_CREATE User_Capability = 10
	// Can this user vote?
	User_PIC_VOTE_CREATE User_Capability = 11
	// Can this user create other users?
	User_USER_CREATE User_Capability = 4
	// Can this user modify capabilities?
	User_USER_UPDATE_CAPABILITY User_Capability = 12
	// Can this user read information about themselves?
	User_USER_READ_SELF User_Capability = 13
	// Can this user read infortmation about others?
	User_USER_READ_ALL User_Capability = 14
)

var User_Capability_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "PIC_CREATE",
	2:  "PIC_READ",
	3:  "PIC_INDEX",
	5:  "PIC_SOFT_DELETE",
	6:  "PIC_HARD_DELETE",
	7:  "PIC_PURGE",
	8:  "PIC_UPDATE_VIEW_COUNTER",
	9:  "PIC_TAG_CREATE",
	10: "PIC_COMMENT_CREATE",
	11: "PIC_VOTE_CREATE",
	4:  "USER_CREATE",
	12: "USER_UPDATE_CAPABILITY",
	13: "USER_READ_SELF",
	14: "USER_READ_ALL",
}
var User_Capability_value = map[string]int32{
	"UNKNOWN":                 0,
	"PIC_CREATE":              1,
	"PIC_READ":                2,
	"PIC_INDEX":               3,
	"PIC_SOFT_DELETE":         5,
	"PIC_HARD_DELETE":         6,
	"PIC_PURGE":               7,
	"PIC_UPDATE_VIEW_COUNTER": 8,
	"PIC_TAG_CREATE":          9,
	"PIC_COMMENT_CREATE":      10,
	"PIC_VOTE_CREATE":         11,
	"USER_CREATE":             4,
	"USER_UPDATE_CAPABILITY":  12,
	"USER_READ_SELF":          13,
	"USER_READ_ALL":           14,
}

func (x User_Capability) String() string {
	return proto.EnumName(User_Capability_name, int32(x))
}
func (User_Capability) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{7, 0}
}

type Pic struct {
	PicId      int64                `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	FileSize   int64                `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Mime       Pic_Mime             `protobuf:"varint,3,opt,name=mime,proto3,enum=pixur.Pic_Mime" json:"mime,omitempty"`
	Width      int64                `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height     int64                `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,11,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// If present, the pic is on the path to removal.  When the pic is marked
	// for deletion, it is delisted from normal indexing operations.  When the
	// pic is actually "deleted" only the pic object is removed.
	DeletionStatus *Pic_DeletionStatus `protobuf:"bytes,12,opt,name=deletion_status,json=deletionStatus,proto3" json:"deletion_status,omitempty"`
	// Only present on animated images.
	AnimationInfo *AnimationInfo    `protobuf:"bytes,13,opt,name=animation_info,json=animationInfo,proto3" json:"animation_info,omitempty"`
	ViewCount     int64             `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Source        []*Pic_FileSource `protobuf:"bytes,15,rep,name=source,proto3" json:"source,omitempty"`
	FileName      []string          `protobuf:"bytes,16,rep,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// The denormalized sum of upvotes for this pic
	VoteUp int64 `protobuf:"varint,17,opt,name=vote_up,json=voteUp,proto3" json:"vote_up,omitempty"`
	// The denormalized sum of downvotes for this pic
	VoteDown int64 `protobuf:"varint,18,opt,name=vote_down,json=voteDown,proto3" json:"vote_down,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,19,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pic) Reset()         { *m = Pic{} }
func (m *Pic) String() string { return proto.CompactTextString(m) }
func (*Pic) ProtoMessage()    {}
func (*Pic) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{0}
}
func (m *Pic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic.Unmarshal(m, b)
}
func (m *Pic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic.Marshal(b, m, deterministic)
}
func (dst *Pic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic.Merge(dst, src)
}
func (m *Pic) XXX_Size() int {
	return xxx_messageInfo_Pic.Size(m)
}
func (m *Pic) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic.DiscardUnknown(m)
}

var xxx_messageInfo_Pic proto.InternalMessageInfo

func (m *Pic) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *Pic) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *Pic) GetMime() Pic_Mime {
	if m != nil {
		return m.Mime
	}
	return Pic_UNKNOWN
}

func (m *Pic) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Pic) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Pic) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *Pic) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *Pic) GetDeletionStatus() *Pic_DeletionStatus {
	if m != nil {
		return m.DeletionStatus
	}
	return nil
}

func (m *Pic) GetAnimationInfo() *AnimationInfo {
	if m != nil {
		return m.AnimationInfo
	}
	return nil
}

func (m *Pic) GetViewCount() int64 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *Pic) GetSource() []*Pic_FileSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Pic) GetFileName() []string {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *Pic) GetVoteUp() int64 {
	if m != nil {
		return m.VoteUp
	}
	return 0
}

func (m *Pic) GetVoteDown() int64 {
	if m != nil {
		return m.VoteDown
	}
	return 0
}

func (m *Pic) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type Pic_DeletionStatus struct {
	// Represents when this Pic was marked for deletion
	MarkedDeletedTs *timestamp.Timestamp `protobuf:"bytes,1,opt,name=marked_deleted_ts,json=markedDeletedTs,proto3" json:"marked_deleted_ts,omitempty"`
	// Represents when this picture will be auto deleted.  Note that the Pic
	// may exist for a short period after this time.  (may be absent)
	PendingDeletedTs *timestamp.Timestamp `protobuf:"bytes,2,opt,name=pending_deleted_ts,json=pendingDeletedTs,proto3" json:"pending_deleted_ts,omitempty"`
	// Determines when Pic was actually deleted.  (present after the Pic is
	// hard deleted, a.k.a purging)
	ActualDeletedTs *timestamp.Timestamp `protobuf:"bytes,3,opt,name=actual_deleted_ts,json=actualDeletedTs,proto3" json:"actual_deleted_ts,omitempty"`
	// Gives an explanation for why this pic was removed.
	Details string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	// The reason the pic was removed.
	Reason Pic_DeletionStatus_Reason `protobuf:"varint,5,opt,name=reason,proto3,enum=pixur.Pic_DeletionStatus_Reason" json:"reason,omitempty"`
	// Determines if this pic can be undeleted if re uploaded.  Currently the
	// only reason is due to disk space concerns.
	Temporary            bool     `protobuf:"varint,6,opt,name=temporary,proto3" json:"temporary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pic_DeletionStatus) Reset()         { *m = Pic_DeletionStatus{} }
func (m *Pic_DeletionStatus) String() string { return proto.CompactTextString(m) }
func (*Pic_DeletionStatus) ProtoMessage()    {}
func (*Pic_DeletionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{0, 0}
}
func (m *Pic_DeletionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic_DeletionStatus.Unmarshal(m, b)
}
func (m *Pic_DeletionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic_DeletionStatus.Marshal(b, m, deterministic)
}
func (dst *Pic_DeletionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic_DeletionStatus.Merge(dst, src)
}
func (m *Pic_DeletionStatus) XXX_Size() int {
	return xxx_messageInfo_Pic_DeletionStatus.Size(m)
}
func (m *Pic_DeletionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic_DeletionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Pic_DeletionStatus proto.InternalMessageInfo

func (m *Pic_DeletionStatus) GetMarkedDeletedTs() *timestamp.Timestamp {
	if m != nil {
		return m.MarkedDeletedTs
	}
	return nil
}

func (m *Pic_DeletionStatus) GetPendingDeletedTs() *timestamp.Timestamp {
	if m != nil {
		return m.PendingDeletedTs
	}
	return nil
}

func (m *Pic_DeletionStatus) GetActualDeletedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ActualDeletedTs
	}
	return nil
}

func (m *Pic_DeletionStatus) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Pic_DeletionStatus) GetReason() Pic_DeletionStatus_Reason {
	if m != nil {
		return m.Reason
	}
	return Pic_DeletionStatus_UNKNOWN
}

func (m *Pic_DeletionStatus) GetTemporary() bool {
	if m != nil {
		return m.Temporary
	}
	return false
}

type Pic_FileSource struct {
	Url                  string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Referrer             string               `protobuf:"bytes,2,opt,name=referrer,proto3" json:"referrer,omitempty"`
	CreatedTs            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pic_FileSource) Reset()         { *m = Pic_FileSource{} }
func (m *Pic_FileSource) String() string { return proto.CompactTextString(m) }
func (*Pic_FileSource) ProtoMessage()    {}
func (*Pic_FileSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{0, 1}
}
func (m *Pic_FileSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic_FileSource.Unmarshal(m, b)
}
func (m *Pic_FileSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic_FileSource.Marshal(b, m, deterministic)
}
func (dst *Pic_FileSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic_FileSource.Merge(dst, src)
}
func (m *Pic_FileSource) XXX_Size() int {
	return xxx_messageInfo_Pic_FileSource.Size(m)
}
func (m *Pic_FileSource) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic_FileSource.DiscardUnknown(m)
}

var xxx_messageInfo_Pic_FileSource proto.InternalMessageInfo

func (m *Pic_FileSource) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Pic_FileSource) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

func (m *Pic_FileSource) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

// A picture identifier
type PicIdent struct {
	PicId int64         `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	Type  PicIdent_Type `protobuf:"varint,2,opt,name=type,proto3,enum=pixur.PicIdent_Type" json:"type,omitempty"`
	Value []byte        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// dct0 are the upper 8x8 corner of the 32x32 dct of the image
	Dct0Values []float32 `protobuf:"fixed32,4,rep,packed,name=dct0_values,json=dct0Values,proto3" json:"dct0_values,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,5,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PicIdent) Reset()         { *m = PicIdent{} }
func (m *PicIdent) String() string { return proto.CompactTextString(m) }
func (*PicIdent) ProtoMessage()    {}
func (*PicIdent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{1}
}
func (m *PicIdent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicIdent.Unmarshal(m, b)
}
func (m *PicIdent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicIdent.Marshal(b, m, deterministic)
}
func (dst *PicIdent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicIdent.Merge(dst, src)
}
func (m *PicIdent) XXX_Size() int {
	return xxx_messageInfo_PicIdent.Size(m)
}
func (m *PicIdent) XXX_DiscardUnknown() {
	xxx_messageInfo_PicIdent.DiscardUnknown(m)
}

var xxx_messageInfo_PicIdent proto.InternalMessageInfo

func (m *PicIdent) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicIdent) GetType() PicIdent_Type {
	if m != nil {
		return m.Type
	}
	return PicIdent_UNKNOWN
}

func (m *PicIdent) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PicIdent) GetDct0Values() []float32 {
	if m != nil {
		return m.Dct0Values
	}
	return nil
}

func (m *PicIdent) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type AnimationInfo struct {
	// How long this animated image in time.  There must be more than 1 frame
	// for this value to be set.
	Duration             *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AnimationInfo) Reset()         { *m = AnimationInfo{} }
func (m *AnimationInfo) String() string { return proto.CompactTextString(m) }
func (*AnimationInfo) ProtoMessage()    {}
func (*AnimationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{2}
}
func (m *AnimationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimationInfo.Unmarshal(m, b)
}
func (m *AnimationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimationInfo.Marshal(b, m, deterministic)
}
func (dst *AnimationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimationInfo.Merge(dst, src)
}
func (m *AnimationInfo) XXX_Size() int {
	return xxx_messageInfo_AnimationInfo.Size(m)
}
func (m *AnimationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AnimationInfo proto.InternalMessageInfo

func (m *AnimationInfo) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type Tag struct {
	TagId      int64                `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name       string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UsageCount int64                `protobuf:"varint,3,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,8,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{3}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetUsageCount() int64 {
	if m != nil {
		return m.UsageCount
	}
	return 0
}

func (m *Tag) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *Tag) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *Tag) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PicTag struct {
	PicId int64  `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	TagId int64  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The user who originally created this tag.  optional.
	UserId     int64                `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,9,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PicTag) Reset()         { *m = PicTag{} }
func (m *PicTag) String() string { return proto.CompactTextString(m) }
func (*PicTag) ProtoMessage()    {}
func (*PicTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{4}
}
func (m *PicTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicTag.Unmarshal(m, b)
}
func (m *PicTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicTag.Marshal(b, m, deterministic)
}
func (dst *PicTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicTag.Merge(dst, src)
}
func (m *PicTag) XXX_Size() int {
	return xxx_messageInfo_PicTag.Size(m)
}
func (m *PicTag) XXX_DiscardUnknown() {
	xxx_messageInfo_PicTag.DiscardUnknown(m)
}

var xxx_messageInfo_PicTag proto.InternalMessageInfo

func (m *PicTag) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicTag) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *PicTag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PicTag) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicTag) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *PicTag) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *PicTag) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PicComment struct {
	PicId     int64 `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	CommentId int64 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	// parent id of this comment.  0 if root.
	CommentParentId int64 `protobuf:"varint,3,opt,name=comment_parent_id,json=commentParentId,proto3" json:"comment_parent_id,omitempty"`
	// author
	UserId     int64                `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text       string               `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,6,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,8,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PicComment) Reset()         { *m = PicComment{} }
func (m *PicComment) String() string { return proto.CompactTextString(m) }
func (*PicComment) ProtoMessage()    {}
func (*PicComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{5}
}
func (m *PicComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicComment.Unmarshal(m, b)
}
func (m *PicComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicComment.Marshal(b, m, deterministic)
}
func (dst *PicComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicComment.Merge(dst, src)
}
func (m *PicComment) XXX_Size() int {
	return xxx_messageInfo_PicComment.Size(m)
}
func (m *PicComment) XXX_DiscardUnknown() {
	xxx_messageInfo_PicComment.DiscardUnknown(m)
}

var xxx_messageInfo_PicComment proto.InternalMessageInfo

func (m *PicComment) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicComment) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PicComment) GetCommentParentId() int64 {
	if m != nil {
		return m.CommentParentId
	}
	return 0
}

func (m *PicComment) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicComment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PicComment) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *PicComment) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *PicComment) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PicVote struct {
	PicId      int64                `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	UserId     int64                `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Vote       PicVote_Vote         `protobuf:"varint,3,opt,name=vote,proto3,enum=pixur.PicVote_Vote" json:"vote,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,5,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,6,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PicVote) Reset()         { *m = PicVote{} }
func (m *PicVote) String() string { return proto.CompactTextString(m) }
func (*PicVote) ProtoMessage()    {}
func (*PicVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{6}
}
func (m *PicVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicVote.Unmarshal(m, b)
}
func (m *PicVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicVote.Marshal(b, m, deterministic)
}
func (dst *PicVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicVote.Merge(dst, src)
}
func (m *PicVote) XXX_Size() int {
	return xxx_messageInfo_PicVote.Size(m)
}
func (m *PicVote) XXX_DiscardUnknown() {
	xxx_messageInfo_PicVote.DiscardUnknown(m)
}

var xxx_messageInfo_PicVote proto.InternalMessageInfo

func (m *PicVote) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicVote) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicVote) GetVote() PicVote_Vote {
	if m != nil {
		return m.Vote
	}
	return PicVote_UNKNOWN
}

func (m *PicVote) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *PicVote) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *PicVote) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type User struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Hashed secret token
	Secret []byte `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// Identity of the user, usually an email.
	Ident      string               `protobuf:"bytes,3,opt,name=ident,proto3" json:"ident,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,5,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	LastSeenTs *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_seen_ts,json=lastSeenTs,proto3" json:"last_seen_ts,omitempty"`
	Capability []User_Capability    `protobuf:"varint,7,rep,packed,name=capability,proto3,enum=pixur.User_Capability" json:"capability,omitempty"`
	// Always increment-then-get
	NextTokenId int64        `protobuf:"varint,8,opt,name=next_token_id,json=nextTokenId,proto3" json:"next_token_id,omitempty"`
	UserToken   []*UserToken `protobuf:"bytes,9,rep,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  []*any.Any `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{7}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *User) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *User) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *User) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *User) GetLastSeenTs() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenTs
	}
	return nil
}

func (m *User) GetCapability() []User_Capability {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *User) GetNextTokenId() int64 {
	if m != nil {
		return m.NextTokenId
	}
	return 0
}

func (m *User) GetUserToken() []*UserToken {
	if m != nil {
		return m.UserToken
	}
	return nil
}

func (m *User) GetExt() []*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

// Represent the valid auth tokens.  When a user logs out, these will be
// deleted.
type UserToken struct {
	TokenId              int64                `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	CreatedTs            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	LastSeenTs           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_seen_ts,json=lastSeenTs,proto3" json:"last_seen_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_pixur_28c9f0fba5e6f146, []int{8}
}
func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (dst *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(dst, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetTokenId() int64 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

func (m *UserToken) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *UserToken) GetLastSeenTs() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenTs
	}
	return nil
}

func init() {
	proto.RegisterType((*Pic)(nil), "pixur.Pic")
	proto.RegisterType((*Pic_DeletionStatus)(nil), "pixur.Pic.DeletionStatus")
	proto.RegisterType((*Pic_FileSource)(nil), "pixur.Pic.FileSource")
	proto.RegisterType((*PicIdent)(nil), "pixur.PicIdent")
	proto.RegisterType((*AnimationInfo)(nil), "pixur.AnimationInfo")
	proto.RegisterType((*Tag)(nil), "pixur.Tag")
	proto.RegisterType((*PicTag)(nil), "pixur.PicTag")
	proto.RegisterType((*PicComment)(nil), "pixur.PicComment")
	proto.RegisterType((*PicVote)(nil), "pixur.PicVote")
	proto.RegisterType((*User)(nil), "pixur.User")
	proto.RegisterType((*UserToken)(nil), "pixur.UserToken")
	proto.RegisterEnum("pixur.Pic_Mime", Pic_Mime_name, Pic_Mime_value)
	proto.RegisterEnum("pixur.Pic_DeletionStatus_Reason", Pic_DeletionStatus_Reason_name, Pic_DeletionStatus_Reason_value)
	proto.RegisterEnum("pixur.PicIdent_Type", PicIdent_Type_name, PicIdent_Type_value)
	proto.RegisterEnum("pixur.PicVote_Vote", PicVote_Vote_name, PicVote_Vote_value)
	proto.RegisterEnum("pixur.User_Capability", User_Capability_name, User_Capability_value)
}

func init() { proto.RegisterFile("pixur.proto", fileDescriptor_pixur_28c9f0fba5e6f146) }

var fileDescriptor_pixur_28c9f0fba5e6f146 = []byte{
	// 1380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4f, 0x6f, 0xdb, 0xc6,
	0x12, 0x7f, 0x22, 0x29, 0x4a, 0x1c, 0xd9, 0x32, 0xbd, 0x49, 0x1c, 0xda, 0x79, 0x79, 0x11, 0x14,
	0xe0, 0x3d, 0xe1, 0x01, 0x55, 0x52, 0x07, 0x09, 0x1a, 0xa4, 0x3d, 0xc8, 0x12, 0x6d, 0xab, 0x95,
	0x25, 0x61, 0x45, 0x39, 0x6d, 0x2f, 0x04, 0x43, 0xae, 0xe5, 0x45, 0x44, 0x52, 0x20, 0x97, 0x71,
	0x9c, 0x6b, 0x3f, 0x41, 0x81, 0xde, 0xfb, 0x19, 0x7a, 0xe9, 0xa5, 0x5f, 0xa9, 0x3d, 0xf4, 0x1b,
	0x14, 0xbb, 0x24, 0xf5, 0xc7, 0x49, 0xaa, 0xba, 0x41, 0x91, 0x8b, 0xb0, 0xf3, 0x9b, 0xdf, 0xce,
	0xee, 0xfc, 0x66, 0x76, 0x44, 0xa8, 0xcc, 0xe8, 0xeb, 0x24, 0x6a, 0xce, 0xa2, 0x90, 0x85, 0xa8,
	0x28, 0x8c, 0xbd, 0xdd, 0x49, 0x18, 0x4e, 0xa6, 0xe4, 0x81, 0x00, 0x5f, 0x24, 0x67, 0x0f, 0x9c,
	0xe0, 0x32, 0x65, 0xec, 0xfd, 0xe7, 0xaa, 0xcb, 0x4b, 0x22, 0x87, 0xd1, 0x30, 0xc8, 0xfc, 0xf7,
	0xae, 0xfa, 0x19, 0xf5, 0x49, 0xcc, 0x1c, 0x7f, 0x96, 0x12, 0xea, 0x3f, 0x68, 0x20, 0x0f, 0xa9,
	0x8b, 0x6e, 0x81, 0x3a, 0xa3, 0xae, 0x4d, 0x3d, 0xa3, 0x50, 0x2b, 0x34, 0x64, 0x5c, 0x9c, 0x51,
	0xb7, 0xeb, 0xa1, 0x3b, 0xa0, 0x9d, 0xd1, 0x29, 0xb1, 0x63, 0xfa, 0x86, 0x18, 0x92, 0xf0, 0x94,
	0x39, 0x30, 0xa2, 0x6f, 0x08, 0xba, 0x0f, 0x8a, 0x4f, 0x7d, 0x62, 0xc8, 0xb5, 0x42, 0xa3, 0xba,
	0xbf, 0xd5, 0x4c, 0xaf, 0x3e, 0xa4, 0x6e, 0xf3, 0x84, 0xfa, 0x04, 0x0b, 0x27, 0xba, 0x09, 0xc5,
	0x0b, 0xea, 0xb1, 0x73, 0x43, 0x49, 0xe3, 0x0a, 0x03, 0xed, 0x80, 0x7a, 0x4e, 0xe8, 0xe4, 0x9c,
	0x19, 0x45, 0x01, 0x67, 0x16, 0x7a, 0x0a, 0xe0, 0x46, 0xc4, 0x61, 0xc4, 0xb3, 0x59, 0x6c, 0x40,
	0xad, 0xd0, 0xa8, 0xec, 0xef, 0x35, 0xd3, 0x24, 0x9a, 0x79, 0x12, 0x4d, 0x2b, 0x4f, 0x02, 0x6b,
	0x19, 0xdb, 0x8a, 0xd1, 0x33, 0xa8, 0xf8, 0xa1, 0x47, 0xcf, 0x68, 0xba, 0xb7, 0xb2, 0x76, 0x2f,
	0xe4, 0x74, 0x2b, 0x46, 0x07, 0xb0, 0xe5, 0x91, 0x29, 0xe1, 0xca, 0xd9, 0x31, 0x73, 0x58, 0x12,
	0x1b, 0x1b, 0x22, 0xc0, 0xee, 0x52, 0x56, 0x9d, 0x8c, 0x31, 0x12, 0x04, 0x5c, 0xf5, 0x56, 0x6c,
	0xf4, 0x0c, 0xaa, 0x4e, 0x40, 0x7d, 0x21, 0xbf, 0x4d, 0x83, 0xb3, 0xd0, 0xd8, 0x14, 0x21, 0x6e,
	0x66, 0x21, 0x5a, 0xb9, 0xb3, 0x1b, 0x9c, 0x85, 0x78, 0xd3, 0x59, 0x36, 0xd1, 0x5d, 0x80, 0x57,
	0x94, 0x5c, 0xd8, 0x6e, 0x98, 0x04, 0xcc, 0xa8, 0x0a, 0x51, 0x34, 0x8e, 0xb4, 0x39, 0x80, 0x3e,
	0x01, 0x35, 0x0e, 0x93, 0xc8, 0x25, 0xc6, 0x56, 0x4d, 0x6e, 0x54, 0xf6, 0x6f, 0x2d, 0x5d, 0xeb,
	0x90, 0xd7, 0x43, 0x38, 0x71, 0x46, 0x9a, 0x97, 0x2d, 0x70, 0x7c, 0x62, 0xe8, 0x35, 0xb9, 0xa1,
	0xa5, 0x65, 0xeb, 0x3b, 0x3e, 0x41, 0xb7, 0xa1, 0xf4, 0x2a, 0x64, 0xc4, 0x4e, 0x66, 0xc6, 0x76,
	0x2a, 0x3e, 0x37, 0xc7, 0x33, 0xbe, 0x4b, 0x38, 0xbc, 0xf0, 0x22, 0x30, 0x50, 0x5a, 0x6c, 0x0e,
	0x74, 0xc2, 0x8b, 0x00, 0xfd, 0x17, 0x64, 0xf2, 0x9a, 0x19, 0x37, 0xc4, 0xf1, 0x37, 0xdf, 0x92,
	0xb5, 0x15, 0x5c, 0x62, 0x4e, 0xd8, 0xfb, 0x5e, 0x86, 0xea, 0xaa, 0x50, 0xe8, 0x10, 0xb6, 0x7d,
	0x27, 0x7a, 0x49, 0x3c, 0x5b, 0x28, 0x96, 0xd6, 0xa7, 0xb0, 0xb6, 0x3e, 0x5b, 0xe9, 0xa6, 0x4e,
	0xba, 0xc7, 0x8a, 0xd1, 0x31, 0xa0, 0x19, 0x09, 0x3c, 0x1a, 0x4c, 0x96, 0x03, 0x49, 0x6b, 0x03,
	0xe9, 0xd9, 0xae, 0x45, 0xa4, 0x43, 0xd8, 0x76, 0x5c, 0x96, 0x38, 0xd3, 0xe5, 0x40, 0xf2, 0xfa,
	0x1b, 0xa5, 0x9b, 0x16, 0x71, 0x0c, 0x28, 0x79, 0x84, 0x39, 0x74, 0x1a, 0x8b, 0xf6, 0xd6, 0x70,
	0x6e, 0xa2, 0xcf, 0x40, 0x8d, 0x88, 0x13, 0x87, 0x81, 0x68, 0xf0, 0xea, 0x7e, 0xed, 0xbd, 0x7d,
	0xd4, 0xc4, 0x82, 0x87, 0x33, 0x3e, 0xfa, 0x37, 0x68, 0x8c, 0xf8, 0xb3, 0x30, 0x72, 0xa2, 0x4b,
	0x43, 0xad, 0x15, 0x1a, 0x65, 0xbc, 0x00, 0xea, 0x8f, 0x40, 0x4d, 0xf9, 0xa8, 0x02, 0xa5, 0x71,
	0xff, 0xab, 0xfe, 0xe0, 0x79, 0x5f, 0xff, 0x17, 0x2a, 0x83, 0xd2, 0x1f, 0xf4, 0x4d, 0xbd, 0x80,
	0x10, 0x54, 0xf1, 0xb8, 0x67, 0xda, 0xa7, 0xdd, 0x41, 0xaf, 0x65, 0x75, 0x07, 0x7d, 0x5d, 0xda,
	0x4b, 0x00, 0x16, 0x4d, 0x82, 0x74, 0x90, 0x93, 0x68, 0x2a, 0x0a, 0xa0, 0x61, 0xbe, 0x44, 0x7b,
	0x50, 0x8e, 0xc8, 0x19, 0x89, 0x22, 0x12, 0x09, 0x39, 0x35, 0x3c, 0xb7, 0xaf, 0xbc, 0x48, 0xf9,
	0x1a, 0x2f, 0xb2, 0xfe, 0x14, 0x14, 0x3e, 0x08, 0xde, 0xba, 0xe9, 0x97, 0x43, 0xf3, 0x48, 0x2f,
	0xa0, 0x12, 0xc8, 0x47, 0xdd, 0x43, 0x5d, 0xe2, 0x8b, 0x61, 0xff, 0x48, 0x97, 0xb9, 0xef, 0xb9,
	0x79, 0x70, 0xa2, 0x2b, 0xf5, 0xdf, 0x0a, 0x50, 0x1e, 0xf2, 0x09, 0x44, 0x02, 0xf6, 0xbe, 0xd9,
	0xd4, 0x00, 0x85, 0x5d, 0xce, 0xd2, 0xb1, 0x54, 0x9d, 0xbf, 0xb2, 0x7c, 0x57, 0xd3, 0xba, 0x9c,
	0x11, 0x2c, 0x18, 0x7c, 0x06, 0xbd, 0x72, 0xa6, 0x49, 0x3a, 0xa9, 0x36, 0x70, 0x6a, 0xa0, 0xfb,
	0x50, 0xf1, 0x5c, 0xf6, 0xd0, 0x16, 0x16, 0x2f, 0xa0, 0xdc, 0x90, 0x0e, 0x24, 0xbd, 0x80, 0x81,
	0xc3, 0xa7, 0x02, 0xcd, 0xdb, 0xbe, 0xb8, 0xa6, 0xed, 0xeb, 0x5f, 0x80, 0xc2, 0x0f, 0x5c, 0xcd,
	0x15, 0x40, 0x1d, 0x1d, 0xb7, 0xf6, 0x1f, 0x3f, 0xd1, 0x0b, 0x3c, 0xb7, 0xd1, 0x71, 0xeb, 0xd3,
	0x34, 0xdd, 0x93, 0xce, 0x63, 0x5d, 0x46, 0x1a, 0x14, 0x3b, 0x6d, 0xcb, 0x7e, 0xa8, 0x2b, 0xf5,
	0x43, 0xd8, 0x5c, 0x19, 0x0f, 0xe8, 0x31, 0x94, 0xf3, 0x51, 0x9e, 0x3d, 0x95, 0xdd, 0xb7, 0x0e,
	0xef, 0x64, 0x04, 0x3c, 0xa7, 0xd6, 0x7f, 0x2f, 0x80, 0x6c, 0x39, 0x13, 0x2e, 0x19, 0x73, 0x26,
	0x4b, 0x92, 0x31, 0x67, 0xd2, 0xf5, 0x10, 0x02, 0x45, 0x8c, 0x84, 0xb4, 0xc8, 0x62, 0x8d, 0xee,
	0x41, 0x25, 0x89, 0x9d, 0x09, 0xc9, 0x46, 0x8f, 0x2c, 0xf8, 0x20, 0xa0, 0x74, 0xf6, 0xac, 0x76,
	0x80, 0xfa, 0x01, 0x33, 0xb9, 0x74, 0xad, 0x99, 0x9c, 0x49, 0x5f, 0x5e, 0x27, 0xfd, 0x77, 0x12,
	0xa8, 0x43, 0xea, 0x66, 0x69, 0xbf, 0xab, 0x53, 0x16, 0x6a, 0x48, 0xef, 0x52, 0x43, 0x5e, 0x52,
	0xe3, 0x36, 0x94, 0x92, 0x98, 0x44, 0x9c, 0x5b, 0x4e, 0x87, 0x23, 0x37, 0xbb, 0xde, 0xc7, 0x56,
	0x41, 0x5b, 0xa7, 0xc2, 0x2f, 0x12, 0xc0, 0x90, 0xba, 0xed, 0xd0, 0xf7, 0xff, 0xe4, 0xcd, 0xdc,
	0x05, 0x70, 0x53, 0xc6, 0x42, 0x0d, 0x2d, 0x43, 0xba, 0x1e, 0xfa, 0x3f, 0x6c, 0xe7, 0xee, 0x99,
	0x13, 0x65, 0xac, 0xb4, 0x23, 0xb6, 0x32, 0xc7, 0x50, 0xe0, 0x5d, 0x6f, 0x59, 0x29, 0x65, 0x45,
	0x29, 0x04, 0x0a, 0xe3, 0x57, 0x2e, 0xa5, 0xb2, 0xf2, 0xf5, 0x15, 0xf5, 0x8a, 0x1f, 0xa0, 0x9e,
	0xfa, 0x8f, 0xf4, 0xd0, 0xcf, 0x12, 0x94, 0x86, 0xd4, 0x3d, 0x0d, 0x19, 0x79, 0x9f, 0x74, 0x4b,
	0xf9, 0x4a, 0x2b, 0xf9, 0xfe, 0x0f, 0x14, 0xfe, 0x2f, 0x99, 0x7d, 0x06, 0xdd, 0x58, 0xcc, 0x21,
	0x1e, 0xad, 0xc9, 0x7f, 0xb0, 0x20, 0x5c, 0x11, 0x41, 0xf9, 0x00, 0x11, 0x8a, 0x7f, 0x47, 0x04,
	0x75, 0x9d, 0x08, 0xfb, 0xa0, 0x08, 0x01, 0x56, 0x66, 0x98, 0x0a, 0xd2, 0x78, 0x98, 0xce, 0xaf,
	0x0e, 0x47, 0x24, 0xee, 0xee, 0x9b, 0x63, 0x0b, 0xb7, 0x7a, 0xba, 0x5c, 0xff, 0xb5, 0x08, 0xca,
	0x38, 0x26, 0xd1, 0xb2, 0x3c, 0x85, 0x15, 0x79, 0x76, 0x40, 0x8d, 0x89, 0x1b, 0x11, 0x26, 0x64,
	0xdb, 0xc0, 0x99, 0xc5, 0x87, 0x32, 0xe5, 0x83, 0x3a, 0x7b, 0x7e, 0xa9, 0xf1, 0xd1, 0x34, 0xfa,
	0x1c, 0x36, 0xa6, 0x4e, 0xcc, 0xec, 0x98, 0x90, 0xe0, 0x2f, 0xb6, 0x19, 0xe7, 0x8f, 0x08, 0x09,
	0xac, 0x18, 0x3d, 0x01, 0x70, 0x9d, 0x99, 0xf3, 0x82, 0x4e, 0x29, 0xbb, 0x34, 0x4a, 0x35, 0xb9,
	0x51, 0xdd, 0xdf, 0xc9, 0x1a, 0x81, 0xab, 0xd3, 0x6c, 0xcf, 0xbd, 0x78, 0x89, 0x89, 0xea, 0xb0,
	0x19, 0x90, 0xd7, 0xcc, 0x66, 0xe1, 0x4b, 0x12, 0x2c, 0x66, 0x4e, 0x85, 0x83, 0x16, 0xc7, 0xba,
	0x1e, 0x7a, 0x00, 0x20, 0x84, 0x15, 0x9c, 0x6c, 0x0e, 0xe8, 0x4b, 0xb1, 0x05, 0x0f, 0x6b, 0x49,
	0xbe, 0xcc, 0xcb, 0x0d, 0xeb, 0xca, 0xfd, 0x93, 0x04, 0xb0, 0xb8, 0xd7, 0x6a, 0xd5, 0xab, 0x00,
	0xc3, 0x6e, 0xdb, 0x6e, 0x63, 0xb3, 0x65, 0xf1, 0xaf, 0x8a, 0x0d, 0x28, 0x73, 0x1b, 0x9b, 0xad,
	0x8e, 0x2e, 0xa1, 0x4d, 0xd0, 0xb8, 0xd5, 0xed, 0x77, 0xcc, 0xaf, 0x75, 0x19, 0xdd, 0x80, 0x2d,
	0x6e, 0x8e, 0x06, 0x87, 0x96, 0xdd, 0x31, 0x7b, 0xa6, 0x65, 0xea, 0xc5, 0x1c, 0x3c, 0x6e, 0xe1,
	0x4e, 0x0e, 0xaa, 0xf9, 0xc6, 0xe1, 0x18, 0x1f, 0x99, 0x7a, 0x09, 0xdd, 0x81, 0xdb, 0xdc, 0x1c,
	0x0f, 0x3b, 0x2d, 0x8b, 0x7f, 0xb1, 0x98, 0xcf, 0xed, 0xf6, 0x60, 0xdc, 0xb7, 0x4c, 0xac, 0x97,
	0xf9, 0x87, 0x0c, 0x77, 0x5a, 0xad, 0xa3, 0xfc, 0x1a, 0x1a, 0xda, 0x01, 0x24, 0xae, 0x35, 0x38,
	0x39, 0x31, 0xfb, 0x56, 0x8e, 0x43, 0x7e, 0xd8, 0xe9, 0xc0, 0x32, 0x73, 0xb0, 0x82, 0xb6, 0xa0,
	0x32, 0x1e, 0x99, 0x38, 0x07, 0x14, 0xb4, 0x07, 0x3b, 0x02, 0xc8, 0xce, 0x6b, 0xb7, 0x86, 0xad,
	0x83, 0x6e, 0xaf, 0x6b, 0x7d, 0xa3, 0x6f, 0xf0, 0xd3, 0x84, 0x8f, 0x67, 0x68, 0x8f, 0xcc, 0xde,
	0xa1, 0xbe, 0x89, 0xb6, 0x61, 0x73, 0x81, 0xb5, 0x7a, 0x3d, 0xbd, 0x5a, 0xff, 0xb1, 0x00, 0xda,
	0x5c, 0x74, 0xb4, 0x0b, 0xe5, 0x79, 0xe5, 0xd2, 0xa6, 0x2f, 0xb1, 0xac, 0x6a, 0xab, 0x7d, 0x2c,
	0x5d, 0xa7, 0x8f, 0xaf, 0xb6, 0xa2, 0x7c, 0x9d, 0x56, 0x3c, 0x28, 0x7f, 0xab, 0xc6, 0xee, 0x39,
	0xf1, 0x9d, 0x17, 0xaa, 0x60, 0x3e, 0xfa, 0x23, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x31, 0x5f, 0xbc,
	0x53, 0x0e, 0x00, 0x00,
}
