// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pixur.proto

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pic_DeletionStatus_Reason int32

const (
	// The reason is not know, due to limitations of proto
	Pic_DeletionStatus_UNKNOWN Pic_DeletionStatus_Reason = 0
	// No specific reason.  This is a catch-all reason.
	Pic_DeletionStatus_NONE Pic_DeletionStatus_Reason = 1
	// The pic is in violation of the rules.
	Pic_DeletionStatus_RULE_VIOLATION Pic_DeletionStatus_Reason = 2
)

var Pic_DeletionStatus_Reason_name = map[int32]string{
	0: "UNKNOWN",
	1: "NONE",
	2: "RULE_VIOLATION",
}

var Pic_DeletionStatus_Reason_value = map[string]int32{
	"UNKNOWN":        0,
	"NONE":           1,
	"RULE_VIOLATION": 2,
}

func (x Pic_DeletionStatus_Reason) String() string {
	return proto.EnumName(Pic_DeletionStatus_Reason_name, int32(x))
}

func (Pic_DeletionStatus_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{0, 0, 0}
}

type Pic_File_Mime int32

const (
	Pic_File_UNKNOWN Pic_File_Mime = 0
	Pic_File_JPEG    Pic_File_Mime = 1
	Pic_File_GIF     Pic_File_Mime = 2
	Pic_File_PNG     Pic_File_Mime = 3
	Pic_File_WEBM    Pic_File_Mime = 4
)

var Pic_File_Mime_name = map[int32]string{
	0: "UNKNOWN",
	1: "JPEG",
	2: "GIF",
	3: "PNG",
	4: "WEBM",
}

var Pic_File_Mime_value = map[string]int32{
	"UNKNOWN": 0,
	"JPEG":    1,
	"GIF":     2,
	"PNG":     3,
	"WEBM":    4,
}

func (x Pic_File_Mime) String() string {
	return proto.EnumName(Pic_File_Mime_name, int32(x))
}

func (Pic_File_Mime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{0, 3, 0}
}

type PicIdent_Type int32

const (
	PicIdent_UNKNOWN    PicIdent_Type = 0
	PicIdent_SHA1       PicIdent_Type = 2
	PicIdent_MD5        PicIdent_Type = 3
	PicIdent_DCT_0      PicIdent_Type = 4
	PicIdent_SHA512_256 PicIdent_Type = 5
)

var PicIdent_Type_name = map[int32]string{
	0: "UNKNOWN",
	2: "SHA1",
	3: "MD5",
	4: "DCT_0",
	5: "SHA512_256",
}

var PicIdent_Type_value = map[string]int32{
	"UNKNOWN":    0,
	"SHA1":       2,
	"MD5":        3,
	"DCT_0":      4,
	"SHA512_256": 5,
}

func (x PicIdent_Type) String() string {
	return proto.EnumName(PicIdent_Type_name, int32(x))
}

func (PicIdent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{1, 0}
}

type PicVote_Vote int32

const (
	PicVote_UNKNOWN PicVote_Vote = 0
	PicVote_UP      PicVote_Vote = 1
	PicVote_DOWN    PicVote_Vote = 2
	PicVote_NEUTRAL PicVote_Vote = 3
)

var PicVote_Vote_name = map[int32]string{
	0: "UNKNOWN",
	1: "UP",
	2: "DOWN",
	3: "NEUTRAL",
}

var PicVote_Vote_value = map[string]int32{
	"UNKNOWN": 0,
	"UP":      1,
	"DOWN":    2,
	"NEUTRAL": 3,
}

func (x PicVote_Vote) String() string {
	return proto.EnumName(PicVote_Vote_name, int32(x))
}

func (PicVote_Vote) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{6, 0}
}

type User_Capability int32

const (
	User_UNKNOWN User_Capability = 0
	// Can this user create and upload pictures
	User_PIC_CREATE User_Capability = 1
	// Can this user view the actual image data (grants pic token)
	User_PIC_READ User_Capability = 2
	// Can this user perform general pic index queries?
	User_PIC_INDEX User_Capability = 3
	// Can this user soft delete a pic?
	User_PIC_SOFT_DELETE User_Capability = 5
	// Can this user hard delete a pic?
	User_PIC_HARD_DELETE User_Capability = 6
	// Can this user purge a pic?
	User_PIC_PURGE User_Capability = 7
	// Can this user increment the pic view counter?
	User_PIC_UPDATE_VIEW_COUNTER User_Capability = 8
	// Can this user add tags and pic tags?
	User_PIC_TAG_CREATE User_Capability = 9
	// Can this user create comments?
	User_PIC_COMMENT_CREATE User_Capability = 10
	// Can this user vote?
	User_PIC_VOTE_CREATE User_Capability = 11
	// Can this user create other users?
	User_USER_CREATE User_Capability = 4
	// Can this user modify capabilities?
	User_USER_UPDATE_CAPABILITY User_Capability = 12
	// Can this user read information about themselves?
	User_USER_READ_SELF User_Capability = 13
	// Can this user read infortmation about others?
	User_USER_READ_ALL User_Capability = 14
	// Can this user create arbitrary extension data on a pic?
	User_PIC_EXTENSION_CREATE User_Capability = 15
	// Can this user read arbitrary extension data on a pic?
	User_PIC_EXTENSION_READ User_Capability = 16
	// Can this user create arbitrary extension data on a comment?
	User_PIC_COMMENT_EXTENSION_CREATE User_Capability = 17
	// Can this user read arbitrary extension data on a comment?
	User_PIC_COMMENT_EXTENSION_READ User_Capability = 18
	// Can this user create arbitrary extension data on a pic tag?
	User_PIC_TAG_EXTENSION_CREATE User_Capability = 19
	// Can this user read arbitrary extension data on a pic tag?
	User_PIC_TAG_EXTENSION_READ User_Capability = 20
	// Can this user create arbitrary extension data on a pic vote?
	User_PIC_VOTE_EXTENSION_CREATE User_Capability = 21
	// Can this user read arbitrary extension data on a pic vote?
	User_PIC_VOTE_EXTENSION_READ User_Capability = 22
)

var User_Capability_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "PIC_CREATE",
	2:  "PIC_READ",
	3:  "PIC_INDEX",
	5:  "PIC_SOFT_DELETE",
	6:  "PIC_HARD_DELETE",
	7:  "PIC_PURGE",
	8:  "PIC_UPDATE_VIEW_COUNTER",
	9:  "PIC_TAG_CREATE",
	10: "PIC_COMMENT_CREATE",
	11: "PIC_VOTE_CREATE",
	4:  "USER_CREATE",
	12: "USER_UPDATE_CAPABILITY",
	13: "USER_READ_SELF",
	14: "USER_READ_ALL",
	15: "PIC_EXTENSION_CREATE",
	16: "PIC_EXTENSION_READ",
	17: "PIC_COMMENT_EXTENSION_CREATE",
	18: "PIC_COMMENT_EXTENSION_READ",
	19: "PIC_TAG_EXTENSION_CREATE",
	20: "PIC_TAG_EXTENSION_READ",
	21: "PIC_VOTE_EXTENSION_CREATE",
	22: "PIC_VOTE_EXTENSION_READ",
}

var User_Capability_value = map[string]int32{
	"UNKNOWN":                      0,
	"PIC_CREATE":                   1,
	"PIC_READ":                     2,
	"PIC_INDEX":                    3,
	"PIC_SOFT_DELETE":              5,
	"PIC_HARD_DELETE":              6,
	"PIC_PURGE":                    7,
	"PIC_UPDATE_VIEW_COUNTER":      8,
	"PIC_TAG_CREATE":               9,
	"PIC_COMMENT_CREATE":           10,
	"PIC_VOTE_CREATE":              11,
	"USER_CREATE":                  4,
	"USER_UPDATE_CAPABILITY":       12,
	"USER_READ_SELF":               13,
	"USER_READ_ALL":                14,
	"PIC_EXTENSION_CREATE":         15,
	"PIC_EXTENSION_READ":           16,
	"PIC_COMMENT_EXTENSION_CREATE": 17,
	"PIC_COMMENT_EXTENSION_READ":   18,
	"PIC_TAG_EXTENSION_CREATE":     19,
	"PIC_TAG_EXTENSION_READ":       20,
	"PIC_VOTE_EXTENSION_CREATE":    21,
	"PIC_VOTE_EXTENSION_READ":      22,
}

func (x User_Capability) String() string {
	return proto.EnumName(User_Capability_name, int32(x))
}

func (User_Capability) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{8, 0}
}

type Pic struct {
	PicId      int64                `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	File       *Pic_File            `protobuf:"bytes,22,opt,name=file,proto3" json:"file,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,11,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// If present, the pic is on the path to removal.  When the pic is marked
	// for deletion, it is delisted from normal indexing operations.  When the
	// pic is actually "deleted" only the pic object is removed.
	DeletionStatus *Pic_DeletionStatus `protobuf:"bytes,12,opt,name=deletion_status,json=deletionStatus,proto3" json:"deletion_status,omitempty"`
	ViewCount      int64               `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Source         []*Pic_FileSource   `protobuf:"bytes,15,rep,name=source,proto3" json:"source,omitempty"`
	// The denormalized sum of upvotes for this pic
	VoteUp int64 `protobuf:"varint,17,opt,name=vote_up,json=voteUp,proto3" json:"vote_up,omitempty"`
	// The denormalized sum of downvotes for this pic
	VoteDown int64 `protobuf:"varint,18,opt,name=vote_down,json=voteDown,proto3" json:"vote_down,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,19,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Thumbnail            []*Pic_File         `protobuf:"bytes,21,rep,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Pic) Reset()         { *m = Pic{} }
func (m *Pic) String() string { return proto.CompactTextString(m) }
func (*Pic) ProtoMessage()    {}
func (*Pic) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{0}
}

func (m *Pic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic.Unmarshal(m, b)
}
func (m *Pic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic.Marshal(b, m, deterministic)
}
func (m *Pic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic.Merge(m, src)
}
func (m *Pic) XXX_Size() int {
	return xxx_messageInfo_Pic.Size(m)
}
func (m *Pic) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic.DiscardUnknown(m)
}

var xxx_messageInfo_Pic proto.InternalMessageInfo

func (m *Pic) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *Pic) GetFile() *Pic_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Pic) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *Pic) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *Pic) GetDeletionStatus() *Pic_DeletionStatus {
	if m != nil {
		return m.DeletionStatus
	}
	return nil
}

func (m *Pic) GetViewCount() int64 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *Pic) GetSource() []*Pic_FileSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Pic) GetVoteUp() int64 {
	if m != nil {
		return m.VoteUp
	}
	return 0
}

func (m *Pic) GetVoteDown() int64 {
	if m != nil {
		return m.VoteDown
	}
	return 0
}

func (m *Pic) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *Pic) GetThumbnail() []*Pic_File {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

type Pic_DeletionStatus struct {
	// Represents when this Pic was marked for deletion
	MarkedDeletedTs *timestamp.Timestamp `protobuf:"bytes,1,opt,name=marked_deleted_ts,json=markedDeletedTs,proto3" json:"marked_deleted_ts,omitempty"`
	// Represents when this picture will be auto deleted.  Note that the Pic
	// may exist for a short period after this time.  (may be absent)
	PendingDeletedTs *timestamp.Timestamp `protobuf:"bytes,2,opt,name=pending_deleted_ts,json=pendingDeletedTs,proto3" json:"pending_deleted_ts,omitempty"`
	// Determines when Pic was actually deleted.  (present after the Pic is
	// hard deleted, a.k.a purging)
	ActualDeletedTs *timestamp.Timestamp `protobuf:"bytes,3,opt,name=actual_deleted_ts,json=actualDeletedTs,proto3" json:"actual_deleted_ts,omitempty"`
	// Gives an explanation for why this pic was removed.
	Details string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	// The reason the pic was removed.
	Reason Pic_DeletionStatus_Reason `protobuf:"varint,5,opt,name=reason,proto3,enum=pixur.Pic_DeletionStatus_Reason" json:"reason,omitempty"`
	// Determines if this pic can be undeleted if re uploaded.  Currently the
	// only reason is due to disk space concerns.
	Temporary            bool     `protobuf:"varint,6,opt,name=temporary,proto3" json:"temporary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pic_DeletionStatus) Reset()         { *m = Pic_DeletionStatus{} }
func (m *Pic_DeletionStatus) String() string { return proto.CompactTextString(m) }
func (*Pic_DeletionStatus) ProtoMessage()    {}
func (*Pic_DeletionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{0, 0}
}

func (m *Pic_DeletionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic_DeletionStatus.Unmarshal(m, b)
}
func (m *Pic_DeletionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic_DeletionStatus.Marshal(b, m, deterministic)
}
func (m *Pic_DeletionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic_DeletionStatus.Merge(m, src)
}
func (m *Pic_DeletionStatus) XXX_Size() int {
	return xxx_messageInfo_Pic_DeletionStatus.Size(m)
}
func (m *Pic_DeletionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic_DeletionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Pic_DeletionStatus proto.InternalMessageInfo

func (m *Pic_DeletionStatus) GetMarkedDeletedTs() *timestamp.Timestamp {
	if m != nil {
		return m.MarkedDeletedTs
	}
	return nil
}

func (m *Pic_DeletionStatus) GetPendingDeletedTs() *timestamp.Timestamp {
	if m != nil {
		return m.PendingDeletedTs
	}
	return nil
}

func (m *Pic_DeletionStatus) GetActualDeletedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ActualDeletedTs
	}
	return nil
}

func (m *Pic_DeletionStatus) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Pic_DeletionStatus) GetReason() Pic_DeletionStatus_Reason {
	if m != nil {
		return m.Reason
	}
	return Pic_DeletionStatus_UNKNOWN
}

func (m *Pic_DeletionStatus) GetTemporary() bool {
	if m != nil {
		return m.Temporary
	}
	return false
}

type Pic_FileSource struct {
	// url is optional and is the location the pic came from.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// referrer is optional and is what website the pic was linked to from.
	Referrer string `protobuf:"bytes,2,opt,name=referrer,proto3" json:"referrer,omitempty"`
	// created_ts is the time the file source was added.
	CreatedTs *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	// If present, there is only one file_source per user_id.
	UserId int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// name is optional and the file name for this source.  It may be derived
	// from the url, from the content-disposition, or from the user who
	// upload the file.
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pic_FileSource) Reset()         { *m = Pic_FileSource{} }
func (m *Pic_FileSource) String() string { return proto.CompactTextString(m) }
func (*Pic_FileSource) ProtoMessage()    {}
func (*Pic_FileSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{0, 1}
}

func (m *Pic_FileSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic_FileSource.Unmarshal(m, b)
}
func (m *Pic_FileSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic_FileSource.Marshal(b, m, deterministic)
}
func (m *Pic_FileSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic_FileSource.Merge(m, src)
}
func (m *Pic_FileSource) XXX_Size() int {
	return xxx_messageInfo_Pic_FileSource.Size(m)
}
func (m *Pic_FileSource) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic_FileSource.DiscardUnknown(m)
}

var xxx_messageInfo_Pic_FileSource proto.InternalMessageInfo

func (m *Pic_FileSource) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Pic_FileSource) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

func (m *Pic_FileSource) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *Pic_FileSource) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Pic_FileSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Pic_File struct {
	Index      int64                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size       int64                `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mime       Pic_File_Mime        `protobuf:"varint,3,opt,name=mime,proto3,enum=pixur.Pic_File_Mime" json:"mime,omitempty"`
	Width      int64                `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height     int64                `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Only present on animated images.
	AnimationInfo        *AnimationInfo `protobuf:"bytes,8,opt,name=animation_info,json=animationInfo,proto3" json:"animation_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Pic_File) Reset()         { *m = Pic_File{} }
func (m *Pic_File) String() string { return proto.CompactTextString(m) }
func (*Pic_File) ProtoMessage()    {}
func (*Pic_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{0, 3}
}

func (m *Pic_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pic_File.Unmarshal(m, b)
}
func (m *Pic_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pic_File.Marshal(b, m, deterministic)
}
func (m *Pic_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pic_File.Merge(m, src)
}
func (m *Pic_File) XXX_Size() int {
	return xxx_messageInfo_Pic_File.Size(m)
}
func (m *Pic_File) XXX_DiscardUnknown() {
	xxx_messageInfo_Pic_File.DiscardUnknown(m)
}

var xxx_messageInfo_Pic_File proto.InternalMessageInfo

func (m *Pic_File) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Pic_File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pic_File) GetMime() Pic_File_Mime {
	if m != nil {
		return m.Mime
	}
	return Pic_File_UNKNOWN
}

func (m *Pic_File) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Pic_File) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Pic_File) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *Pic_File) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *Pic_File) GetAnimationInfo() *AnimationInfo {
	if m != nil {
		return m.AnimationInfo
	}
	return nil
}

// A picture identifier
type PicIdent struct {
	PicId int64         `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	Type  PicIdent_Type `protobuf:"varint,2,opt,name=type,proto3,enum=pixur.PicIdent_Type" json:"type,omitempty"`
	Value []byte        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// dct0 are the upper 8x8 corner of the 32x32 dct of the image
	Dct0Values []float32 `protobuf:"fixed32,4,rep,packed,name=dct0_values,json=dct0Values,proto3" json:"dct0_values,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,5,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PicIdent) Reset()         { *m = PicIdent{} }
func (m *PicIdent) String() string { return proto.CompactTextString(m) }
func (*PicIdent) ProtoMessage()    {}
func (*PicIdent) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{1}
}

func (m *PicIdent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicIdent.Unmarshal(m, b)
}
func (m *PicIdent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicIdent.Marshal(b, m, deterministic)
}
func (m *PicIdent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicIdent.Merge(m, src)
}
func (m *PicIdent) XXX_Size() int {
	return xxx_messageInfo_PicIdent.Size(m)
}
func (m *PicIdent) XXX_DiscardUnknown() {
	xxx_messageInfo_PicIdent.DiscardUnknown(m)
}

var xxx_messageInfo_PicIdent proto.InternalMessageInfo

func (m *PicIdent) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicIdent) GetType() PicIdent_Type {
	if m != nil {
		return m.Type
	}
	return PicIdent_UNKNOWN
}

func (m *PicIdent) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PicIdent) GetDct0Values() []float32 {
	if m != nil {
		return m.Dct0Values
	}
	return nil
}

func (m *PicIdent) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type AnimationInfo struct {
	// How long this animated image in time.  There must be more than 1 frame
	// for this value to be set.
	Duration             *duration.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AnimationInfo) Reset()         { *m = AnimationInfo{} }
func (m *AnimationInfo) String() string { return proto.CompactTextString(m) }
func (*AnimationInfo) ProtoMessage()    {}
func (*AnimationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{2}
}

func (m *AnimationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimationInfo.Unmarshal(m, b)
}
func (m *AnimationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimationInfo.Marshal(b, m, deterministic)
}
func (m *AnimationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimationInfo.Merge(m, src)
}
func (m *AnimationInfo) XXX_Size() int {
	return xxx_messageInfo_AnimationInfo.Size(m)
}
func (m *AnimationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AnimationInfo proto.InternalMessageInfo

func (m *AnimationInfo) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type Tag struct {
	TagId      int64                `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name       string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UsageCount int64                `protobuf:"varint,3,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,8,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{3}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetUsageCount() int64 {
	if m != nil {
		return m.UsageCount
	}
	return 0
}

func (m *Tag) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *Tag) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *Tag) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PicTag struct {
	PicId int64  `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	TagId int64  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The user who originally created this tag.  optional.
	UserId     int64                `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,9,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PicTag) Reset()         { *m = PicTag{} }
func (m *PicTag) String() string { return proto.CompactTextString(m) }
func (*PicTag) ProtoMessage()    {}
func (*PicTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{4}
}

func (m *PicTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicTag.Unmarshal(m, b)
}
func (m *PicTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicTag.Marshal(b, m, deterministic)
}
func (m *PicTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicTag.Merge(m, src)
}
func (m *PicTag) XXX_Size() int {
	return xxx_messageInfo_PicTag.Size(m)
}
func (m *PicTag) XXX_DiscardUnknown() {
	xxx_messageInfo_PicTag.DiscardUnknown(m)
}

var xxx_messageInfo_PicTag proto.InternalMessageInfo

func (m *PicTag) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicTag) GetTagId() int64 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *PicTag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PicTag) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicTag) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *PicTag) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *PicTag) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PicComment struct {
	PicId     int64 `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	CommentId int64 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	// parent id of this comment.  0 if root.
	CommentParentId int64 `protobuf:"varint,3,opt,name=comment_parent_id,json=commentParentId,proto3" json:"comment_parent_id,omitempty"`
	// author
	UserId     int64                `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text       string               `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,6,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,8,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PicComment) Reset()         { *m = PicComment{} }
func (m *PicComment) String() string { return proto.CompactTextString(m) }
func (*PicComment) ProtoMessage()    {}
func (*PicComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{5}
}

func (m *PicComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicComment.Unmarshal(m, b)
}
func (m *PicComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicComment.Marshal(b, m, deterministic)
}
func (m *PicComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicComment.Merge(m, src)
}
func (m *PicComment) XXX_Size() int {
	return xxx_messageInfo_PicComment.Size(m)
}
func (m *PicComment) XXX_DiscardUnknown() {
	xxx_messageInfo_PicComment.DiscardUnknown(m)
}

var xxx_messageInfo_PicComment proto.InternalMessageInfo

func (m *PicComment) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicComment) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *PicComment) GetCommentParentId() int64 {
	if m != nil {
		return m.CommentParentId
	}
	return 0
}

func (m *PicComment) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicComment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PicComment) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *PicComment) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *PicComment) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type PicVote struct {
	PicId  int64 `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Index is a tie breaker for anonymous votes.  It is always 0 if user_id is not 0.  It is
	// always positive.
	Index      int64                `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	Vote       PicVote_Vote         `protobuf:"varint,3,opt,name=vote,proto3,enum=pixur.PicVote_Vote" json:"vote,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,5,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,6,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PicVote) Reset()         { *m = PicVote{} }
func (m *PicVote) String() string { return proto.CompactTextString(m) }
func (*PicVote) ProtoMessage()    {}
func (*PicVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{6}
}

func (m *PicVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicVote.Unmarshal(m, b)
}
func (m *PicVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicVote.Marshal(b, m, deterministic)
}
func (m *PicVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicVote.Merge(m, src)
}
func (m *PicVote) XXX_Size() int {
	return xxx_messageInfo_PicVote.Size(m)
}
func (m *PicVote) XXX_DiscardUnknown() {
	xxx_messageInfo_PicVote.DiscardUnknown(m)
}

var xxx_messageInfo_PicVote proto.InternalMessageInfo

func (m *PicVote) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

func (m *PicVote) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PicVote) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PicVote) GetVote() PicVote_Vote {
	if m != nil {
		return m.Vote
	}
	return PicVote_UNKNOWN
}

func (m *PicVote) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *PicVote) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *PicVote) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type UserEvent struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// If multiple events are being created for a single pic, this acts as a tie breaker.
	Index int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Indexed and can't change
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,4,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	// Types that are valid to be assigned to Evt:
	//	*UserEvent_OutgoingUpsertPicVote_
	//	*UserEvent_IncomingUpsertPicVote_
	//	*UserEvent_OutgoingPicComment_
	//	*UserEvent_IncomingPicComment_
	Evt                  isUserEvent_Evt `protobuf_oneof:"evt"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserEvent) Reset()         { *m = UserEvent{} }
func (m *UserEvent) String() string { return proto.CompactTextString(m) }
func (*UserEvent) ProtoMessage()    {}
func (*UserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{7}
}

func (m *UserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvent.Unmarshal(m, b)
}
func (m *UserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvent.Marshal(b, m, deterministic)
}
func (m *UserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvent.Merge(m, src)
}
func (m *UserEvent) XXX_Size() int {
	return xxx_messageInfo_UserEvent.Size(m)
}
func (m *UserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvent proto.InternalMessageInfo

func (m *UserEvent) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserEvent) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *UserEvent) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *UserEvent) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

type isUserEvent_Evt interface {
	isUserEvent_Evt()
}

type UserEvent_OutgoingUpsertPicVote_ struct {
	OutgoingUpsertPicVote *UserEvent_OutgoingUpsertPicVote `protobuf:"bytes,5,opt,name=outgoing_upsert_pic_vote,json=outgoingUpsertPicVote,proto3,oneof"`
}

type UserEvent_IncomingUpsertPicVote_ struct {
	IncomingUpsertPicVote *UserEvent_IncomingUpsertPicVote `protobuf:"bytes,6,opt,name=incoming_upsert_pic_vote,json=incomingUpsertPicVote,proto3,oneof"`
}

type UserEvent_OutgoingPicComment_ struct {
	OutgoingPicComment *UserEvent_OutgoingPicComment `protobuf:"bytes,7,opt,name=outgoing_pic_comment,json=outgoingPicComment,proto3,oneof"`
}

type UserEvent_IncomingPicComment_ struct {
	IncomingPicComment *UserEvent_IncomingPicComment `protobuf:"bytes,8,opt,name=incoming_pic_comment,json=incomingPicComment,proto3,oneof"`
}

func (*UserEvent_OutgoingUpsertPicVote_) isUserEvent_Evt() {}

func (*UserEvent_IncomingUpsertPicVote_) isUserEvent_Evt() {}

func (*UserEvent_OutgoingPicComment_) isUserEvent_Evt() {}

func (*UserEvent_IncomingPicComment_) isUserEvent_Evt() {}

func (m *UserEvent) GetEvt() isUserEvent_Evt {
	if m != nil {
		return m.Evt
	}
	return nil
}

func (m *UserEvent) GetOutgoingUpsertPicVote() *UserEvent_OutgoingUpsertPicVote {
	if x, ok := m.GetEvt().(*UserEvent_OutgoingUpsertPicVote_); ok {
		return x.OutgoingUpsertPicVote
	}
	return nil
}

func (m *UserEvent) GetIncomingUpsertPicVote() *UserEvent_IncomingUpsertPicVote {
	if x, ok := m.GetEvt().(*UserEvent_IncomingUpsertPicVote_); ok {
		return x.IncomingUpsertPicVote
	}
	return nil
}

func (m *UserEvent) GetOutgoingPicComment() *UserEvent_OutgoingPicComment {
	if x, ok := m.GetEvt().(*UserEvent_OutgoingPicComment_); ok {
		return x.OutgoingPicComment
	}
	return nil
}

func (m *UserEvent) GetIncomingPicComment() *UserEvent_IncomingPicComment {
	if x, ok := m.GetEvt().(*UserEvent_IncomingPicComment_); ok {
		return x.IncomingPicComment
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserEvent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserEvent_OneofMarshaler, _UserEvent_OneofUnmarshaler, _UserEvent_OneofSizer, []interface{}{
		(*UserEvent_OutgoingUpsertPicVote_)(nil),
		(*UserEvent_IncomingUpsertPicVote_)(nil),
		(*UserEvent_OutgoingPicComment_)(nil),
		(*UserEvent_IncomingPicComment_)(nil),
	}
}

func _UserEvent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserEvent)
	// evt
	switch x := m.Evt.(type) {
	case *UserEvent_OutgoingUpsertPicVote_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OutgoingUpsertPicVote); err != nil {
			return err
		}
	case *UserEvent_IncomingUpsertPicVote_:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IncomingUpsertPicVote); err != nil {
			return err
		}
	case *UserEvent_OutgoingPicComment_:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OutgoingPicComment); err != nil {
			return err
		}
	case *UserEvent_IncomingPicComment_:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IncomingPicComment); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UserEvent.Evt has unexpected type %T", x)
	}
	return nil
}

func _UserEvent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserEvent)
	switch tag {
	case 5: // evt.outgoing_upsert_pic_vote
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEvent_OutgoingUpsertPicVote)
		err := b.DecodeMessage(msg)
		m.Evt = &UserEvent_OutgoingUpsertPicVote_{msg}
		return true, err
	case 6: // evt.incoming_upsert_pic_vote
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEvent_IncomingUpsertPicVote)
		err := b.DecodeMessage(msg)
		m.Evt = &UserEvent_IncomingUpsertPicVote_{msg}
		return true, err
	case 7: // evt.outgoing_pic_comment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEvent_OutgoingPicComment)
		err := b.DecodeMessage(msg)
		m.Evt = &UserEvent_OutgoingPicComment_{msg}
		return true, err
	case 8: // evt.incoming_pic_comment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEvent_IncomingPicComment)
		err := b.DecodeMessage(msg)
		m.Evt = &UserEvent_IncomingPicComment_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UserEvent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserEvent)
	// evt
	switch x := m.Evt.(type) {
	case *UserEvent_OutgoingUpsertPicVote_:
		s := proto.Size(x.OutgoingUpsertPicVote)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEvent_IncomingUpsertPicVote_:
		s := proto.Size(x.IncomingUpsertPicVote)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEvent_OutgoingPicComment_:
		s := proto.Size(x.OutgoingPicComment)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEvent_IncomingPicComment_:
		s := proto.Size(x.IncomingPicComment)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// IncomingUpsertPicVote represents sending a vote on a pic another user made.  If a user
// self-votes, OutgoingUpsertPicVote will be created instead of IncomingUpsertPicVote.
type UserEvent_OutgoingUpsertPicVote struct {
	PicId                int64    `protobuf:"varint,1,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEvent_OutgoingUpsertPicVote) Reset()         { *m = UserEvent_OutgoingUpsertPicVote{} }
func (m *UserEvent_OutgoingUpsertPicVote) String() string { return proto.CompactTextString(m) }
func (*UserEvent_OutgoingUpsertPicVote) ProtoMessage()    {}
func (*UserEvent_OutgoingUpsertPicVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{7, 0}
}

func (m *UserEvent_OutgoingUpsertPicVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvent_OutgoingUpsertPicVote.Unmarshal(m, b)
}
func (m *UserEvent_OutgoingUpsertPicVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvent_OutgoingUpsertPicVote.Marshal(b, m, deterministic)
}
func (m *UserEvent_OutgoingUpsertPicVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvent_OutgoingUpsertPicVote.Merge(m, src)
}
func (m *UserEvent_OutgoingUpsertPicVote) XXX_Size() int {
	return xxx_messageInfo_UserEvent_OutgoingUpsertPicVote.Size(m)
}
func (m *UserEvent_OutgoingUpsertPicVote) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvent_OutgoingUpsertPicVote.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvent_OutgoingUpsertPicVote proto.InternalMessageInfo

func (m *UserEvent_OutgoingUpsertPicVote) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

// IncomingUpsertPicVote represents receiving a vote on a pic they made.  If a user
// self-votes, OutgoingUpsertPicVote will be created instead of IncomingUpsertPicVote.
type UserEvent_IncomingUpsertPicVote struct {
	// The user who made the vote
	SubjectUserId        int64    `protobuf:"varint,1,opt,name=subject_user_id,json=subjectUserId,proto3" json:"subject_user_id,omitempty"`
	PicId                int64    `protobuf:"varint,2,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEvent_IncomingUpsertPicVote) Reset()         { *m = UserEvent_IncomingUpsertPicVote{} }
func (m *UserEvent_IncomingUpsertPicVote) String() string { return proto.CompactTextString(m) }
func (*UserEvent_IncomingUpsertPicVote) ProtoMessage()    {}
func (*UserEvent_IncomingUpsertPicVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{7, 1}
}

func (m *UserEvent_IncomingUpsertPicVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvent_IncomingUpsertPicVote.Unmarshal(m, b)
}
func (m *UserEvent_IncomingUpsertPicVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvent_IncomingUpsertPicVote.Marshal(b, m, deterministic)
}
func (m *UserEvent_IncomingUpsertPicVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvent_IncomingUpsertPicVote.Merge(m, src)
}
func (m *UserEvent_IncomingUpsertPicVote) XXX_Size() int {
	return xxx_messageInfo_UserEvent_IncomingUpsertPicVote.Size(m)
}
func (m *UserEvent_IncomingUpsertPicVote) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvent_IncomingUpsertPicVote.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvent_IncomingUpsertPicVote proto.InternalMessageInfo

func (m *UserEvent_IncomingUpsertPicVote) GetSubjectUserId() int64 {
	if m != nil {
		return m.SubjectUserId
	}
	return 0
}

func (m *UserEvent_IncomingUpsertPicVote) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

// OutgoingPicComment represents commenting on someone else's pic.  If a user comments on
// their own pic, OutgoingPicComment will be used instead of IncomingPicComment.
type UserEvent_OutgoingPicComment struct {
	// comment_id is the comment that this user created.
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	PicId                int64    `protobuf:"varint,2,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEvent_OutgoingPicComment) Reset()         { *m = UserEvent_OutgoingPicComment{} }
func (m *UserEvent_OutgoingPicComment) String() string { return proto.CompactTextString(m) }
func (*UserEvent_OutgoingPicComment) ProtoMessage()    {}
func (*UserEvent_OutgoingPicComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{7, 2}
}

func (m *UserEvent_OutgoingPicComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvent_OutgoingPicComment.Unmarshal(m, b)
}
func (m *UserEvent_OutgoingPicComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvent_OutgoingPicComment.Marshal(b, m, deterministic)
}
func (m *UserEvent_OutgoingPicComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvent_OutgoingPicComment.Merge(m, src)
}
func (m *UserEvent_OutgoingPicComment) XXX_Size() int {
	return xxx_messageInfo_UserEvent_OutgoingPicComment.Size(m)
}
func (m *UserEvent_OutgoingPicComment) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvent_OutgoingPicComment.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvent_OutgoingPicComment proto.InternalMessageInfo

func (m *UserEvent_OutgoingPicComment) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *UserEvent_OutgoingPicComment) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

// IncomingPicComment represents commenting on someone else's pic.  If a user comments on
// their own pic, OutgoingPicComment will be used instead of IncomingPicComment.
type UserEvent_IncomingPicComment struct {
	// comment_id is the newly created child comment, **not** the one owned by user_id.  The
	// comment_parent_id of the given comment must be owned by user_id.
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	PicId                int64    `protobuf:"varint,2,opt,name=pic_id,json=picId,proto3" json:"pic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEvent_IncomingPicComment) Reset()         { *m = UserEvent_IncomingPicComment{} }
func (m *UserEvent_IncomingPicComment) String() string { return proto.CompactTextString(m) }
func (*UserEvent_IncomingPicComment) ProtoMessage()    {}
func (*UserEvent_IncomingPicComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{7, 3}
}

func (m *UserEvent_IncomingPicComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvent_IncomingPicComment.Unmarshal(m, b)
}
func (m *UserEvent_IncomingPicComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvent_IncomingPicComment.Marshal(b, m, deterministic)
}
func (m *UserEvent_IncomingPicComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvent_IncomingPicComment.Merge(m, src)
}
func (m *UserEvent_IncomingPicComment) XXX_Size() int {
	return xxx_messageInfo_UserEvent_IncomingPicComment.Size(m)
}
func (m *UserEvent_IncomingPicComment) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvent_IncomingPicComment.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvent_IncomingPicComment proto.InternalMessageInfo

func (m *UserEvent_IncomingPicComment) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *UserEvent_IncomingPicComment) GetPicId() int64 {
	if m != nil {
		return m.PicId
	}
	return 0
}

type User struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Hashed secret token
	Secret []byte `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// Identity of the user, usually an email.
	Ident      string               `protobuf:"bytes,3,opt,name=ident,proto3" json:"ident,omitempty"`
	CreatedTs  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs *timestamp.Timestamp `protobuf:"bytes,5,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	LastSeenTs *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_seen_ts,json=lastSeenTs,proto3" json:"last_seen_ts,omitempty"`
	Capability []User_Capability    `protobuf:"varint,7,rep,packed,name=capability,proto3,enum=pixur.User_Capability" json:"capability,omitempty"`
	// Always increment-then-get
	NextTokenId int64        `protobuf:"varint,8,opt,name=next_token_id,json=nextTokenId,proto3" json:"next_token_id,omitempty"`
	UserToken   []*UserToken `protobuf:"bytes,9,rep,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	// Extra information that may not fit into the schema
	Ext                  map[string]*any.Any `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *User) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *User) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *User) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *User) GetLastSeenTs() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenTs
	}
	return nil
}

func (m *User) GetCapability() []User_Capability {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *User) GetNextTokenId() int64 {
	if m != nil {
		return m.NextTokenId
	}
	return 0
}

func (m *User) GetUserToken() []*UserToken {
	if m != nil {
		return m.UserToken
	}
	return nil
}

func (m *User) GetExt() map[string]*any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

// Represent the valid auth tokens.  When a user logs out, these will be
// deleted.
type UserToken struct {
	TokenId              int64                `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	CreatedTs            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	LastSeenTs           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_seen_ts,json=lastSeenTs,proto3" json:"last_seen_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{9}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetTokenId() int64 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

func (m *UserToken) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *UserToken) GetLastSeenTs() *timestamp.Timestamp {
	if m != nil {
		return m.LastSeenTs
	}
	return nil
}

type Configuration struct {
	// the minimum comment length in bytes.
	MinCommentLength *wrappers.Int64Value `protobuf:"bytes,1,opt,name=min_comment_length,json=minCommentLength,proto3" json:"min_comment_length,omitempty"`
	// the maximum comment length in bytes.
	MaxCommentLength *wrappers.Int64Value `protobuf:"bytes,2,opt,name=max_comment_length,json=maxCommentLength,proto3" json:"max_comment_length,omitempty"`
	// the minimum ident length for a user in bytes.
	MinIdentLength *wrappers.Int64Value `protobuf:"bytes,3,opt,name=min_ident_length,json=minIdentLength,proto3" json:"min_ident_length,omitempty"`
	// the maximum ident length for a user in bytes.
	MaxIdentLength *wrappers.Int64Value `protobuf:"bytes,4,opt,name=max_ident_length,json=maxIdentLength,proto3" json:"max_ident_length,omitempty"`
	// the minimum file name length in bytes.
	MinFileNameLength *wrappers.Int64Value `protobuf:"bytes,5,opt,name=min_file_name_length,json=minFileNameLength,proto3" json:"min_file_name_length,omitempty"`
	// the maximum file name length in bytes.
	MaxFileNameLength *wrappers.Int64Value `protobuf:"bytes,6,opt,name=max_file_name_length,json=maxFileNameLength,proto3" json:"max_file_name_length,omitempty"`
	// the minimum url length for pic upsert in bytes.
	MinUrlLength *wrappers.Int64Value `protobuf:"bytes,7,opt,name=min_url_length,json=minUrlLength,proto3" json:"min_url_length,omitempty"`
	// the maximum url length for pic upsert in bytes.
	MaxUrlLength *wrappers.Int64Value `protobuf:"bytes,8,opt,name=max_url_length,json=maxUrlLength,proto3" json:"max_url_length,omitempty"`
	// the minimum tag length in bytes.
	MinTagLength *wrappers.Int64Value `protobuf:"bytes,9,opt,name=min_tag_length,json=minTagLength,proto3" json:"min_tag_length,omitempty"`
	// the maximum tag length in bytes.
	MaxTagLength *wrappers.Int64Value `protobuf:"bytes,10,opt,name=max_tag_length,json=maxTagLength,proto3" json:"max_tag_length,omitempty"`
	// the capabilities of the anonymous user.
	AnonymousCapability *Configuration_CapabilitySet `protobuf:"bytes,11,opt,name=anonymous_capability,json=anonymousCapability,proto3" json:"anonymous_capability,omitempty"`
	// the capabilities of a newly created user.
	NewUserCapability *Configuration_CapabilitySet `protobuf:"bytes,12,opt,name=new_user_capability,json=newUserCapability,proto3" json:"new_user_capability,omitempty"`
	// the default number of index pics to return
	DefaultFindIndexPics *wrappers.Int64Value `protobuf:"bytes,13,opt,name=default_find_index_pics,json=defaultFindIndexPics,proto3" json:"default_find_index_pics,omitempty"`
	// the max number of index pics to return
	MaxFindIndexPics *wrappers.Int64Value `protobuf:"bytes,14,opt,name=max_find_index_pics,json=maxFindIndexPics,proto3" json:"max_find_index_pics,omitempty"`
	// the max duration a WEBM pic can be
	MaxWebmDuration *duration.Duration `protobuf:"bytes,15,opt,name=max_webm_duration,json=maxWebmDuration,proto3" json:"max_webm_duration,omitempty"`
	// allows users to reply to their own comments
	EnablePicCommentSelfReply *wrappers.BoolValue `protobuf:"bytes,16,opt,name=enable_pic_comment_self_reply,json=enablePicCommentSelfReply,proto3" json:"enable_pic_comment_self_reply,omitempty"`
	// allows a single user to reply multiple times to one comment
	EnablePicCommentSiblingReply *wrappers.BoolValue `protobuf:"bytes,17,opt,name=enable_pic_comment_sibling_reply,json=enablePicCommentSiblingReply,proto3" json:"enable_pic_comment_sibling_reply,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}            `json:"-"`
	XXX_unrecognized             []byte              `json:"-"`
	XXX_sizecache                int32               `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{10}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetMinCommentLength() *wrappers.Int64Value {
	if m != nil {
		return m.MinCommentLength
	}
	return nil
}

func (m *Configuration) GetMaxCommentLength() *wrappers.Int64Value {
	if m != nil {
		return m.MaxCommentLength
	}
	return nil
}

func (m *Configuration) GetMinIdentLength() *wrappers.Int64Value {
	if m != nil {
		return m.MinIdentLength
	}
	return nil
}

func (m *Configuration) GetMaxIdentLength() *wrappers.Int64Value {
	if m != nil {
		return m.MaxIdentLength
	}
	return nil
}

func (m *Configuration) GetMinFileNameLength() *wrappers.Int64Value {
	if m != nil {
		return m.MinFileNameLength
	}
	return nil
}

func (m *Configuration) GetMaxFileNameLength() *wrappers.Int64Value {
	if m != nil {
		return m.MaxFileNameLength
	}
	return nil
}

func (m *Configuration) GetMinUrlLength() *wrappers.Int64Value {
	if m != nil {
		return m.MinUrlLength
	}
	return nil
}

func (m *Configuration) GetMaxUrlLength() *wrappers.Int64Value {
	if m != nil {
		return m.MaxUrlLength
	}
	return nil
}

func (m *Configuration) GetMinTagLength() *wrappers.Int64Value {
	if m != nil {
		return m.MinTagLength
	}
	return nil
}

func (m *Configuration) GetMaxTagLength() *wrappers.Int64Value {
	if m != nil {
		return m.MaxTagLength
	}
	return nil
}

func (m *Configuration) GetAnonymousCapability() *Configuration_CapabilitySet {
	if m != nil {
		return m.AnonymousCapability
	}
	return nil
}

func (m *Configuration) GetNewUserCapability() *Configuration_CapabilitySet {
	if m != nil {
		return m.NewUserCapability
	}
	return nil
}

func (m *Configuration) GetDefaultFindIndexPics() *wrappers.Int64Value {
	if m != nil {
		return m.DefaultFindIndexPics
	}
	return nil
}

func (m *Configuration) GetMaxFindIndexPics() *wrappers.Int64Value {
	if m != nil {
		return m.MaxFindIndexPics
	}
	return nil
}

func (m *Configuration) GetMaxWebmDuration() *duration.Duration {
	if m != nil {
		return m.MaxWebmDuration
	}
	return nil
}

func (m *Configuration) GetEnablePicCommentSelfReply() *wrappers.BoolValue {
	if m != nil {
		return m.EnablePicCommentSelfReply
	}
	return nil
}

func (m *Configuration) GetEnablePicCommentSiblingReply() *wrappers.BoolValue {
	if m != nil {
		return m.EnablePicCommentSiblingReply
	}
	return nil
}

type Configuration_CapabilitySet struct {
	Capability           []User_Capability `protobuf:"varint,1,rep,packed,name=capability,proto3,enum=pixur.User_Capability" json:"capability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Configuration_CapabilitySet) Reset()         { *m = Configuration_CapabilitySet{} }
func (m *Configuration_CapabilitySet) String() string { return proto.CompactTextString(m) }
func (*Configuration_CapabilitySet) ProtoMessage()    {}
func (*Configuration_CapabilitySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{10, 0}
}

func (m *Configuration_CapabilitySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration_CapabilitySet.Unmarshal(m, b)
}
func (m *Configuration_CapabilitySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration_CapabilitySet.Marshal(b, m, deterministic)
}
func (m *Configuration_CapabilitySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration_CapabilitySet.Merge(m, src)
}
func (m *Configuration_CapabilitySet) XXX_Size() int {
	return xxx_messageInfo_Configuration_CapabilitySet.Size(m)
}
func (m *Configuration_CapabilitySet) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration_CapabilitySet.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration_CapabilitySet proto.InternalMessageInfo

func (m *Configuration_CapabilitySet) GetCapability() []User_Capability {
	if m != nil {
		return m.Capability
	}
	return nil
}

// CustomData is a free form message that can be used for experimental data.  It contains a 5-tuple
// of long keys which are indexed as a prefix.  The keys must be unique.
type CustomData struct {
	// The key type.  Pixur reserves types 0-127, inclusive.
	KeyType              int64                `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Key1                 int64                `protobuf:"varint,2,opt,name=key1,proto3" json:"key1,omitempty"`
	Key2                 int64                `protobuf:"varint,3,opt,name=key2,proto3" json:"key2,omitempty"`
	Key3                 int64                `protobuf:"varint,4,opt,name=key3,proto3" json:"key3,omitempty"`
	Key4                 int64                `protobuf:"varint,5,opt,name=key4,proto3" json:"key4,omitempty"`
	Key5                 int64                `protobuf:"varint,6,opt,name=key5,proto3" json:"key5,omitempty"`
	CreatedTs            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	ModifiedTs           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	Data                 *any.Any             `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CustomData) Reset()         { *m = CustomData{} }
func (m *CustomData) String() string { return proto.CompactTextString(m) }
func (*CustomData) ProtoMessage()    {}
func (*CustomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_962aa63430fd1f4b, []int{11}
}

func (m *CustomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomData.Unmarshal(m, b)
}
func (m *CustomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomData.Marshal(b, m, deterministic)
}
func (m *CustomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomData.Merge(m, src)
}
func (m *CustomData) XXX_Size() int {
	return xxx_messageInfo_CustomData.Size(m)
}
func (m *CustomData) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomData.DiscardUnknown(m)
}

var xxx_messageInfo_CustomData proto.InternalMessageInfo

func (m *CustomData) GetKeyType() int64 {
	if m != nil {
		return m.KeyType
	}
	return 0
}

func (m *CustomData) GetKey1() int64 {
	if m != nil {
		return m.Key1
	}
	return 0
}

func (m *CustomData) GetKey2() int64 {
	if m != nil {
		return m.Key2
	}
	return 0
}

func (m *CustomData) GetKey3() int64 {
	if m != nil {
		return m.Key3
	}
	return 0
}

func (m *CustomData) GetKey4() int64 {
	if m != nil {
		return m.Key4
	}
	return 0
}

func (m *CustomData) GetKey5() int64 {
	if m != nil {
		return m.Key5
	}
	return 0
}

func (m *CustomData) GetCreatedTs() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTs
	}
	return nil
}

func (m *CustomData) GetModifiedTs() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedTs
	}
	return nil
}

func (m *CustomData) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pixur.Pic_DeletionStatus_Reason", Pic_DeletionStatus_Reason_name, Pic_DeletionStatus_Reason_value)
	proto.RegisterEnum("pixur.Pic_File_Mime", Pic_File_Mime_name, Pic_File_Mime_value)
	proto.RegisterEnum("pixur.PicIdent_Type", PicIdent_Type_name, PicIdent_Type_value)
	proto.RegisterEnum("pixur.PicVote_Vote", PicVote_Vote_name, PicVote_Vote_value)
	proto.RegisterEnum("pixur.User_Capability", User_Capability_name, User_Capability_value)
	proto.RegisterType((*Pic)(nil), "pixur.Pic")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.Pic.ExtEntry")
	proto.RegisterType((*Pic_DeletionStatus)(nil), "pixur.Pic.DeletionStatus")
	proto.RegisterType((*Pic_FileSource)(nil), "pixur.Pic.FileSource")
	proto.RegisterType((*Pic_File)(nil), "pixur.Pic.File")
	proto.RegisterType((*PicIdent)(nil), "pixur.PicIdent")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.PicIdent.ExtEntry")
	proto.RegisterType((*AnimationInfo)(nil), "pixur.AnimationInfo")
	proto.RegisterType((*Tag)(nil), "pixur.Tag")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.Tag.ExtEntry")
	proto.RegisterType((*PicTag)(nil), "pixur.PicTag")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.PicTag.ExtEntry")
	proto.RegisterType((*PicComment)(nil), "pixur.PicComment")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.PicComment.ExtEntry")
	proto.RegisterType((*PicVote)(nil), "pixur.PicVote")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.PicVote.ExtEntry")
	proto.RegisterType((*UserEvent)(nil), "pixur.UserEvent")
	proto.RegisterType((*UserEvent_OutgoingUpsertPicVote)(nil), "pixur.UserEvent.OutgoingUpsertPicVote")
	proto.RegisterType((*UserEvent_IncomingUpsertPicVote)(nil), "pixur.UserEvent.IncomingUpsertPicVote")
	proto.RegisterType((*UserEvent_OutgoingPicComment)(nil), "pixur.UserEvent.OutgoingPicComment")
	proto.RegisterType((*UserEvent_IncomingPicComment)(nil), "pixur.UserEvent.IncomingPicComment")
	proto.RegisterType((*User)(nil), "pixur.User")
	proto.RegisterMapType((map[string]*any.Any)(nil), "pixur.User.ExtEntry")
	proto.RegisterType((*UserToken)(nil), "pixur.UserToken")
	proto.RegisterType((*Configuration)(nil), "pixur.Configuration")
	proto.RegisterType((*Configuration_CapabilitySet)(nil), "pixur.Configuration.CapabilitySet")
	proto.RegisterType((*CustomData)(nil), "pixur.CustomData")
}

func init() { proto.RegisterFile("pixur.proto", fileDescriptor_962aa63430fd1f4b) }

var fileDescriptor_962aa63430fd1f4b = []byte{
	// 2311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x5f, 0x6f, 0xdb, 0xc8,
	0x11, 0x3f, 0x89, 0x94, 0x44, 0x8d, 0x6d, 0x99, 0x5e, 0xff, 0x89, 0xac, 0x4b, 0xee, 0x0c, 0x1d,
	0x9a, 0xba, 0x41, 0x4f, 0xb9, 0x38, 0xe7, 0xe0, 0xae, 0xd7, 0x17, 0xd9, 0xa2, 0x6d, 0xb9, 0x8e,
	0x2c, 0x50, 0x54, 0x72, 0x2d, 0x0a, 0x10, 0x6b, 0x71, 0x25, 0x6f, 0xcd, 0x3f, 0x02, 0x49, 0xc5,
	0x52, 0xbf, 0x41, 0x9f, 0x8a, 0x3e, 0x17, 0x45, 0x81, 0xa2, 0xaf, 0xfd, 0x0a, 0xfd, 0x0e, 0x87,
	0x7e, 0x99, 0x7b, 0x2c, 0x76, 0xb9, 0x94, 0x48, 0xc9, 0x3e, 0xdb, 0x4d, 0x83, 0xbc, 0x08, 0xbb,
	0x33, 0xb3, 0xbf, 0x9d, 0xfd, 0xcd, 0xec, 0xcc, 0x8a, 0xb0, 0x34, 0xa4, 0xe3, 0x91, 0x5f, 0x1b,
	0xfa, 0x5e, 0xe8, 0xa1, 0x1c, 0x9f, 0x54, 0xb6, 0x07, 0x9e, 0x37, 0xb0, 0xc9, 0x73, 0x2e, 0xbc,
	0x18, 0xf5, 0x9f, 0x63, 0x77, 0x12, 0x59, 0x54, 0x3e, 0x9b, 0x57, 0x59, 0x23, 0x1f, 0x87, 0xd4,
	0x73, 0x85, 0xfe, 0xf3, 0x79, 0x7d, 0x48, 0x1d, 0x12, 0x84, 0xd8, 0x19, 0xde, 0x06, 0x70, 0xed,
	0xe3, 0xe1, 0x90, 0xf8, 0x41, 0xa4, 0xaf, 0xfe, 0x69, 0x19, 0xa4, 0x36, 0xed, 0xa1, 0x4d, 0xc8,
	0x0f, 0x69, 0xcf, 0xa4, 0x56, 0x39, 0xb3, 0x93, 0xd9, 0x95, 0xf4, 0xdc, 0x90, 0xf6, 0x9a, 0x16,
	0xfa, 0x02, 0xe4, 0x3e, 0xb5, 0x49, 0x79, 0x6b, 0x27, 0xb3, 0xbb, 0xb4, 0xb7, 0x5a, 0x8b, 0xbc,
	0x6f, 0xd3, 0x5e, 0xed, 0x88, 0xda, 0x44, 0xe7, 0x4a, 0xf4, 0x2d, 0x40, 0xcf, 0x27, 0x38, 0x24,
	0x96, 0x19, 0x06, 0x65, 0xe0, 0xa6, 0x95, 0x5a, 0xb4, 0x71, 0x2d, 0xde, 0xb8, 0x66, 0xc4, 0x9e,
	0xe9, 0x45, 0x61, 0x6d, 0x04, 0xe8, 0x3b, 0x58, 0x72, 0x3c, 0x8b, 0xf6, 0x69, 0xb4, 0x76, 0xe9,
	0xce, 0xb5, 0x10, 0x9b, 0x1b, 0x01, 0x3a, 0x80, 0x55, 0x8b, 0xd8, 0x84, 0xd1, 0x61, 0x06, 0x21,
	0x0e, 0x47, 0x41, 0x79, 0x99, 0x03, 0x6c, 0x27, 0xfc, 0x6c, 0x08, 0x8b, 0x0e, 0x37, 0xd0, 0x4b,
	0x56, 0x6a, 0x8e, 0x9e, 0x00, 0xbc, 0xa3, 0xe4, 0xda, 0xec, 0x79, 0x23, 0x37, 0x2c, 0x97, 0xf8,
	0xd9, 0x8b, 0x4c, 0x72, 0xc8, 0x04, 0xe8, 0x4b, 0xc8, 0x07, 0xde, 0xc8, 0xef, 0x91, 0xf2, 0xea,
	0x8e, 0xb4, 0xbb, 0xb4, 0xb7, 0x39, 0xc7, 0x40, 0x87, 0x2b, 0x75, 0x61, 0x84, 0x1e, 0x41, 0xe1,
	0x9d, 0x17, 0x12, 0x73, 0x34, 0x2c, 0xaf, 0x71, 0xa8, 0x3c, 0x9b, 0x76, 0x87, 0xe8, 0x53, 0x28,
	0x72, 0x85, 0xe5, 0x5d, 0xbb, 0x65, 0xc4, 0x55, 0x0a, 0x13, 0x34, 0xbc, 0x6b, 0x17, 0xfd, 0x0c,
	0x24, 0x32, 0x0e, 0xcb, 0xeb, 0x7c, 0x87, 0xf5, 0xc4, 0x0e, 0xda, 0x38, 0xd4, 0xdc, 0xd0, 0x9f,
	0xe8, 0x4c, 0x8f, 0xbe, 0x84, 0x62, 0x78, 0x39, 0x72, 0x2e, 0x5c, 0x4c, 0xed, 0xf2, 0x26, 0x37,
	0x5e, 0x08, 0xc8, 0xcc, 0xa2, 0xf2, 0x17, 0x09, 0x4a, 0xe9, 0xc3, 0xa3, 0x23, 0x58, 0x73, 0xb0,
	0x7f, 0x45, 0x2c, 0x93, 0xb3, 0x10, 0x71, 0x9e, 0xb9, 0x93, 0xf3, 0xd5, 0x68, 0x51, 0x23, 0x5a,
	0x63, 0x04, 0xe8, 0x04, 0xd0, 0x90, 0xb8, 0x16, 0x75, 0x07, 0x49, 0xa0, 0xec, 0x9d, 0x40, 0xaa,
	0x58, 0x35, 0x43, 0x3a, 0x82, 0x35, 0xdc, 0x0b, 0x47, 0xd8, 0x4e, 0x02, 0x49, 0x77, 0x7b, 0x14,
	0x2d, 0x9a, 0xe1, 0x94, 0xa1, 0x60, 0x91, 0x10, 0x53, 0x3b, 0x28, 0xcb, 0x3b, 0x99, 0xdd, 0xa2,
	0x1e, 0x4f, 0xd1, 0x37, 0x90, 0xf7, 0x09, 0x0e, 0x3c, 0xb7, 0x9c, 0xdb, 0xc9, 0xec, 0x96, 0xf6,
	0x76, 0x6e, 0xcd, 0x8d, 0x9a, 0xce, 0xed, 0x74, 0x61, 0x8f, 0x1e, 0x43, 0x31, 0x24, 0xce, 0xd0,
	0xf3, 0xb1, 0x3f, 0x29, 0xe7, 0x77, 0x32, 0xbb, 0x8a, 0x3e, 0x13, 0x54, 0x5f, 0x42, 0x3e, 0xb2,
	0x47, 0x4b, 0x50, 0xe8, 0xb6, 0x7e, 0xd3, 0x3a, 0x7f, 0xdb, 0x52, 0x3f, 0x41, 0x0a, 0xc8, 0xad,
	0xf3, 0x96, 0xa6, 0x66, 0x10, 0x82, 0x92, 0xde, 0x3d, 0xd3, 0xcc, 0x37, 0xcd, 0xf3, 0xb3, 0xba,
	0xd1, 0x3c, 0x6f, 0xa9, 0xd9, 0xca, 0x3f, 0x32, 0x00, 0xb3, 0xb4, 0x41, 0x2a, 0x48, 0x23, 0xdf,
	0xe6, 0x11, 0x28, 0xea, 0x6c, 0x88, 0x2a, 0xa0, 0xf8, 0xa4, 0x4f, 0x7c, 0x9f, 0xf8, 0x9c, 0xcf,
	0xa2, 0x3e, 0x9d, 0xcf, 0x5d, 0x33, 0xe9, 0x21, 0xd7, 0xec, 0x11, 0x14, 0x46, 0x01, 0xf1, 0xd9,
	0xf5, 0x96, 0xa3, 0xbc, 0x64, 0xd3, 0xa6, 0x85, 0x10, 0xc8, 0x2e, 0x76, 0x08, 0xe7, 0xa6, 0xa8,
	0xf3, 0x71, 0xe5, 0x0c, 0x94, 0x38, 0xf1, 0x98, 0x87, 0x57, 0x64, 0x12, 0x7b, 0x78, 0x45, 0x26,
	0xe8, 0x19, 0xe4, 0xde, 0x61, 0x7b, 0x44, 0x44, 0xb8, 0x37, 0x16, 0x1c, 0xa8, 0xbb, 0x13, 0x3d,
	0x32, 0xf9, 0x55, 0xf6, 0x9b, 0x4c, 0xe5, 0xc7, 0x2c, 0xc8, 0xec, 0xc8, 0x68, 0x03, 0x72, 0xd4,
	0xb5, 0xc8, 0x38, 0x2e, 0x30, 0x7c, 0xc2, 0x1c, 0x08, 0xe8, 0x1f, 0x23, 0x34, 0x49, 0xe7, 0x63,
	0xb4, 0x0b, 0xb2, 0x43, 0x1d, 0xc2, 0x8f, 0x58, 0xda, 0xdb, 0x98, 0xcb, 0xf1, 0xda, 0x6b, 0xea,
	0x10, 0x9d, 0x5b, 0x30, 0xcc, 0x6b, 0x6a, 0x85, 0x97, 0xe2, 0x54, 0xd1, 0x04, 0x6d, 0x41, 0xfe,
	0x92, 0xd0, 0xc1, 0x65, 0xc8, 0x8f, 0x25, 0xe9, 0x62, 0x36, 0x47, 0x60, 0xfe, 0x3d, 0xea, 0x54,
	0xe1, 0x41, 0x75, 0xea, 0x3b, 0x28, 0x61, 0x97, 0x3a, 0xbc, 0x6e, 0x9b, 0xd4, 0xed, 0x7b, 0x65,
	0x45, 0x70, 0x17, 0x9d, 0xac, 0x1e, 0x2b, 0x9b, 0x6e, 0xdf, 0xd3, 0x57, 0x70, 0x72, 0x5a, 0xfd,
	0x16, 0x64, 0x76, 0xe0, 0x85, 0x2c, 0x3b, 0x6d, 0x6b, 0xc7, 0x6a, 0x06, 0x15, 0x40, 0x3a, 0x6e,
	0x1e, 0xa9, 0x59, 0x36, 0x68, 0xb7, 0x8e, 0x55, 0x89, 0xe9, 0xde, 0x6a, 0x07, 0xaf, 0x55, 0xf9,
	0x54, 0x56, 0xb2, 0xaa, 0x74, 0x2a, 0x2b, 0x12, 0x1f, 0xcb, 0x6a, 0xee, 0x54, 0x56, 0x72, 0x6a,
	0xfe, 0x54, 0x56, 0x8a, 0x2a, 0x9c, 0xca, 0xca, 0x8a, 0x5a, 0x3a, 0x95, 0x15, 0x55, 0x5d, 0x3b,
	0x95, 0x95, 0x0d, 0x75, 0xb3, 0xfa, 0x43, 0x16, 0x94, 0x36, 0x2b, 0xfb, 0xc4, 0x0d, 0x6f, 0x6b,
	0x08, 0xbb, 0x20, 0x87, 0x93, 0x61, 0x14, 0xaf, 0x54, 0x6c, 0xf8, 0xaa, 0x9a, 0x31, 0x19, 0x12,
	0x9d, 0x5b, 0xb0, 0xd8, 0x44, 0x89, 0xc2, 0xc2, 0xb8, 0x2c, 0x52, 0x02, 0x7d, 0x01, 0x4b, 0x56,
	0x2f, 0xfc, 0xca, 0xe4, 0x33, 0x76, 0x59, 0xa5, 0xdd, 0xec, 0x41, 0x56, 0xcd, 0xe8, 0xc0, 0xc4,
	0x6f, 0xb8, 0x14, 0x3d, 0x8b, 0x0a, 0x62, 0x8e, 0xd7, 0xb8, 0xf2, 0xfc, 0x1e, 0xa9, 0xaa, 0xf8,
	0xff, 0xcd, 0xd6, 0xea, 0x39, 0xc8, 0xec, 0x08, 0x0b, 0x6c, 0x77, 0x4e, 0xea, 0x2f, 0x22, 0x92,
	0x5f, 0x37, 0xf6, 0x55, 0x09, 0x15, 0x21, 0xd7, 0x38, 0x34, 0xcc, 0xaf, 0x54, 0x19, 0x95, 0x00,
	0x3a, 0x27, 0xf5, 0xfd, 0x17, 0x7b, 0xe6, 0xde, 0xfe, 0x2b, 0x35, 0x57, 0x95, 0x95, 0x8c, 0x9a,
	0x79, 0x96, 0xef, 0x9c, 0xd4, 0xf7, 0xf6, 0x5f, 0x55, 0x8f, 0x60, 0x25, 0x15, 0x5e, 0xb4, 0x0f,
	0x4a, 0xdc, 0xc3, 0x45, 0xe9, 0xdd, 0x5e, 0x70, 0xaa, 0x21, 0x0c, 0xf4, 0xa9, 0x69, 0xf5, 0xdf,
	0x59, 0x90, 0x0c, 0x3c, 0x60, 0x61, 0x09, 0xf1, 0x20, 0x11, 0x96, 0x10, 0x0f, 0x12, 0xf7, 0x38,
	0x3b, 0xbb, 0xc7, 0xe8, 0x73, 0x58, 0x1a, 0x05, 0x78, 0x40, 0x44, 0x6f, 0x93, 0xb8, 0x3d, 0x70,
	0x51, 0xd4, 0xdc, 0x3e, 0xd6, 0x7d, 0x10, 0xfd, 0x4e, 0x49, 0xf5, 0x3b, 0x03, 0x0f, 0x3e, 0x68,
	0x64, 0xff, 0x93, 0x85, 0x7c, 0x9b, 0xf6, 0x04, 0x87, 0x37, 0xa5, 0xf6, 0x8c, 0xda, 0xec, 0x4d,
	0xd4, 0x4a, 0x09, 0x6a, 0x13, 0xf5, 0x54, 0x49, 0xd5, 0xd3, 0x8f, 0x45, 0xe9, 0x6e, 0x44, 0x69,
	0x91, 0x53, 0xba, 0x35, 0xbb, 0x31, 0x1f, 0x9a, 0xd5, 0x3f, 0x4b, 0x00, 0x6d, 0xda, 0x3b, 0xf4,
	0x1c, 0xe7, 0x27, 0x8a, 0xc6, 0x13, 0x80, 0x5e, 0x64, 0x31, 0x63, 0xb7, 0x28, 0x24, 0x4d, 0x0b,
	0x3d, 0x83, 0xb5, 0x58, 0x3d, 0xc4, 0xbe, 0xb0, 0x8a, 0xd2, 0x75, 0x55, 0x28, 0xda, 0x5c, 0xde,
	0xb4, 0x7e, 0xb2, 0x93, 0x85, 0x8c, 0x82, 0x42, 0x14, 0x26, 0x36, 0x9e, 0x8b, 0x46, 0xee, 0x3d,
	0xa2, 0x91, 0x7f, 0x50, 0x34, 0x7e, 0x99, 0x4c, 0xf0, 0xca, 0x2c, 0x1a, 0x82, 0xa6, 0x0f, 0x1a,
	0x91, 0xbf, 0x49, 0x50, 0x68, 0xd3, 0xde, 0x1b, 0x2f, 0x24, 0xb7, 0x85, 0x23, 0xc1, 0x61, 0x36,
	0xc5, 0xe1, 0xb4, 0x45, 0x17, 0x92, 0x2d, 0xfa, 0xe7, 0x20, 0xb3, 0xa7, 0xaa, 0x68, 0xc7, 0x89,
	0xf7, 0x29, 0xdb, 0xa3, 0xc6, 0x7e, 0x74, 0x6e, 0x30, 0x47, 0xb7, 0xfc, 0x1e, 0x74, 0xe7, 0x1e,
	0x44, 0xf7, 0x2f, 0x22, 0xba, 0xf3, 0x9c, 0xee, 0x47, 0x73, 0xfe, 0x7d, 0x48, 0xae, 0xf7, 0x40,
	0xe6, 0x3c, 0xa7, 0xba, 0x45, 0x1e, 0xb2, 0xdd, 0xb6, 0x9a, 0x61, 0x5d, 0xa3, 0xc1, 0x24, 0x59,
	0xa6, 0x6e, 0x69, 0x5d, 0x43, 0xaf, 0x9f, 0xa9, 0x52, 0xf5, 0x87, 0x3c, 0x14, 0xbb, 0x01, 0xf1,
	0xb5, 0x77, 0xec, 0xc2, 0x24, 0x42, 0x91, 0xb9, 0x39, 0x14, 0xd9, 0x64, 0x28, 0xde, 0xe3, 0x09,
	0x38, 0xc7, 0xb0, 0xfc, 0x20, 0x86, 0x31, 0x94, 0xbd, 0x51, 0x38, 0xf0, 0xd8, 0x8b, 0x7f, 0x34,
	0x0c, 0x88, 0x1f, 0x9a, 0x2c, 0xb1, 0x78, 0x5a, 0x44, 0xb1, 0x7a, 0x2a, 0x68, 0x9f, 0x1e, 0xad,
	0x76, 0x2e, 0x16, 0x74, 0xb9, 0xbd, 0x08, 0xc7, 0xc9, 0x27, 0xfa, 0xa6, 0x77, 0x93, 0x82, 0x6d,
	0x41, 0xdd, 0x9e, 0xe7, 0xdc, 0xb4, 0x45, 0xfe, 0x96, 0x2d, 0x9a, 0x62, 0xc1, 0xc2, 0x16, 0xf4,
	0x26, 0x05, 0x7a, 0x0b, 0x1b, 0xd3, 0x53, 0x30, 0x6c, 0x51, 0x5b, 0x44, 0xa9, 0xfd, 0xe2, 0xd6,
	0x13, 0xcc, 0x6e, 0xee, 0xc9, 0x27, 0x3a, 0xf2, 0x16, 0xa4, 0x0c, 0x78, 0xea, 0x7b, 0x12, 0x58,
	0xb9, 0x05, 0x38, 0xf6, 0x3b, 0x0d, 0x4c, 0x17, 0xa4, 0x95, 0x1a, 0x6c, 0xde, 0x48, 0xe3, 0x2d,
	0x37, 0xbb, 0xf2, 0x06, 0x36, 0x6f, 0xe4, 0x04, 0x3d, 0x85, 0xd5, 0x60, 0x74, 0xf1, 0x07, 0xd2,
	0x0b, 0xcd, 0x74, 0xbe, 0xad, 0x08, 0x71, 0x37, 0x4a, 0xbb, 0x19, 0x6e, 0x36, 0x89, 0x7b, 0x0a,
	0x68, 0x91, 0x8c, 0xb9, 0xb2, 0x9e, 0x99, 0x2f, 0xeb, 0xb7, 0x63, 0x2d, 0x9e, 0xff, 0x7f, 0xc3,
	0x3a, 0xc8, 0x81, 0x44, 0xde, 0x85, 0xd5, 0x7f, 0x2a, 0x20, 0xb3, 0x03, 0xdc, 0x7e, 0x9d, 0xb6,
	0x20, 0x1f, 0x90, 0x9e, 0x4f, 0x42, 0xbe, 0x7e, 0x59, 0x17, 0x33, 0x7e, 0xcd, 0xd8, 0xa3, 0x52,
	0x74, 0xf7, 0x68, 0xf2, 0xd1, 0x0a, 0xd9, 0xaf, 0x61, 0xd9, 0xc6, 0x41, 0x68, 0x06, 0x84, 0xb8,
	0xf7, 0xec, 0x3a, 0xcc, 0xbe, 0x43, 0x88, 0x6b, 0x04, 0xe8, 0x15, 0x40, 0x0f, 0x0f, 0xf1, 0x05,
	0xb5, 0x69, 0x38, 0x29, 0x17, 0x76, 0xa4, 0xdd, 0xd2, 0xf4, 0x29, 0xc0, 0xd8, 0xa9, 0x1d, 0x4e,
	0xb5, 0x7a, 0xc2, 0x12, 0x55, 0x61, 0xc5, 0x25, 0xe3, 0xd0, 0x0c, 0xbd, 0x2b, 0xe2, 0xce, 0x9e,
	0x34, 0x4b, 0x4c, 0x68, 0x30, 0x59, 0xd3, 0x42, 0xcf, 0x01, 0x38, 0xb1, 0xdc, 0x46, 0x3c, 0x33,
	0xd4, 0x04, 0x36, 0xb7, 0xd3, 0x8b, 0xa3, 0x78, 0x88, 0x9e, 0x46, 0x35, 0x19, 0xb8, 0xe5, 0x46,
	0xd2, 0x8b, 0x0f, 0x59, 0x90, 0xff, 0x2a, 0x03, 0xcc, 0x4e, 0x99, 0xae, 0xcb, 0x25, 0x80, 0x76,
	0xf3, 0xd0, 0x3c, 0xd4, 0xb5, 0xba, 0xc1, 0xfe, 0x9f, 0x2f, 0x83, 0xc2, 0xe6, 0xba, 0x56, 0x6f,
	0xa8, 0x59, 0xb4, 0x02, 0x45, 0x36, 0x6b, 0xb6, 0x1a, 0xda, 0xf7, 0xaa, 0x84, 0xd6, 0x61, 0x95,
	0x4d, 0x3b, 0xe7, 0x47, 0x86, 0xd9, 0xd0, 0xce, 0x34, 0x43, 0x53, 0x73, 0xb1, 0xf0, 0xa4, 0xae,
	0x37, 0x62, 0x61, 0x3e, 0x5e, 0xd8, 0xee, 0xea, 0xc7, 0x9a, 0x5a, 0x40, 0x9f, 0xc2, 0x23, 0x36,
	0xed, 0xb6, 0x1b, 0x75, 0x83, 0xfd, 0xf7, 0xd7, 0xde, 0x9a, 0x87, 0xe7, 0xdd, 0x96, 0xa1, 0xe9,
	0xaa, 0x82, 0x10, 0x94, 0x98, 0xd2, 0xa8, 0x1f, 0xc7, 0x6e, 0x14, 0xd1, 0x16, 0x20, 0xee, 0xd6,
	0xf9, 0xeb, 0xd7, 0x5a, 0xcb, 0x88, 0xe5, 0x10, 0x6f, 0xf6, 0xe6, 0xdc, 0xd0, 0x62, 0xe1, 0x12,
	0x5a, 0x85, 0xa5, 0x6e, 0x47, 0xd3, 0x63, 0x81, 0x8c, 0x2a, 0xb0, 0xc5, 0x05, 0x62, 0xbf, 0xc3,
	0x7a, 0xbb, 0x7e, 0xd0, 0x3c, 0x6b, 0x1a, 0xbf, 0x55, 0x97, 0xd9, 0x6e, 0x5c, 0xc7, 0x4e, 0x68,
	0x76, 0xb4, 0xb3, 0x23, 0x75, 0x05, 0xad, 0xc1, 0xca, 0x4c, 0x56, 0x3f, 0x3b, 0x53, 0x4b, 0xa8,
	0x0c, 0x1b, 0x6c, 0x23, 0xed, 0x7b, 0x43, 0x6b, 0x75, 0x9a, 0xe7, 0xad, 0x18, 0x7c, 0x35, 0x76,
	0x6d, 0xa6, 0xe1, 0x5c, 0xa9, 0x68, 0x07, 0x1e, 0x27, 0x5d, 0x5e, 0x58, 0xb9, 0x86, 0x3e, 0x83,
	0xca, 0xcd, 0x16, 0x1c, 0x01, 0xa1, 0xc7, 0x50, 0x8e, 0x89, 0x58, 0x58, 0xbd, 0xce, 0x0e, 0xb5,
	0xa8, 0xe5, 0x2b, 0x37, 0xd0, 0x13, 0xd8, 0x9e, 0xd2, 0xb2, 0xb0, 0x74, 0x33, 0xa6, 0x7f, 0x4e,
	0xcd, 0xd7, 0x6e, 0x55, 0xff, 0x9e, 0x89, 0x5a, 0x6f, 0x94, 0xa1, 0xdb, 0xa0, 0x4c, 0x33, 0x3e,
	0x2a, 0x16, 0x85, 0x50, 0x64, 0x7b, 0xfa, 0xfe, 0x67, 0x1f, 0x72, 0xff, 0xe7, 0xaf, 0xb0, 0xf4,
	0x90, 0x2b, 0x5c, 0xfd, 0x11, 0x60, 0xe5, 0xd0, 0x73, 0xfb, 0x74, 0x20, 0xfe, 0xf7, 0xa1, 0x26,
	0x20, 0x87, 0xba, 0x71, 0x47, 0x31, 0x6d, 0xe2, 0x0e, 0xc2, 0x4b, 0xf1, 0xc7, 0xf1, 0xd3, 0x05,
	0xd4, 0xa6, 0x1b, 0xbe, 0xfa, 0x9a, 0xff, 0x89, 0xd6, 0x55, 0x87, 0xba, 0xa2, 0xb8, 0x9e, 0xf1,
	0x45, 0x1c, 0x0a, 0x8f, 0xe7, 0xa1, 0xb2, 0xf7, 0x81, 0xc2, 0xe3, 0x34, 0x94, 0x06, 0x0c, 0xde,
	0xe4, 0xd5, 0x32, 0x06, 0x92, 0xee, 0x06, 0x2a, 0x39, 0xd4, 0xe5, 0xff, 0xe1, 0x13, 0x30, 0x78,
	0x9c, 0x86, 0x91, 0xef, 0x03, 0x83, 0xc7, 0x49, 0x98, 0x33, 0xd8, 0x60, 0xde, 0xf4, 0xa9, 0x4d,
	0x4c, 0xf6, 0xf7, 0x2c, 0x86, 0xca, 0xdd, 0x0d, 0xb5, 0xe6, 0x50, 0xf7, 0x88, 0xda, 0xa4, 0x85,
	0x1d, 0x92, 0x40, 0xc3, 0xe3, 0x45, 0xb4, 0xfc, 0x7d, 0xd0, 0xf0, 0x78, 0x0e, 0xad, 0x0e, 0xec,
	0xd0, 0xe6, 0xc8, 0xb7, 0x63, 0x9c, 0xc2, 0xdd, 0x38, 0xcb, 0x0e, 0x75, 0xbb, 0xbe, 0x9d, 0x80,
	0xc0, 0xe3, 0x24, 0x84, 0x72, 0x1f, 0x08, 0x3c, 0x4e, 0x43, 0x50, 0xd7, 0x64, 0x7f, 0x6f, 0x05,
	0x44, 0xf1, 0x7e, 0x5e, 0x18, 0x78, 0x90, 0xf6, 0x22, 0x01, 0x01, 0xf7, 0xf3, 0x62, 0x06, 0xd1,
	0x85, 0x0d, 0xec, 0x7a, 0xee, 0xc4, 0xf1, 0x46, 0x81, 0x99, 0x68, 0x55, 0xd1, 0x57, 0xff, 0xaa,
	0x68, 0x12, 0xa9, 0xfc, 0x4f, 0xf4, 0xac, 0x0e, 0x09, 0xf5, 0xf5, 0xe9, 0xfa, 0x44, 0x95, 0xd7,
	0x61, 0xdd, 0x25, 0xd7, 0xd1, 0xbb, 0x26, 0x81, 0xba, 0x7c, 0x6f, 0xd4, 0x35, 0x97, 0x5c, 0xb3,
	0xba, 0x90, 0xc2, 0x7c, 0x64, 0x91, 0x3e, 0x1e, 0xd9, 0xa1, 0xd9, 0xa7, 0xae, 0x65, 0xf2, 0xe7,
	0x37, 0x7b, 0xdb, 0x05, 0xe5, 0x95, 0xbb, 0x8f, 0xbd, 0x21, 0xd6, 0x1e, 0x51, 0xd7, 0x6a, 0xb2,
	0x95, 0x6d, 0xda, 0x0b, 0xd0, 0x29, 0xac, 0x47, 0x89, 0x95, 0xc6, 0x2b, 0xdd, 0xef, 0x02, 0xa6,
	0xb1, 0x34, 0x60, 0xb9, 0x66, 0x5e, 0x93, 0x0b, 0xc7, 0x9c, 0x7e, 0x4e, 0x5a, 0xbd, 0xeb, 0x73,
	0xd2, 0xaa, 0x83, 0xc7, 0x6f, 0xc9, 0x85, 0x13, 0x0b, 0xd0, 0xef, 0xe1, 0x09, 0x71, 0xf1, 0x85,
	0x4d, 0x92, 0xcf, 0x56, 0x33, 0x20, 0x76, 0xdf, 0xf4, 0xc9, 0xd0, 0x9e, 0x94, 0xd5, 0x5b, 0xca,
	0xd7, 0x81, 0xe7, 0xd9, 0x91, 0x6f, 0xdb, 0x11, 0xc0, 0xec, 0x29, 0xd7, 0x21, 0x76, 0x5f, 0x67,
	0x8b, 0xd1, 0x05, 0xec, 0xdc, 0x84, 0x4e, 0x2f, 0x6c, 0xf6, 0x50, 0x8e, 0x36, 0x58, 0xbb, 0x73,
	0x83, 0xc7, 0x0b, 0x1b, 0x44, 0x00, 0x7c, 0x8f, 0xca, 0x31, 0xac, 0xa4, 0x82, 0x39, 0xf7, 0x0a,
	0xca, 0xdc, 0xf7, 0x15, 0x54, 0xfd, 0x57, 0x16, 0xe0, 0x70, 0x14, 0x84, 0x9e, 0xd3, 0xc0, 0x21,
	0x66, 0xdd, 0xe1, 0x8a, 0x4c, 0x4c, 0xfe, 0xad, 0x53, 0x74, 0x87, 0x2b, 0x32, 0xe1, 0xdf, 0x06,
	0x11, 0xc8, 0x57, 0x64, 0xf2, 0x22, 0xfe, 0x64, 0xcd, 0xc6, 0x42, 0xb6, 0x27, 0xbe, 0x5a, 0xf0,
	0xb1, 0x90, 0xbd, 0x14, 0xdf, 0x29, 0xf8, 0x58, 0xc8, 0xbe, 0x16, 0x1f, 0xa6, 0xf9, 0x58, 0xc8,
	0xf6, 0x79, 0x81, 0x89, 0x64, 0xfb, 0x73, 0x1d, 0xa8, 0xf0, 0x1e, 0x2f, 0x50, 0xe5, 0x81, 0xdf,
	0x91, 0x64, 0x0b, 0x87, 0x58, 0x94, 0x87, 0x9b, 0xdf, 0x5b, 0xdc, 0xe2, 0x40, 0xf9, 0x5d, 0x3e,
	0xe8, 0x5d, 0x12, 0x07, 0x5f, 0xe4, 0xb9, 0xf6, 0xe5, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2f,
	0x92, 0xfe, 0xf8, 0xdb, 0x1c, 0x00, 0x00,
}
