// Code generated by protoc-gen-go.
// source: pixur.proto
// DO NOT EDIT!

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	pixur.proto

It has these top-level messages:
	Pic
	Tag
	PicTag
	Timestamp
*/
package schema

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Pic_Mime int32

const (
	Pic_UNKNOWN Pic_Mime = 0
	Pic_JPEG    Pic_Mime = 1
	Pic_GIF     Pic_Mime = 2
	Pic_PNG     Pic_Mime = 3
	Pic_WEBM    Pic_Mime = 4
)

var Pic_Mime_name = map[int32]string{
	0: "UNKNOWN",
	1: "JPEG",
	2: "GIF",
	3: "PNG",
	4: "WEBM",
}
var Pic_Mime_value = map[string]int32{
	"UNKNOWN": 0,
	"JPEG":    1,
	"GIF":     2,
	"PNG":     3,
	"WEBM":    4,
}

func (x Pic_Mime) String() string {
	return proto.EnumName(Pic_Mime_name, int32(x))
}

type Pic struct {
	PicId             int64      `protobuf:"varint,1,opt,name=pic_id" json:"pic_id,omitempty"`
	FileSize          int64      `protobuf:"varint,2,opt,name=file_size" json:"file_size,omitempty"`
	Mime              Pic_Mime   `protobuf:"varint,3,opt,name=mime,enum=pixur.Pic_Mime" json:"mime,omitempty"`
	Width             int64      `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
	Height            int64      `protobuf:"varint,5,opt,name=height" json:"height,omitempty"`
	Sha256Hash        []byte     `protobuf:"bytes,9,opt,name=sha256_hash,proto3" json:"sha256_hash,omitempty"`
	CreatedTimestamp  *Timestamp `protobuf:"bytes,10,opt,name=created_timestamp" json:"created_timestamp,omitempty"`
	ModifiedTimestamp *Timestamp `protobuf:"bytes,11,opt,name=modified_timestamp" json:"modified_timestamp,omitempty"`
}

func (m *Pic) Reset()         { *m = Pic{} }
func (m *Pic) String() string { return proto.CompactTextString(m) }
func (*Pic) ProtoMessage()    {}

func (m *Pic) GetCreatedTimestamp() *Timestamp {
	if m != nil {
		return m.CreatedTimestamp
	}
	return nil
}

func (m *Pic) GetModifiedTimestamp() *Timestamp {
	if m != nil {
		return m.ModifiedTimestamp
	}
	return nil
}

type Tag struct {
	TagId             int64      `protobuf:"varint,1,opt,name=tag_id" json:"tag_id,omitempty"`
	Name              string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UsageCount        int64      `protobuf:"varint,3,opt,name=usage_count" json:"usage_count,omitempty"`
	CreatedTimestamp  *Timestamp `protobuf:"bytes,6,opt,name=created_timestamp" json:"created_timestamp,omitempty"`
	ModifiedTimestamp *Timestamp `protobuf:"bytes,7,opt,name=modified_timestamp" json:"modified_timestamp,omitempty"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}

func (m *Tag) GetCreatedTimestamp() *Timestamp {
	if m != nil {
		return m.CreatedTimestamp
	}
	return nil
}

func (m *Tag) GetModifiedTimestamp() *Timestamp {
	if m != nil {
		return m.ModifiedTimestamp
	}
	return nil
}

type PicTag struct {
	PicId             int64      `protobuf:"varint,1,opt,name=pic_id" json:"pic_id,omitempty"`
	TagId             int64      `protobuf:"varint,2,opt,name=tag_id" json:"tag_id,omitempty"`
	Name              string     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	CreatedTimestamp  *Timestamp `protobuf:"bytes,6,opt,name=created_timestamp" json:"created_timestamp,omitempty"`
	ModifiedTimestamp *Timestamp `protobuf:"bytes,7,opt,name=modified_timestamp" json:"modified_timestamp,omitempty"`
}

func (m *PicTag) Reset()         { *m = PicTag{} }
func (m *PicTag) String() string { return proto.CompactTextString(m) }
func (*PicTag) ProtoMessage()    {}

func (m *PicTag) GetCreatedTimestamp() *Timestamp {
	if m != nil {
		return m.CreatedTimestamp
	}
	return nil
}

func (m *PicTag) GetModifiedTimestamp() *Timestamp {
	if m != nil {
		return m.ModifiedTimestamp
	}
	return nil
}

// This is the same as google.protobuf.Timestamp, until it becomes standard.
type Timestamp struct {
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanos   int32 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("pixur.Pic_Mime", Pic_Mime_name, Pic_Mime_value)
}
